[package]
name = "openapi-bindgen-cli"
description = "CLI for openapi-bindgen"
readme = "README.md"
version.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true
edition.workspace = true
authors.workspace = true

[[bin]]
name = "openapi-bindgen"
path = "src/main.rs"

[features]

[dependencies]
openapi-bindgen = { workspace = true }
anyhow = "1"
heck = "0.5"
indexmap = "2"
openapiv3 = "2"
serde_json = "1"

[dev-dependencies]

[lints]
workspace = true
