// AUTOGENERATED by openapi-bindgen. Do not edit by hand.

use crate::runtime::{dispatch, AuthApply, AuthKind, FieldLocation, FieldSpec, OpSpec};
use crate::exports::autostamp::zuora::entities as iface_entities;
use serde_json::{Map, Value};

const OP_ENTITIES_GET_ENTITIES: OpSpec = OpSpec {
    method: "GET",
    path_template: "/v1/entities",
    fields: &[
        FieldSpec { snake: "zuora_track_id", wire: "Zuora-Track-Id", location: FieldLocation::Header },
        FieldSpec { snake: "zuora_entity_ids", wire: "Zuora-Entity-Ids", location: FieldLocation::Header },
        FieldSpec { snake: "provisioned", wire: "provisioned", location: FieldLocation::Query },
    ],
    auth: &[
    ],
};

const OP_ENTITIES_POST_ENTITIES: OpSpec = OpSpec {
    method: "POST",
    path_template: "/v1/entities",
    fields: &[
        FieldSpec { snake: "zuora_track_id", wire: "Zuora-Track-Id", location: FieldLocation::Header },
        FieldSpec { snake: "zuora_entity_ids", wire: "Zuora-Entity-Ids", location: FieldLocation::Header },
        FieldSpec { snake: "display_name", wire: "displayName", location: FieldLocation::Body },
        FieldSpec { snake: "locale", wire: "locale", location: FieldLocation::Body },
        FieldSpec { snake: "name", wire: "name", location: FieldLocation::Body },
        FieldSpec { snake: "parent_id", wire: "parentId", location: FieldLocation::Body },
        FieldSpec { snake: "timezone", wire: "timezone", location: FieldLocation::Body },
    ],
    auth: &[
    ],
};

const OP_ENTITIES_GET_ENTITY_BY_ID: OpSpec = OpSpec {
    method: "GET",
    path_template: "/v1/entities/{id}",
    fields: &[
        FieldSpec { snake: "zuora_track_id", wire: "Zuora-Track-Id", location: FieldLocation::Header },
        FieldSpec { snake: "zuora_entity_ids", wire: "Zuora-Entity-Ids", location: FieldLocation::Header },
        FieldSpec { snake: "id", wire: "id", location: FieldLocation::Path },
    ],
    auth: &[
    ],
};

const OP_ENTITIES_PUT_ENTITIES: OpSpec = OpSpec {
    method: "PUT",
    path_template: "/v1/entities/{id}",
    fields: &[
        FieldSpec { snake: "zuora_track_id", wire: "Zuora-Track-Id", location: FieldLocation::Header },
        FieldSpec { snake: "zuora_entity_ids", wire: "Zuora-Entity-Ids", location: FieldLocation::Header },
        FieldSpec { snake: "id", wire: "id", location: FieldLocation::Path },
        FieldSpec { snake: "display_name", wire: "displayName", location: FieldLocation::Body },
        FieldSpec { snake: "locale", wire: "locale", location: FieldLocation::Body },
        FieldSpec { snake: "name", wire: "name", location: FieldLocation::Body },
        FieldSpec { snake: "timezone", wire: "timezone", location: FieldLocation::Body },
    ],
    auth: &[
    ],
};

const OP_ENTITIES_DELETE_ENTITIES: OpSpec = OpSpec {
    method: "DELETE",
    path_template: "/v1/entities/{id}",
    fields: &[
        FieldSpec { snake: "zuora_track_id", wire: "Zuora-Track-Id", location: FieldLocation::Header },
        FieldSpec { snake: "zuora_entity_ids", wire: "Zuora-Entity-Ids", location: FieldLocation::Header },
        FieldSpec { snake: "id", wire: "id", location: FieldLocation::Path },
    ],
    auth: &[
    ],
};

const OP_ENTITIES_PUT_PROVISION_ENTITY: OpSpec = OpSpec {
    method: "PUT",
    path_template: "/v1/entities/{id}/provision",
    fields: &[
        FieldSpec { snake: "zuora_track_id", wire: "Zuora-Track-Id", location: FieldLocation::Header },
        FieldSpec { snake: "zuora_entity_ids", wire: "Zuora-Entity-Ids", location: FieldLocation::Header },
        FieldSpec { snake: "id", wire: "id", location: FieldLocation::Path },
    ],
    auth: &[
    ],
};

fn iface_entities__get_entities_params__to_json(p: &iface_entities::GetEntitiesParams) -> Value {
    let mut m = Map::new();
    m.insert("zuora_track_id".into(), match (&p.zuora_track_id) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("zuora_entity_ids".into(), match (&p.zuora_entity_ids) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("provisioned".into(), match (&p.provisioned) { Some(v) => Value::String((v).clone()), None => Value::Null });
    Value::Object(m)
}

fn iface_entities__post_entities_params__to_json(p: &iface_entities::PostEntitiesParams) -> Value {
    let mut m = Map::new();
    m.insert("zuora_track_id".into(), match (&p.zuora_track_id) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("zuora_entity_ids".into(), match (&p.zuora_entity_ids) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("display_name".into(), match (&p.display_name) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("locale".into(), Value::String((&p.locale).clone()));
    m.insert("name".into(), Value::String((&p.name).clone()));
    m.insert("parent_id".into(), Value::String((&p.parent_id).clone()));
    m.insert("timezone".into(), Value::String((&p.timezone).clone()));
    Value::Object(m)
}

fn iface_entities__get_entity_by_id_params__to_json(p: &iface_entities::GetEntityByIdParams) -> Value {
    let mut m = Map::new();
    m.insert("zuora_track_id".into(), match (&p.zuora_track_id) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("zuora_entity_ids".into(), match (&p.zuora_entity_ids) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("id".into(), Value::String((&p.id).clone()));
    Value::Object(m)
}

fn iface_entities__put_entities_params__to_json(p: &iface_entities::PutEntitiesParams) -> Value {
    let mut m = Map::new();
    m.insert("zuora_track_id".into(), match (&p.zuora_track_id) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("zuora_entity_ids".into(), match (&p.zuora_entity_ids) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("id".into(), Value::String((&p.id).clone()));
    m.insert("display_name".into(), match (&p.display_name) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("locale".into(), match (&p.locale) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("name".into(), match (&p.name) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("timezone".into(), match (&p.timezone) { Some(v) => Value::String((v).clone()), None => Value::Null });
    Value::Object(m)
}

fn iface_entities__delete_entities_params__to_json(p: &iface_entities::DeleteEntitiesParams) -> Value {
    let mut m = Map::new();
    m.insert("zuora_track_id".into(), match (&p.zuora_track_id) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("zuora_entity_ids".into(), match (&p.zuora_entity_ids) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("id".into(), Value::String((&p.id).clone()));
    Value::Object(m)
}

fn iface_entities__put_provision_entity_params__to_json(p: &iface_entities::PutProvisionEntityParams) -> Value {
    let mut m = Map::new();
    m.insert("zuora_track_id".into(), match (&p.zuora_track_id) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("zuora_entity_ids".into(), match (&p.zuora_entity_ids) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("id".into(), Value::String((&p.id).clone()));
    Value::Object(m)
}

fn iface_entities__get_entities__ok(body: String) -> Result<String, crate::runtime::DispatchError> {
    Ok(body)
}

fn iface_entities__get_entities__err(e: crate::runtime::DispatchError) -> String {
    match e {
        crate::runtime::DispatchError::Http { status, body } => format!("HTTP {status}: {body}"),
        crate::runtime::DispatchError::Transport(m) => m,
    }
}

fn iface_entities__post_entities__ok(body: String) -> Result<String, crate::runtime::DispatchError> {
    Ok(body)
}

fn iface_entities__post_entities__err(e: crate::runtime::DispatchError) -> String {
    match e {
        crate::runtime::DispatchError::Http { status, body } => format!("HTTP {status}: {body}"),
        crate::runtime::DispatchError::Transport(m) => m,
    }
}

fn iface_entities__get_entity_by_id__ok(body: String) -> Result<String, crate::runtime::DispatchError> {
    Ok(body)
}

fn iface_entities__get_entity_by_id__err(e: crate::runtime::DispatchError) -> String {
    match e {
        crate::runtime::DispatchError::Http { status, body } => format!("HTTP {status}: {body}"),
        crate::runtime::DispatchError::Transport(m) => m,
    }
}

fn iface_entities__put_entities__ok(body: String) -> Result<String, crate::runtime::DispatchError> {
    Ok(body)
}

fn iface_entities__put_entities__err(e: crate::runtime::DispatchError) -> String {
    match e {
        crate::runtime::DispatchError::Http { status, body } => format!("HTTP {status}: {body}"),
        crate::runtime::DispatchError::Transport(m) => m,
    }
}

fn iface_entities__delete_entities__ok(body: String) -> Result<String, crate::runtime::DispatchError> {
    Ok(body)
}

fn iface_entities__delete_entities__err(e: crate::runtime::DispatchError) -> String {
    match e {
        crate::runtime::DispatchError::Http { status, body } => format!("HTTP {status}: {body}"),
        crate::runtime::DispatchError::Transport(m) => m,
    }
}

fn iface_entities__put_provision_entity__ok(body: String) -> Result<String, crate::runtime::DispatchError> {
    Ok(body)
}

fn iface_entities__put_provision_entity__err(e: crate::runtime::DispatchError) -> String {
    match e {
        crate::runtime::DispatchError::Http { status, body } => format!("HTTP {status}: {body}"),
        crate::runtime::DispatchError::Transport(m) => m,
    }
}

impl iface_entities::Guest for crate::Component {
    fn get_entities(params: iface_entities::GetEntitiesParams) -> Result<String, String> {
        let json = iface_entities__get_entities_params__to_json(&params);
        match dispatch(&OP_ENTITIES_GET_ENTITIES, json).and_then(iface_entities__get_entities__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_entities__get_entities__err(e)),
        }
    }
    fn post_entities(params: iface_entities::PostEntitiesParams) -> Result<String, String> {
        let json = iface_entities__post_entities_params__to_json(&params);
        match dispatch(&OP_ENTITIES_POST_ENTITIES, json).and_then(iface_entities__post_entities__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_entities__post_entities__err(e)),
        }
    }
    fn get_entity_by_id(params: iface_entities::GetEntityByIdParams) -> Result<String, String> {
        let json = iface_entities__get_entity_by_id_params__to_json(&params);
        match dispatch(&OP_ENTITIES_GET_ENTITY_BY_ID, json).and_then(iface_entities__get_entity_by_id__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_entities__get_entity_by_id__err(e)),
        }
    }
    fn put_entities(params: iface_entities::PutEntitiesParams) -> Result<String, String> {
        let json = iface_entities__put_entities_params__to_json(&params);
        match dispatch(&OP_ENTITIES_PUT_ENTITIES, json).and_then(iface_entities__put_entities__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_entities__put_entities__err(e)),
        }
    }
    fn delete_entities(params: iface_entities::DeleteEntitiesParams) -> Result<String, String> {
        let json = iface_entities__delete_entities_params__to_json(&params);
        match dispatch(&OP_ENTITIES_DELETE_ENTITIES, json).and_then(iface_entities__delete_entities__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_entities__delete_entities__err(e)),
        }
    }
    fn put_provision_entity(params: iface_entities::PutProvisionEntityParams) -> Result<String, String> {
        let json = iface_entities__put_provision_entity_params__to_json(&params);
        match dispatch(&OP_ENTITIES_PUT_PROVISION_ENTITY, json).and_then(iface_entities__put_provision_entity__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_entities__put_provision_entity__err(e)),
        }
    }
}
