// AUTOGENERATED by openapi-bindgen. Do not edit by hand.

use crate::runtime::{dispatch, AuthApply, AuthKind, FieldLocation, FieldSpec, OpSpec};
use crate::exports::autostamp::twilio::api20100401_trigger as iface_api20100401_trigger;
use serde_json::{Map, Value};

const OP_API20100401_TRIGGER_LIST_USAGE_TRIGGER: OpSpec = OpSpec {
    method: "GET",
    path_template: "/2010-04-01/Accounts/{account_sid}/Usage/Triggers.json",
    fields: &[
        FieldSpec { snake: "account_sid", wire: "AccountSid", location: FieldLocation::Path },
        FieldSpec { snake: "recurring", wire: "Recurring", location: FieldLocation::Query },
        FieldSpec { snake: "trigger_by", wire: "TriggerBy", location: FieldLocation::Query },
        FieldSpec { snake: "usage_category", wire: "UsageCategory", location: FieldLocation::Query },
        FieldSpec { snake: "page_size", wire: "PageSize", location: FieldLocation::Query },
        FieldSpec { snake: "page", wire: "Page", location: FieldLocation::Query },
        FieldSpec { snake: "page_token", wire: "PageToken", location: FieldLocation::Query },
    ],
    auth: &[
        AuthApply { secret_key: "accountSid_authToken", kind: AuthKind::Basic },
    ],
};

const OP_API20100401_TRIGGER_CREATE_USAGE_TRIGGER: OpSpec = OpSpec {
    method: "POST",
    path_template: "/2010-04-01/Accounts/{account_sid}/Usage/Triggers.json",
    fields: &[
        FieldSpec { snake: "account_sid", wire: "AccountSid", location: FieldLocation::Path },
        FieldSpec { snake: "callback_method", wire: "CallbackMethod", location: FieldLocation::Body },
        FieldSpec { snake: "callback_url", wire: "CallbackUrl", location: FieldLocation::Body },
        FieldSpec { snake: "friendly_name", wire: "FriendlyName", location: FieldLocation::Body },
        FieldSpec { snake: "recurring", wire: "Recurring", location: FieldLocation::Body },
        FieldSpec { snake: "trigger_by", wire: "TriggerBy", location: FieldLocation::Body },
        FieldSpec { snake: "trigger_value", wire: "TriggerValue", location: FieldLocation::Body },
        FieldSpec { snake: "usage_category", wire: "UsageCategory", location: FieldLocation::Body },
    ],
    auth: &[
        AuthApply { secret_key: "accountSid_authToken", kind: AuthKind::Basic },
    ],
};

const OP_API20100401_TRIGGER_FETCH_USAGE_TRIGGER: OpSpec = OpSpec {
    method: "GET",
    path_template: "/2010-04-01/Accounts/{account_sid}/Usage/Triggers/{sid}.json",
    fields: &[
        FieldSpec { snake: "account_sid", wire: "AccountSid", location: FieldLocation::Path },
        FieldSpec { snake: "sid", wire: "Sid", location: FieldLocation::Path },
    ],
    auth: &[
        AuthApply { secret_key: "accountSid_authToken", kind: AuthKind::Basic },
    ],
};

const OP_API20100401_TRIGGER_UPDATE_USAGE_TRIGGER: OpSpec = OpSpec {
    method: "POST",
    path_template: "/2010-04-01/Accounts/{account_sid}/Usage/Triggers/{sid}.json",
    fields: &[
        FieldSpec { snake: "account_sid", wire: "AccountSid", location: FieldLocation::Path },
        FieldSpec { snake: "sid", wire: "Sid", location: FieldLocation::Path },
        FieldSpec { snake: "callback_method", wire: "CallbackMethod", location: FieldLocation::Body },
        FieldSpec { snake: "callback_url", wire: "CallbackUrl", location: FieldLocation::Body },
        FieldSpec { snake: "friendly_name", wire: "FriendlyName", location: FieldLocation::Body },
    ],
    auth: &[
        AuthApply { secret_key: "accountSid_authToken", kind: AuthKind::Basic },
    ],
};

const OP_API20100401_TRIGGER_DELETE_USAGE_TRIGGER: OpSpec = OpSpec {
    method: "DELETE",
    path_template: "/2010-04-01/Accounts/{account_sid}/Usage/Triggers/{sid}.json",
    fields: &[
        FieldSpec { snake: "account_sid", wire: "AccountSid", location: FieldLocation::Path },
        FieldSpec { snake: "sid", wire: "Sid", location: FieldLocation::Path },
    ],
    auth: &[
        AuthApply { secret_key: "accountSid_authToken", kind: AuthKind::Basic },
    ],
};

fn iface_api20100401_trigger__usage_trigger_enum_recurring__to_str(e: &iface_api20100401_trigger::UsageTriggerEnumRecurring) -> &'static str {
    match e {
        iface_api20100401_trigger::UsageTriggerEnumRecurring::Daily => "daily",
        iface_api20100401_trigger::UsageTriggerEnumRecurring::Monthly => "monthly",
        iface_api20100401_trigger::UsageTriggerEnumRecurring::Yearly => "yearly",
        iface_api20100401_trigger::UsageTriggerEnumRecurring::Alltime => "alltime",
    }
}

fn iface_api20100401_trigger__usage_trigger_enum_trigger_field__to_str(e: &iface_api20100401_trigger::UsageTriggerEnumTriggerField) -> &'static str {
    match e {
        iface_api20100401_trigger::UsageTriggerEnumTriggerField::Count => "count",
        iface_api20100401_trigger::UsageTriggerEnumTriggerField::Usage => "usage",
        iface_api20100401_trigger::UsageTriggerEnumTriggerField::Price => "price",
    }
}

fn iface_api20100401_trigger__usage_trigger_enum_usage_category__to_str(e: &iface_api20100401_trigger::UsageTriggerEnumUsageCategory) -> &'static str {
    match e {
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::A2pRegistrationFees => "a2p-registration-fees",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::AgentConference => "agent-conference",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::AmazonPolly => "amazon-polly",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::AnsweringMachineDetection => "answering-machine-detection",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::AuthyAuthentications => "authy-authentications",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::AuthyCallsOutbound => "authy-calls-outbound",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::AuthyMonthlyFees => "authy-monthly-fees",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::AuthyPhoneIntelligence => "authy-phone-intelligence",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::AuthyPhoneVerifications => "authy-phone-verifications",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::AuthySmsOutbound => "authy-sms-outbound",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::CallProgessEvents => "call-progess-events",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::Calleridlookups => "calleridlookups",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::Calls => "calls",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::CallsClient => "calls-client",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::CallsGlobalconference => "calls-globalconference",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::CallsInbound => "calls-inbound",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::CallsInboundLocal => "calls-inbound-local",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::CallsInboundMobile => "calls-inbound-mobile",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::CallsInboundTollfree => "calls-inbound-tollfree",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::CallsOutbound => "calls-outbound",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::CallsPayVerbTransactions => "calls-pay-verb-transactions",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::CallsRecordings => "calls-recordings",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::CallsSip => "calls-sip",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::CallsSipInbound => "calls-sip-inbound",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::CallsSipOutbound => "calls-sip-outbound",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::CallsTransfers => "calls-transfers",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::CarrierLookups => "carrier-lookups",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::Conversations => "conversations",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::ConversationsApiRequests => "conversations-api-requests",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::ConversationsConversationEvents => "conversations-conversation-events",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::ConversationsEndpointConnectivity => "conversations-endpoint-connectivity",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::ConversationsEvents => "conversations-events",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::ConversationsParticipantEvents => "conversations-participant-events",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::ConversationsParticipants => "conversations-participants",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::Cps => "cps",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::FlexUsage => "flex-usage",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::FraudLookups => "fraud-lookups",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::GroupRooms => "group-rooms",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::GroupRoomsDataTrack => "group-rooms-data-track",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::GroupRoomsEncryptedMediaRecorded => "group-rooms-encrypted-media-recorded",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::GroupRoomsMediaDownloaded => "group-rooms-media-downloaded",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::GroupRoomsMediaRecorded => "group-rooms-media-recorded",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::GroupRoomsMediaRouted => "group-rooms-media-routed",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::GroupRoomsMediaStored => "group-rooms-media-stored",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::GroupRoomsParticipantMinutes => "group-rooms-participant-minutes",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::GroupRoomsRecordedMinutes => "group-rooms-recorded-minutes",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::ImpV1Usage => "imp-v1-usage",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::Lookups => "lookups",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::Marketplace => "marketplace",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceAlgorithmiaNamedEntityRecognition => "marketplace-algorithmia-named-entity-recognition",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceCadenceTranscription => "marketplace-cadence-transcription",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceCadenceTranslation => "marketplace-cadence-translation",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceCapioSpeechToText => "marketplace-capio-speech-to-text",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceConvrizaAbaba => "marketplace-convriza-ababa",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceDeepgramPhraseDetector => "marketplace-deepgram-phrase-detector",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceDigitalSegmentBusinessInfo => "marketplace-digital-segment-business-info",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceFacebookOfflineConversions => "marketplace-facebook-offline-conversions",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceGoogleSpeechToText => "marketplace-google-speech-to-text",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceIbmWatsonMessageInsights => "marketplace-ibm-watson-message-insights",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceIbmWatsonMessageSentiment => "marketplace-ibm-watson-message-sentiment",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceIbmWatsonRecordingAnalysis => "marketplace-ibm-watson-recording-analysis",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceIbmWatsonToneAnalyzer => "marketplace-ibm-watson-tone-analyzer",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceIcehookSystemsScout => "marketplace-icehook-systems-scout",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceInfogroupDataaxleBizinfo => "marketplace-infogroup-dataaxle-bizinfo",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceKeenIoContactCenterAnalytics => "marketplace-keen-io-contact-center-analytics",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceMarchexCleancall => "marketplace-marchex-cleancall",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceMarchexSentimentAnalysisForSms => "marketplace-marchex-sentiment-analysis-for-sms",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceMarketplaceNextcallerSocialId => "marketplace-marketplace-nextcaller-social-id",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceMobileCommonsOptOutClassifier => "marketplace-mobile-commons-opt-out-classifier",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceNexiwaveVoicemailToText => "marketplace-nexiwave-voicemail-to-text",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceNextcallerAdvancedCallerIdentification => "marketplace-nextcaller-advanced-caller-identification",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceNomoroboSpamScore => "marketplace-nomorobo-spam-score",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplacePayfoneTcpaCompliance => "marketplace-payfone-tcpa-compliance",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceRemeetingAutomaticSpeechRecognition => "marketplace-remeeting-automatic-speech-recognition",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceTcpaDefenseSolutionsBlacklistFeed => "marketplace-tcpa-defense-solutions-blacklist-feed",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceTeloOpencnam => "marketplace-telo-opencnam",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceTruecnamTrueSpam => "marketplace-truecnam-true-spam",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceTwilioCallerNameLookupUs => "marketplace-twilio-caller-name-lookup-us",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceTwilioCarrierInformationLookup => "marketplace-twilio-carrier-information-lookup",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceVoicebasePci => "marketplace-voicebase-pci",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceVoicebaseTranscription => "marketplace-voicebase-transcription",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceVoicebaseTranscriptionCustomVocabulary => "marketplace-voicebase-transcription-custom-vocabulary",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceWhitepagesProCallerIdentification => "marketplace-whitepages-pro-caller-identification",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceWhitepagesProPhoneIntelligence => "marketplace-whitepages-pro-phone-intelligence",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceWhitepagesProPhoneReputation => "marketplace-whitepages-pro-phone-reputation",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceWolfarmSpokenResults => "marketplace-wolfarm-spoken-results",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceWolframShortAnswer => "marketplace-wolfram-short-answer",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceYticaContactCenterReportingAnalytics => "marketplace-ytica-contact-center-reporting-analytics",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::Mediastorage => "mediastorage",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::Mms => "mms",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MmsInbound => "mms-inbound",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MmsInboundLongcode => "mms-inbound-longcode",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MmsInboundShortcode => "mms-inbound-shortcode",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MmsMessagesCarrierfees => "mms-messages-carrierfees",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MmsOutbound => "mms-outbound",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MmsOutboundLongcode => "mms-outbound-longcode",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MmsOutboundShortcode => "mms-outbound-shortcode",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MonitorReads => "monitor-reads",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MonitorStorage => "monitor-storage",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MonitorWrites => "monitor-writes",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::Notify => "notify",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::NotifyActionsAttempts => "notify-actions-attempts",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::NotifyChannels => "notify-channels",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::NumberFormatLookups => "number-format-lookups",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::Pchat => "pchat",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::PchatUsers => "pchat-users",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::PeerToPeerRoomsParticipantMinutes => "peer-to-peer-rooms-participant-minutes",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::Pfax => "pfax",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::PfaxMinutes => "pfax-minutes",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::PfaxMinutesInbound => "pfax-minutes-inbound",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::PfaxMinutesOutbound => "pfax-minutes-outbound",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::PfaxPages => "pfax-pages",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::Phonenumbers => "phonenumbers",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::PhonenumbersCps => "phonenumbers-cps",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::PhonenumbersEmergency => "phonenumbers-emergency",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::PhonenumbersLocal => "phonenumbers-local",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::PhonenumbersMobile => "phonenumbers-mobile",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::PhonenumbersSetups => "phonenumbers-setups",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::PhonenumbersTollfree => "phonenumbers-tollfree",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::Premiumsupport => "premiumsupport",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::Proxy => "proxy",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::ProxyActiveSessions => "proxy-active-sessions",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::Pstnconnectivity => "pstnconnectivity",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::Pv => "pv",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::PvCompositionMediaDownloaded => "pv-composition-media-downloaded",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::PvCompositionMediaEncrypted => "pv-composition-media-encrypted",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::PvCompositionMediaStored => "pv-composition-media-stored",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::PvCompositionMinutes => "pv-composition-minutes",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::PvRecordingCompositions => "pv-recording-compositions",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::PvRoomParticipants => "pv-room-participants",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::PvRoomParticipantsAu1 => "pv-room-participants-au1",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::PvRoomParticipantsBr1 => "pv-room-participants-br1",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::PvRoomParticipantsIe1 => "pv-room-participants-ie1",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::PvRoomParticipantsJp1 => "pv-room-participants-jp1",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::PvRoomParticipantsSg1 => "pv-room-participants-sg1",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::PvRoomParticipantsUs1 => "pv-room-participants-us1",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::PvRoomParticipantsUs2 => "pv-room-participants-us2",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::PvRooms => "pv-rooms",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::PvSipEndpointRegistrations => "pv-sip-endpoint-registrations",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::Recordings => "recordings",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::Recordingstorage => "recordingstorage",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::RoomsGroupBandwidth => "rooms-group-bandwidth",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::RoomsGroupMinutes => "rooms-group-minutes",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::RoomsPeerToPeerMinutes => "rooms-peer-to-peer-minutes",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::Shortcodes => "shortcodes",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::ShortcodesCustomerowned => "shortcodes-customerowned",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::ShortcodesMmsEnablement => "shortcodes-mms-enablement",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::ShortcodesMps => "shortcodes-mps",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::ShortcodesRandom => "shortcodes-random",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::ShortcodesUk => "shortcodes-uk",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::ShortcodesVanity => "shortcodes-vanity",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::SmallGroupRooms => "small-group-rooms",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::SmallGroupRoomsDataTrack => "small-group-rooms-data-track",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::SmallGroupRoomsParticipantMinutes => "small-group-rooms-participant-minutes",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::Sms => "sms",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::SmsInbound => "sms-inbound",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::SmsInboundLongcode => "sms-inbound-longcode",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::SmsInboundShortcode => "sms-inbound-shortcode",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::SmsMessagesCarrierfees => "sms-messages-carrierfees",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::SmsMessagesFeatures => "sms-messages-features",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::SmsMessagesFeaturesSenderid => "sms-messages-features-senderid",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::SmsOutbound => "sms-outbound",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::SmsOutboundContentInspection => "sms-outbound-content-inspection",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::SmsOutboundLongcode => "sms-outbound-longcode",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::SmsOutboundShortcode => "sms-outbound-shortcode",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::SpeechRecognition => "speech-recognition",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::StudioEngagements => "studio-engagements",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::Sync => "sync",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::SyncActions => "sync-actions",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::SyncEndpointHours => "sync-endpoint-hours",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::SyncEndpointHoursAboveDailyCap => "sync-endpoint-hours-above-daily-cap",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::TaskrouterTasks => "taskrouter-tasks",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::Totalprice => "totalprice",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::Transcriptions => "transcriptions",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::TrunkingCps => "trunking-cps",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::TrunkingEmergencyCalls => "trunking-emergency-calls",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::TrunkingOrigination => "trunking-origination",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::TrunkingOriginationLocal => "trunking-origination-local",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::TrunkingOriginationMobile => "trunking-origination-mobile",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::TrunkingOriginationTollfree => "trunking-origination-tollfree",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::TrunkingRecordings => "trunking-recordings",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::TrunkingSecure => "trunking-secure",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::TrunkingTermination => "trunking-termination",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::TtsGoogle => "tts-google",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::Turnmegabytes => "turnmegabytes",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::TurnmegabytesAustralia => "turnmegabytes-australia",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::TurnmegabytesBrasil => "turnmegabytes-brasil",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::TurnmegabytesGermany => "turnmegabytes-germany",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::TurnmegabytesIndia => "turnmegabytes-india",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::TurnmegabytesIreland => "turnmegabytes-ireland",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::TurnmegabytesJapan => "turnmegabytes-japan",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::TurnmegabytesSingapore => "turnmegabytes-singapore",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::TurnmegabytesUseast => "turnmegabytes-useast",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::TurnmegabytesUswest => "turnmegabytes-uswest",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::TwilioInterconnect => "twilio-interconnect",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::VerifyPush => "verify-push",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::VerifyTotp => "verify-totp",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::VerifyWhatsappConversationsBusinessInitiated => "verify-whatsapp-conversations-business-initiated",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::VideoRecordings => "video-recordings",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::VirtualAgent => "virtual-agent",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::VoiceInsights => "voice-insights",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::VoiceInsightsClientInsightsOnDemandMinute => "voice-insights-client-insights-on-demand-minute",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::VoiceInsightsPtsnInsightsOnDemandMinute => "voice-insights-ptsn-insights-on-demand-minute",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::VoiceInsightsSipInterfaceInsightsOnDemandMinute => "voice-insights-sip-interface-insights-on-demand-minute",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::VoiceInsightsSipTrunkingInsightsOnDemandMinute => "voice-insights-sip-trunking-insights-on-demand-minute",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::VoiceIntelligence => "voice-intelligence",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::VoiceIntelligenceTranscription => "voice-intelligence-transcription",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::VoiceIntelligenceOperators => "voice-intelligence-operators",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::Wireless => "wireless",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessOrders => "wireless-orders",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessOrdersArtwork => "wireless-orders-artwork",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessOrdersBulk => "wireless-orders-bulk",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessOrdersEsim => "wireless-orders-esim",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessOrdersStarter => "wireless-orders-starter",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsage => "wireless-usage",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageCommands => "wireless-usage-commands",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageCommandsAfrica => "wireless-usage-commands-africa",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageCommandsAsia => "wireless-usage-commands-asia",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageCommandsCentralandsouthamerica => "wireless-usage-commands-centralandsouthamerica",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageCommandsEurope => "wireless-usage-commands-europe",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageCommandsHome => "wireless-usage-commands-home",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageCommandsNorthamerica => "wireless-usage-commands-northamerica",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageCommandsOceania => "wireless-usage-commands-oceania",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageCommandsRoaming => "wireless-usage-commands-roaming",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageData => "wireless-usage-data",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageDataAfrica => "wireless-usage-data-africa",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageDataAsia => "wireless-usage-data-asia",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageDataCentralandsouthamerica => "wireless-usage-data-centralandsouthamerica",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageDataCustomAdditionalmb => "wireless-usage-data-custom-additionalmb",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageDataCustomFirst5mb => "wireless-usage-data-custom-first5mb",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageDataDomesticRoaming => "wireless-usage-data-domestic-roaming",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageDataEurope => "wireless-usage-data-europe",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageDataIndividualAdditionalgb => "wireless-usage-data-individual-additionalgb",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageDataIndividualFirstgb => "wireless-usage-data-individual-firstgb",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageDataInternationalRoamingCanada => "wireless-usage-data-international-roaming-canada",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageDataInternationalRoamingIndia => "wireless-usage-data-international-roaming-india",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageDataInternationalRoamingMexico => "wireless-usage-data-international-roaming-mexico",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageDataNorthamerica => "wireless-usage-data-northamerica",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageDataOceania => "wireless-usage-data-oceania",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageDataPooled => "wireless-usage-data-pooled",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageDataPooledDownlink => "wireless-usage-data-pooled-downlink",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageDataPooledUplink => "wireless-usage-data-pooled-uplink",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageMrc => "wireless-usage-mrc",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageMrcCustom => "wireless-usage-mrc-custom",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageMrcIndividual => "wireless-usage-mrc-individual",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageMrcPooled => "wireless-usage-mrc-pooled",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageMrcSuspended => "wireless-usage-mrc-suspended",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageSms => "wireless-usage-sms",
        iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageVoice => "wireless-usage-voice",
    }
}

fn iface_api20100401_trigger__api_v2010_account_usage_usage_trigger_callback_method_enum__to_str(e: &iface_api20100401_trigger::ApiV2010AccountUsageUsageTriggerCallbackMethodEnum) -> &'static str {
    match e {
        iface_api20100401_trigger::ApiV2010AccountUsageUsageTriggerCallbackMethodEnum::Head => "HEAD",
        iface_api20100401_trigger::ApiV2010AccountUsageUsageTriggerCallbackMethodEnum::Get => "GET",
        iface_api20100401_trigger::ApiV2010AccountUsageUsageTriggerCallbackMethodEnum::Post => "POST",
        iface_api20100401_trigger::ApiV2010AccountUsageUsageTriggerCallbackMethodEnum::Patch => "PATCH",
        iface_api20100401_trigger::ApiV2010AccountUsageUsageTriggerCallbackMethodEnum::Put => "PUT",
        iface_api20100401_trigger::ApiV2010AccountUsageUsageTriggerCallbackMethodEnum::Delete => "DELETE",
    }
}

fn iface_api20100401_trigger__list_usage_trigger_response__to_json(p: &iface_api20100401_trigger::ListUsageTriggerResponse) -> Value {
    let mut m = Map::new();
    m.insert("end".into(), match (&p.end) { Some(v) => Value::Number(serde_json::Number::from(*(v))), None => Value::Null });
    m.insert("first_page_uri".into(), match (&p.first_page_uri) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("next_page_uri".into(), match (&p.next_page_uri) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("page".into(), match (&p.page) { Some(v) => Value::Number(serde_json::Number::from(*(v))), None => Value::Null });
    m.insert("page_size".into(), match (&p.page_size) { Some(v) => Value::Number(serde_json::Number::from(*(v))), None => Value::Null });
    m.insert("previous_page_uri".into(), match (&p.previous_page_uri) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("start".into(), match (&p.start) { Some(v) => Value::Number(serde_json::Number::from(*(v))), None => Value::Null });
    m.insert("uri".into(), match (&p.uri) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("usage_triggers".into(), match (&p.usage_triggers) { Some(v) => Value::Array((v).iter().map(|v| iface_api20100401_trigger__api_v2010_account_usage_usage_trigger__to_json(v)).collect()), None => Value::Null });
    Value::Object(m)
}

fn iface_api20100401_trigger__api_v2010_account_usage_usage_trigger__to_json(p: &iface_api20100401_trigger::ApiV2010AccountUsageUsageTrigger) -> Value {
    let mut m = Map::new();
    m.insert("account_sid".into(), match (&p.account_sid) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("api_version".into(), match (&p.api_version) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("callback_method".into(), match (&p.callback_method) { Some(v) => Value::String(iface_api20100401_trigger__api_v2010_account_usage_usage_trigger_callback_method_enum__to_str(v).into()), None => Value::Null });
    m.insert("callback_url".into(), match (&p.callback_url) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("current_value".into(), match (&p.current_value) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("date_created".into(), match (&p.date_created) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("date_fired".into(), match (&p.date_fired) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("date_updated".into(), match (&p.date_updated) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("friendly_name".into(), match (&p.friendly_name) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("recurring".into(), match (&p.recurring) { Some(v) => Value::String(iface_api20100401_trigger__usage_trigger_enum_recurring__to_str(v).into()), None => Value::Null });
    m.insert("sid".into(), match (&p.sid) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("trigger_by".into(), match (&p.trigger_by) { Some(v) => Value::String(iface_api20100401_trigger__usage_trigger_enum_trigger_field__to_str(v).into()), None => Value::Null });
    m.insert("trigger_value".into(), match (&p.trigger_value) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("uri".into(), match (&p.uri) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("usage_category".into(), match (&p.usage_category) { Some(v) => Value::String(iface_api20100401_trigger__usage_trigger_enum_usage_category__to_str(v).into()), None => Value::Null });
    m.insert("usage_record_uri".into(), match (&p.usage_record_uri) { Some(v) => Value::String((v).clone()), None => Value::Null });
    Value::Object(m)
}

fn iface_api20100401_trigger__list_usage_trigger_params__to_json(p: &iface_api20100401_trigger::ListUsageTriggerParams) -> Value {
    let mut m = Map::new();
    m.insert("account_sid".into(), Value::String((&p.account_sid).clone()));
    m.insert("recurring".into(), match (&p.recurring) { Some(v) => Value::String(iface_api20100401_trigger__usage_trigger_enum_recurring__to_str(v).into()), None => Value::Null });
    m.insert("trigger_by".into(), match (&p.trigger_by) { Some(v) => Value::String(iface_api20100401_trigger__usage_trigger_enum_trigger_field__to_str(v).into()), None => Value::Null });
    m.insert("usage_category".into(), match (&p.usage_category) { Some(v) => Value::String(iface_api20100401_trigger__usage_trigger_enum_usage_category__to_str(v).into()), None => Value::Null });
    m.insert("page_size".into(), match (&p.page_size) { Some(v) => Value::Number(serde_json::Number::from(*(v))), None => Value::Null });
    m.insert("page".into(), match (&p.page) { Some(v) => Value::Number(serde_json::Number::from(*(v))), None => Value::Null });
    m.insert("page_token".into(), match (&p.page_token) { Some(v) => Value::String((v).clone()), None => Value::Null });
    Value::Object(m)
}

fn iface_api20100401_trigger__create_usage_trigger_params__to_json(p: &iface_api20100401_trigger::CreateUsageTriggerParams) -> Value {
    let mut m = Map::new();
    m.insert("account_sid".into(), Value::String((&p.account_sid).clone()));
    m.insert("callback_method".into(), match (&p.callback_method) { Some(v) => Value::String(iface_api20100401_trigger__api_v2010_account_usage_usage_trigger_callback_method_enum__to_str(v).into()), None => Value::Null });
    m.insert("callback_url".into(), Value::String((&p.callback_url).clone()));
    m.insert("friendly_name".into(), match (&p.friendly_name) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("recurring".into(), match (&p.recurring) { Some(v) => Value::String(iface_api20100401_trigger__usage_trigger_enum_recurring__to_str(v).into()), None => Value::Null });
    m.insert("trigger_by".into(), match (&p.trigger_by) { Some(v) => Value::String(iface_api20100401_trigger__usage_trigger_enum_trigger_field__to_str(v).into()), None => Value::Null });
    m.insert("trigger_value".into(), Value::String((&p.trigger_value).clone()));
    m.insert("usage_category".into(), Value::String(iface_api20100401_trigger__usage_trigger_enum_usage_category__to_str(&p.usage_category).into()));
    Value::Object(m)
}

fn iface_api20100401_trigger__fetch_usage_trigger_params__to_json(p: &iface_api20100401_trigger::FetchUsageTriggerParams) -> Value {
    let mut m = Map::new();
    m.insert("account_sid".into(), Value::String((&p.account_sid).clone()));
    m.insert("sid".into(), Value::String((&p.sid).clone()));
    Value::Object(m)
}

fn iface_api20100401_trigger__update_usage_trigger_params__to_json(p: &iface_api20100401_trigger::UpdateUsageTriggerParams) -> Value {
    let mut m = Map::new();
    m.insert("account_sid".into(), Value::String((&p.account_sid).clone()));
    m.insert("sid".into(), Value::String((&p.sid).clone()));
    m.insert("callback_method".into(), match (&p.callback_method) { Some(v) => Value::String(iface_api20100401_trigger__api_v2010_account_usage_usage_trigger_callback_method_enum__to_str(v).into()), None => Value::Null });
    m.insert("callback_url".into(), match (&p.callback_url) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("friendly_name".into(), match (&p.friendly_name) { Some(v) => Value::String((v).clone()), None => Value::Null });
    Value::Object(m)
}

fn iface_api20100401_trigger__delete_usage_trigger_params__to_json(p: &iface_api20100401_trigger::DeleteUsageTriggerParams) -> Value {
    let mut m = Map::new();
    m.insert("account_sid".into(), Value::String((&p.account_sid).clone()));
    m.insert("sid".into(), Value::String((&p.sid).clone()));
    Value::Object(m)
}

fn iface_api20100401_trigger__list_usage_trigger_response__from_json(v: &Value) -> Option<iface_api20100401_trigger::ListUsageTriggerResponse> {
    let m = v.as_object()?;
    Some(iface_api20100401_trigger::ListUsageTriggerResponse {
        end: m.get("end").filter(|v| !v.is_null()).and_then(|v| (v).as_i64().map(|n| n as i32)),
        first_page_uri: m.get("first_page_uri").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        next_page_uri: m.get("next_page_uri").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        page: m.get("page").filter(|v| !v.is_null()).and_then(|v| (v).as_i64().map(|n| n as i32)),
        page_size: m.get("page_size").filter(|v| !v.is_null()).and_then(|v| (v).as_i64().map(|n| n as i32)),
        previous_page_uri: m.get("previous_page_uri").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        start: m.get("start").filter(|v| !v.is_null()).and_then(|v| (v).as_i64().map(|n| n as i32)),
        uri: m.get("uri").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        usage_triggers: m.get("usage_triggers").filter(|v| !v.is_null()).and_then(|v| (v).as_array().map(|a| a.iter().filter_map(|x| iface_api20100401_trigger__api_v2010_account_usage_usage_trigger__from_json(x)).collect())),
    })
}

fn iface_api20100401_trigger__api_v2010_account_usage_usage_trigger__from_json(v: &Value) -> Option<iface_api20100401_trigger::ApiV2010AccountUsageUsageTrigger> {
    let m = v.as_object()?;
    Some(iface_api20100401_trigger::ApiV2010AccountUsageUsageTrigger {
        account_sid: m.get("account_sid").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        api_version: m.get("api_version").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        callback_method: m.get("callback_method").filter(|v| !v.is_null()).and_then(|v| (v).as_str().and_then(iface_api20100401_trigger__api_v2010_account_usage_usage_trigger_callback_method_enum__from_str)),
        callback_url: m.get("callback_url").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        current_value: m.get("current_value").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        date_created: m.get("date_created").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        date_fired: m.get("date_fired").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        date_updated: m.get("date_updated").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        friendly_name: m.get("friendly_name").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        recurring: m.get("recurring").filter(|v| !v.is_null()).and_then(|v| (v).as_str().and_then(iface_api20100401_trigger__usage_trigger_enum_recurring__from_str)),
        sid: m.get("sid").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        trigger_by: m.get("trigger_by").filter(|v| !v.is_null()).and_then(|v| (v).as_str().and_then(iface_api20100401_trigger__usage_trigger_enum_trigger_field__from_str)),
        trigger_value: m.get("trigger_value").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        uri: m.get("uri").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        usage_category: m.get("usage_category").filter(|v| !v.is_null()).and_then(|v| (v).as_str().and_then(iface_api20100401_trigger__usage_trigger_enum_usage_category__from_str)),
        usage_record_uri: m.get("usage_record_uri").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
    })
}

fn iface_api20100401_trigger__usage_trigger_enum_recurring__from_str(s: &str) -> Option<iface_api20100401_trigger::UsageTriggerEnumRecurring> {
    match s {
        "daily" => Some(iface_api20100401_trigger::UsageTriggerEnumRecurring::Daily),
        "monthly" => Some(iface_api20100401_trigger::UsageTriggerEnumRecurring::Monthly),
        "yearly" => Some(iface_api20100401_trigger::UsageTriggerEnumRecurring::Yearly),
        "alltime" => Some(iface_api20100401_trigger::UsageTriggerEnumRecurring::Alltime),
        _ => None,
    }
}

fn iface_api20100401_trigger__usage_trigger_enum_trigger_field__from_str(s: &str) -> Option<iface_api20100401_trigger::UsageTriggerEnumTriggerField> {
    match s {
        "count" => Some(iface_api20100401_trigger::UsageTriggerEnumTriggerField::Count),
        "usage" => Some(iface_api20100401_trigger::UsageTriggerEnumTriggerField::Usage),
        "price" => Some(iface_api20100401_trigger::UsageTriggerEnumTriggerField::Price),
        _ => None,
    }
}

fn iface_api20100401_trigger__usage_trigger_enum_usage_category__from_str(s: &str) -> Option<iface_api20100401_trigger::UsageTriggerEnumUsageCategory> {
    match s {
        "a2p-registration-fees" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::A2pRegistrationFees),
        "agent-conference" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::AgentConference),
        "amazon-polly" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::AmazonPolly),
        "answering-machine-detection" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::AnsweringMachineDetection),
        "authy-authentications" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::AuthyAuthentications),
        "authy-calls-outbound" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::AuthyCallsOutbound),
        "authy-monthly-fees" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::AuthyMonthlyFees),
        "authy-phone-intelligence" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::AuthyPhoneIntelligence),
        "authy-phone-verifications" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::AuthyPhoneVerifications),
        "authy-sms-outbound" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::AuthySmsOutbound),
        "call-progess-events" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::CallProgessEvents),
        "calleridlookups" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::Calleridlookups),
        "calls" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::Calls),
        "calls-client" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::CallsClient),
        "calls-globalconference" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::CallsGlobalconference),
        "calls-inbound" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::CallsInbound),
        "calls-inbound-local" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::CallsInboundLocal),
        "calls-inbound-mobile" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::CallsInboundMobile),
        "calls-inbound-tollfree" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::CallsInboundTollfree),
        "calls-outbound" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::CallsOutbound),
        "calls-pay-verb-transactions" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::CallsPayVerbTransactions),
        "calls-recordings" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::CallsRecordings),
        "calls-sip" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::CallsSip),
        "calls-sip-inbound" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::CallsSipInbound),
        "calls-sip-outbound" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::CallsSipOutbound),
        "calls-transfers" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::CallsTransfers),
        "carrier-lookups" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::CarrierLookups),
        "conversations" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::Conversations),
        "conversations-api-requests" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::ConversationsApiRequests),
        "conversations-conversation-events" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::ConversationsConversationEvents),
        "conversations-endpoint-connectivity" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::ConversationsEndpointConnectivity),
        "conversations-events" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::ConversationsEvents),
        "conversations-participant-events" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::ConversationsParticipantEvents),
        "conversations-participants" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::ConversationsParticipants),
        "cps" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::Cps),
        "flex-usage" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::FlexUsage),
        "fraud-lookups" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::FraudLookups),
        "group-rooms" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::GroupRooms),
        "group-rooms-data-track" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::GroupRoomsDataTrack),
        "group-rooms-encrypted-media-recorded" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::GroupRoomsEncryptedMediaRecorded),
        "group-rooms-media-downloaded" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::GroupRoomsMediaDownloaded),
        "group-rooms-media-recorded" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::GroupRoomsMediaRecorded),
        "group-rooms-media-routed" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::GroupRoomsMediaRouted),
        "group-rooms-media-stored" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::GroupRoomsMediaStored),
        "group-rooms-participant-minutes" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::GroupRoomsParticipantMinutes),
        "group-rooms-recorded-minutes" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::GroupRoomsRecordedMinutes),
        "imp-v1-usage" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::ImpV1Usage),
        "lookups" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::Lookups),
        "marketplace" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::Marketplace),
        "marketplace-algorithmia-named-entity-recognition" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceAlgorithmiaNamedEntityRecognition),
        "marketplace-cadence-transcription" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceCadenceTranscription),
        "marketplace-cadence-translation" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceCadenceTranslation),
        "marketplace-capio-speech-to-text" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceCapioSpeechToText),
        "marketplace-convriza-ababa" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceConvrizaAbaba),
        "marketplace-deepgram-phrase-detector" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceDeepgramPhraseDetector),
        "marketplace-digital-segment-business-info" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceDigitalSegmentBusinessInfo),
        "marketplace-facebook-offline-conversions" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceFacebookOfflineConversions),
        "marketplace-google-speech-to-text" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceGoogleSpeechToText),
        "marketplace-ibm-watson-message-insights" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceIbmWatsonMessageInsights),
        "marketplace-ibm-watson-message-sentiment" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceIbmWatsonMessageSentiment),
        "marketplace-ibm-watson-recording-analysis" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceIbmWatsonRecordingAnalysis),
        "marketplace-ibm-watson-tone-analyzer" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceIbmWatsonToneAnalyzer),
        "marketplace-icehook-systems-scout" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceIcehookSystemsScout),
        "marketplace-infogroup-dataaxle-bizinfo" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceInfogroupDataaxleBizinfo),
        "marketplace-keen-io-contact-center-analytics" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceKeenIoContactCenterAnalytics),
        "marketplace-marchex-cleancall" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceMarchexCleancall),
        "marketplace-marchex-sentiment-analysis-for-sms" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceMarchexSentimentAnalysisForSms),
        "marketplace-marketplace-nextcaller-social-id" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceMarketplaceNextcallerSocialId),
        "marketplace-mobile-commons-opt-out-classifier" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceMobileCommonsOptOutClassifier),
        "marketplace-nexiwave-voicemail-to-text" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceNexiwaveVoicemailToText),
        "marketplace-nextcaller-advanced-caller-identification" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceNextcallerAdvancedCallerIdentification),
        "marketplace-nomorobo-spam-score" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceNomoroboSpamScore),
        "marketplace-payfone-tcpa-compliance" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplacePayfoneTcpaCompliance),
        "marketplace-remeeting-automatic-speech-recognition" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceRemeetingAutomaticSpeechRecognition),
        "marketplace-tcpa-defense-solutions-blacklist-feed" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceTcpaDefenseSolutionsBlacklistFeed),
        "marketplace-telo-opencnam" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceTeloOpencnam),
        "marketplace-truecnam-true-spam" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceTruecnamTrueSpam),
        "marketplace-twilio-caller-name-lookup-us" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceTwilioCallerNameLookupUs),
        "marketplace-twilio-carrier-information-lookup" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceTwilioCarrierInformationLookup),
        "marketplace-voicebase-pci" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceVoicebasePci),
        "marketplace-voicebase-transcription" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceVoicebaseTranscription),
        "marketplace-voicebase-transcription-custom-vocabulary" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceVoicebaseTranscriptionCustomVocabulary),
        "marketplace-whitepages-pro-caller-identification" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceWhitepagesProCallerIdentification),
        "marketplace-whitepages-pro-phone-intelligence" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceWhitepagesProPhoneIntelligence),
        "marketplace-whitepages-pro-phone-reputation" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceWhitepagesProPhoneReputation),
        "marketplace-wolfarm-spoken-results" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceWolfarmSpokenResults),
        "marketplace-wolfram-short-answer" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceWolframShortAnswer),
        "marketplace-ytica-contact-center-reporting-analytics" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MarketplaceYticaContactCenterReportingAnalytics),
        "mediastorage" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::Mediastorage),
        "mms" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::Mms),
        "mms-inbound" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MmsInbound),
        "mms-inbound-longcode" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MmsInboundLongcode),
        "mms-inbound-shortcode" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MmsInboundShortcode),
        "mms-messages-carrierfees" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MmsMessagesCarrierfees),
        "mms-outbound" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MmsOutbound),
        "mms-outbound-longcode" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MmsOutboundLongcode),
        "mms-outbound-shortcode" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MmsOutboundShortcode),
        "monitor-reads" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MonitorReads),
        "monitor-storage" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MonitorStorage),
        "monitor-writes" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::MonitorWrites),
        "notify" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::Notify),
        "notify-actions-attempts" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::NotifyActionsAttempts),
        "notify-channels" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::NotifyChannels),
        "number-format-lookups" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::NumberFormatLookups),
        "pchat" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::Pchat),
        "pchat-users" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::PchatUsers),
        "peer-to-peer-rooms-participant-minutes" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::PeerToPeerRoomsParticipantMinutes),
        "pfax" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::Pfax),
        "pfax-minutes" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::PfaxMinutes),
        "pfax-minutes-inbound" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::PfaxMinutesInbound),
        "pfax-minutes-outbound" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::PfaxMinutesOutbound),
        "pfax-pages" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::PfaxPages),
        "phonenumbers" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::Phonenumbers),
        "phonenumbers-cps" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::PhonenumbersCps),
        "phonenumbers-emergency" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::PhonenumbersEmergency),
        "phonenumbers-local" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::PhonenumbersLocal),
        "phonenumbers-mobile" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::PhonenumbersMobile),
        "phonenumbers-setups" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::PhonenumbersSetups),
        "phonenumbers-tollfree" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::PhonenumbersTollfree),
        "premiumsupport" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::Premiumsupport),
        "proxy" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::Proxy),
        "proxy-active-sessions" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::ProxyActiveSessions),
        "pstnconnectivity" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::Pstnconnectivity),
        "pv" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::Pv),
        "pv-composition-media-downloaded" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::PvCompositionMediaDownloaded),
        "pv-composition-media-encrypted" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::PvCompositionMediaEncrypted),
        "pv-composition-media-stored" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::PvCompositionMediaStored),
        "pv-composition-minutes" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::PvCompositionMinutes),
        "pv-recording-compositions" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::PvRecordingCompositions),
        "pv-room-participants" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::PvRoomParticipants),
        "pv-room-participants-au1" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::PvRoomParticipantsAu1),
        "pv-room-participants-br1" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::PvRoomParticipantsBr1),
        "pv-room-participants-ie1" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::PvRoomParticipantsIe1),
        "pv-room-participants-jp1" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::PvRoomParticipantsJp1),
        "pv-room-participants-sg1" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::PvRoomParticipantsSg1),
        "pv-room-participants-us1" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::PvRoomParticipantsUs1),
        "pv-room-participants-us2" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::PvRoomParticipantsUs2),
        "pv-rooms" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::PvRooms),
        "pv-sip-endpoint-registrations" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::PvSipEndpointRegistrations),
        "recordings" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::Recordings),
        "recordingstorage" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::Recordingstorage),
        "rooms-group-bandwidth" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::RoomsGroupBandwidth),
        "rooms-group-minutes" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::RoomsGroupMinutes),
        "rooms-peer-to-peer-minutes" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::RoomsPeerToPeerMinutes),
        "shortcodes" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::Shortcodes),
        "shortcodes-customerowned" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::ShortcodesCustomerowned),
        "shortcodes-mms-enablement" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::ShortcodesMmsEnablement),
        "shortcodes-mps" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::ShortcodesMps),
        "shortcodes-random" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::ShortcodesRandom),
        "shortcodes-uk" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::ShortcodesUk),
        "shortcodes-vanity" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::ShortcodesVanity),
        "small-group-rooms" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::SmallGroupRooms),
        "small-group-rooms-data-track" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::SmallGroupRoomsDataTrack),
        "small-group-rooms-participant-minutes" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::SmallGroupRoomsParticipantMinutes),
        "sms" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::Sms),
        "sms-inbound" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::SmsInbound),
        "sms-inbound-longcode" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::SmsInboundLongcode),
        "sms-inbound-shortcode" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::SmsInboundShortcode),
        "sms-messages-carrierfees" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::SmsMessagesCarrierfees),
        "sms-messages-features" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::SmsMessagesFeatures),
        "sms-messages-features-senderid" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::SmsMessagesFeaturesSenderid),
        "sms-outbound" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::SmsOutbound),
        "sms-outbound-content-inspection" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::SmsOutboundContentInspection),
        "sms-outbound-longcode" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::SmsOutboundLongcode),
        "sms-outbound-shortcode" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::SmsOutboundShortcode),
        "speech-recognition" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::SpeechRecognition),
        "studio-engagements" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::StudioEngagements),
        "sync" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::Sync),
        "sync-actions" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::SyncActions),
        "sync-endpoint-hours" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::SyncEndpointHours),
        "sync-endpoint-hours-above-daily-cap" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::SyncEndpointHoursAboveDailyCap),
        "taskrouter-tasks" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::TaskrouterTasks),
        "totalprice" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::Totalprice),
        "transcriptions" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::Transcriptions),
        "trunking-cps" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::TrunkingCps),
        "trunking-emergency-calls" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::TrunkingEmergencyCalls),
        "trunking-origination" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::TrunkingOrigination),
        "trunking-origination-local" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::TrunkingOriginationLocal),
        "trunking-origination-mobile" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::TrunkingOriginationMobile),
        "trunking-origination-tollfree" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::TrunkingOriginationTollfree),
        "trunking-recordings" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::TrunkingRecordings),
        "trunking-secure" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::TrunkingSecure),
        "trunking-termination" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::TrunkingTermination),
        "tts-google" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::TtsGoogle),
        "turnmegabytes" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::Turnmegabytes),
        "turnmegabytes-australia" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::TurnmegabytesAustralia),
        "turnmegabytes-brasil" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::TurnmegabytesBrasil),
        "turnmegabytes-germany" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::TurnmegabytesGermany),
        "turnmegabytes-india" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::TurnmegabytesIndia),
        "turnmegabytes-ireland" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::TurnmegabytesIreland),
        "turnmegabytes-japan" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::TurnmegabytesJapan),
        "turnmegabytes-singapore" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::TurnmegabytesSingapore),
        "turnmegabytes-useast" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::TurnmegabytesUseast),
        "turnmegabytes-uswest" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::TurnmegabytesUswest),
        "twilio-interconnect" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::TwilioInterconnect),
        "verify-push" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::VerifyPush),
        "verify-totp" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::VerifyTotp),
        "verify-whatsapp-conversations-business-initiated" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::VerifyWhatsappConversationsBusinessInitiated),
        "video-recordings" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::VideoRecordings),
        "virtual-agent" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::VirtualAgent),
        "voice-insights" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::VoiceInsights),
        "voice-insights-client-insights-on-demand-minute" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::VoiceInsightsClientInsightsOnDemandMinute),
        "voice-insights-ptsn-insights-on-demand-minute" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::VoiceInsightsPtsnInsightsOnDemandMinute),
        "voice-insights-sip-interface-insights-on-demand-minute" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::VoiceInsightsSipInterfaceInsightsOnDemandMinute),
        "voice-insights-sip-trunking-insights-on-demand-minute" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::VoiceInsightsSipTrunkingInsightsOnDemandMinute),
        "voice-intelligence" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::VoiceIntelligence),
        "voice-intelligence-transcription" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::VoiceIntelligenceTranscription),
        "voice-intelligence-operators" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::VoiceIntelligenceOperators),
        "wireless" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::Wireless),
        "wireless-orders" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessOrders),
        "wireless-orders-artwork" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessOrdersArtwork),
        "wireless-orders-bulk" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessOrdersBulk),
        "wireless-orders-esim" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessOrdersEsim),
        "wireless-orders-starter" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessOrdersStarter),
        "wireless-usage" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsage),
        "wireless-usage-commands" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageCommands),
        "wireless-usage-commands-africa" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageCommandsAfrica),
        "wireless-usage-commands-asia" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageCommandsAsia),
        "wireless-usage-commands-centralandsouthamerica" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageCommandsCentralandsouthamerica),
        "wireless-usage-commands-europe" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageCommandsEurope),
        "wireless-usage-commands-home" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageCommandsHome),
        "wireless-usage-commands-northamerica" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageCommandsNorthamerica),
        "wireless-usage-commands-oceania" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageCommandsOceania),
        "wireless-usage-commands-roaming" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageCommandsRoaming),
        "wireless-usage-data" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageData),
        "wireless-usage-data-africa" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageDataAfrica),
        "wireless-usage-data-asia" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageDataAsia),
        "wireless-usage-data-centralandsouthamerica" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageDataCentralandsouthamerica),
        "wireless-usage-data-custom-additionalmb" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageDataCustomAdditionalmb),
        "wireless-usage-data-custom-first5mb" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageDataCustomFirst5mb),
        "wireless-usage-data-domestic-roaming" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageDataDomesticRoaming),
        "wireless-usage-data-europe" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageDataEurope),
        "wireless-usage-data-individual-additionalgb" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageDataIndividualAdditionalgb),
        "wireless-usage-data-individual-firstgb" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageDataIndividualFirstgb),
        "wireless-usage-data-international-roaming-canada" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageDataInternationalRoamingCanada),
        "wireless-usage-data-international-roaming-india" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageDataInternationalRoamingIndia),
        "wireless-usage-data-international-roaming-mexico" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageDataInternationalRoamingMexico),
        "wireless-usage-data-northamerica" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageDataNorthamerica),
        "wireless-usage-data-oceania" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageDataOceania),
        "wireless-usage-data-pooled" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageDataPooled),
        "wireless-usage-data-pooled-downlink" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageDataPooledDownlink),
        "wireless-usage-data-pooled-uplink" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageDataPooledUplink),
        "wireless-usage-mrc" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageMrc),
        "wireless-usage-mrc-custom" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageMrcCustom),
        "wireless-usage-mrc-individual" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageMrcIndividual),
        "wireless-usage-mrc-pooled" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageMrcPooled),
        "wireless-usage-mrc-suspended" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageMrcSuspended),
        "wireless-usage-sms" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageSms),
        "wireless-usage-voice" => Some(iface_api20100401_trigger::UsageTriggerEnumUsageCategory::WirelessUsageVoice),
        _ => None,
    }
}

fn iface_api20100401_trigger__api_v2010_account_usage_usage_trigger_callback_method_enum__from_str(s: &str) -> Option<iface_api20100401_trigger::ApiV2010AccountUsageUsageTriggerCallbackMethodEnum> {
    match s {
        "HEAD" => Some(iface_api20100401_trigger::ApiV2010AccountUsageUsageTriggerCallbackMethodEnum::Head),
        "GET" => Some(iface_api20100401_trigger::ApiV2010AccountUsageUsageTriggerCallbackMethodEnum::Get),
        "POST" => Some(iface_api20100401_trigger::ApiV2010AccountUsageUsageTriggerCallbackMethodEnum::Post),
        "PATCH" => Some(iface_api20100401_trigger::ApiV2010AccountUsageUsageTriggerCallbackMethodEnum::Patch),
        "PUT" => Some(iface_api20100401_trigger::ApiV2010AccountUsageUsageTriggerCallbackMethodEnum::Put),
        "DELETE" => Some(iface_api20100401_trigger::ApiV2010AccountUsageUsageTriggerCallbackMethodEnum::Delete),
        _ => None,
    }
}

fn iface_api20100401_trigger__list_usage_trigger__ok(body: String) -> Result<iface_api20100401_trigger::ListUsageTriggerResponse, crate::runtime::DispatchError> {
    let v: Value = match serde_json::from_str(&body) {
        Ok(v) => v,
        Err(e) => return Err(crate::runtime::DispatchError::Transport(format!("failed to decode response body as JSON: {e}"))),
    };
    match iface_api20100401_trigger__list_usage_trigger_response__from_json(&v) {
        Some(x) => Ok(x),
        None => Err(crate::runtime::DispatchError::Transport("response body did not match the expected schema".to_string())),
    }
}

fn iface_api20100401_trigger__list_usage_trigger__err(e: crate::runtime::DispatchError) -> String {
    match e {
        crate::runtime::DispatchError::Http { status, body } => format!("HTTP {status}: {body}"),
        crate::runtime::DispatchError::Transport(m) => m,
    }
}

fn iface_api20100401_trigger__create_usage_trigger__ok(body: String) -> Result<iface_api20100401_trigger::ApiV2010AccountUsageUsageTrigger, crate::runtime::DispatchError> {
    let v: Value = match serde_json::from_str(&body) {
        Ok(v) => v,
        Err(e) => return Err(crate::runtime::DispatchError::Transport(format!("failed to decode response body as JSON: {e}"))),
    };
    match iface_api20100401_trigger__api_v2010_account_usage_usage_trigger__from_json(&v) {
        Some(x) => Ok(x),
        None => Err(crate::runtime::DispatchError::Transport("response body did not match the expected schema".to_string())),
    }
}

fn iface_api20100401_trigger__create_usage_trigger__err(e: crate::runtime::DispatchError) -> String {
    match e {
        crate::runtime::DispatchError::Http { status, body } => format!("HTTP {status}: {body}"),
        crate::runtime::DispatchError::Transport(m) => m,
    }
}

fn iface_api20100401_trigger__fetch_usage_trigger__ok(body: String) -> Result<iface_api20100401_trigger::ApiV2010AccountUsageUsageTrigger, crate::runtime::DispatchError> {
    let v: Value = match serde_json::from_str(&body) {
        Ok(v) => v,
        Err(e) => return Err(crate::runtime::DispatchError::Transport(format!("failed to decode response body as JSON: {e}"))),
    };
    match iface_api20100401_trigger__api_v2010_account_usage_usage_trigger__from_json(&v) {
        Some(x) => Ok(x),
        None => Err(crate::runtime::DispatchError::Transport("response body did not match the expected schema".to_string())),
    }
}

fn iface_api20100401_trigger__fetch_usage_trigger__err(e: crate::runtime::DispatchError) -> String {
    match e {
        crate::runtime::DispatchError::Http { status, body } => format!("HTTP {status}: {body}"),
        crate::runtime::DispatchError::Transport(m) => m,
    }
}

fn iface_api20100401_trigger__update_usage_trigger__ok(body: String) -> Result<iface_api20100401_trigger::ApiV2010AccountUsageUsageTrigger, crate::runtime::DispatchError> {
    let v: Value = match serde_json::from_str(&body) {
        Ok(v) => v,
        Err(e) => return Err(crate::runtime::DispatchError::Transport(format!("failed to decode response body as JSON: {e}"))),
    };
    match iface_api20100401_trigger__api_v2010_account_usage_usage_trigger__from_json(&v) {
        Some(x) => Ok(x),
        None => Err(crate::runtime::DispatchError::Transport("response body did not match the expected schema".to_string())),
    }
}

fn iface_api20100401_trigger__update_usage_trigger__err(e: crate::runtime::DispatchError) -> String {
    match e {
        crate::runtime::DispatchError::Http { status, body } => format!("HTTP {status}: {body}"),
        crate::runtime::DispatchError::Transport(m) => m,
    }
}

fn iface_api20100401_trigger__delete_usage_trigger__ok(body: String) -> Result<String, crate::runtime::DispatchError> {
    Ok(body)
}

fn iface_api20100401_trigger__delete_usage_trigger__err(e: crate::runtime::DispatchError) -> String {
    match e {
        crate::runtime::DispatchError::Http { status, body } => format!("HTTP {status}: {body}"),
        crate::runtime::DispatchError::Transport(m) => m,
    }
}

impl iface_api20100401_trigger::Guest for crate::Component {
    fn list_usage_trigger(params: iface_api20100401_trigger::ListUsageTriggerParams) -> Result<iface_api20100401_trigger::ListUsageTriggerResponse, String> {
        let json = iface_api20100401_trigger__list_usage_trigger_params__to_json(&params);
        match dispatch(&OP_API20100401_TRIGGER_LIST_USAGE_TRIGGER, json).and_then(iface_api20100401_trigger__list_usage_trigger__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_api20100401_trigger__list_usage_trigger__err(e)),
        }
    }
    fn create_usage_trigger(params: iface_api20100401_trigger::CreateUsageTriggerParams) -> Result<iface_api20100401_trigger::ApiV2010AccountUsageUsageTrigger, String> {
        let json = iface_api20100401_trigger__create_usage_trigger_params__to_json(&params);
        match dispatch(&OP_API20100401_TRIGGER_CREATE_USAGE_TRIGGER, json).and_then(iface_api20100401_trigger__create_usage_trigger__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_api20100401_trigger__create_usage_trigger__err(e)),
        }
    }
    fn fetch_usage_trigger(params: iface_api20100401_trigger::FetchUsageTriggerParams) -> Result<iface_api20100401_trigger::ApiV2010AccountUsageUsageTrigger, String> {
        let json = iface_api20100401_trigger__fetch_usage_trigger_params__to_json(&params);
        match dispatch(&OP_API20100401_TRIGGER_FETCH_USAGE_TRIGGER, json).and_then(iface_api20100401_trigger__fetch_usage_trigger__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_api20100401_trigger__fetch_usage_trigger__err(e)),
        }
    }
    fn update_usage_trigger(params: iface_api20100401_trigger::UpdateUsageTriggerParams) -> Result<iface_api20100401_trigger::ApiV2010AccountUsageUsageTrigger, String> {
        let json = iface_api20100401_trigger__update_usage_trigger_params__to_json(&params);
        match dispatch(&OP_API20100401_TRIGGER_UPDATE_USAGE_TRIGGER, json).and_then(iface_api20100401_trigger__update_usage_trigger__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_api20100401_trigger__update_usage_trigger__err(e)),
        }
    }
    fn delete_usage_trigger(params: iface_api20100401_trigger::DeleteUsageTriggerParams) -> Result<String, String> {
        let json = iface_api20100401_trigger__delete_usage_trigger_params__to_json(&params);
        match dispatch(&OP_API20100401_TRIGGER_DELETE_USAGE_TRIGGER, json).and_then(iface_api20100401_trigger__delete_usage_trigger__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_api20100401_trigger__delete_usage_trigger__err(e)),
        }
    }
}
