// AUTOGENERATED by openapi-bindgen. Do not edit by hand.

use crate::runtime::{dispatch, AuthApply, AuthKind, FieldLocation, FieldSpec, OpSpec};
use crate::exports::autostamp::telnyx::messages as iface_messages;
use serde_json::{Map, Value};

const OP_MESSAGES_CREATE_MESSAGE: OpSpec = OpSpec {
    method: "POST",
    path_template: "/messages",
    fields: &[
        FieldSpec { snake: "auto_detect", wire: "auto_detect", location: FieldLocation::Body },
        FieldSpec { snake: "from", wire: "from", location: FieldLocation::Body },
        FieldSpec { snake: "media_urls", wire: "media_urls", location: FieldLocation::Body },
        FieldSpec { snake: "messaging_profile_id", wire: "messaging_profile_id", location: FieldLocation::Body },
        FieldSpec { snake: "subject", wire: "subject", location: FieldLocation::Body },
        FieldSpec { snake: "text", wire: "text", location: FieldLocation::Body },
        FieldSpec { snake: "to", wire: "to", location: FieldLocation::Body },
        FieldSpec { snake: "type", wire: "type", location: FieldLocation::Body },
        FieldSpec { snake: "use_profile_webhooks", wire: "use_profile_webhooks", location: FieldLocation::Body },
        FieldSpec { snake: "webhook_failover_url", wire: "webhook_failover_url", location: FieldLocation::Body },
        FieldSpec { snake: "webhook_url", wire: "webhook_url", location: FieldLocation::Body },
    ],
    auth: &[
        AuthApply { secret_key: "BearerAuth", kind: AuthKind::Bearer },
    ],
};

const OP_MESSAGES_CREATE_LONG_CODE_MESSAGE: OpSpec = OpSpec {
    method: "POST",
    path_template: "/messages/long_code",
    fields: &[
        FieldSpec { snake: "auto_detect", wire: "auto_detect", location: FieldLocation::Body },
        FieldSpec { snake: "from", wire: "from", location: FieldLocation::Body },
        FieldSpec { snake: "media_urls", wire: "media_urls", location: FieldLocation::Body },
        FieldSpec { snake: "subject", wire: "subject", location: FieldLocation::Body },
        FieldSpec { snake: "text", wire: "text", location: FieldLocation::Body },
        FieldSpec { snake: "to", wire: "to", location: FieldLocation::Body },
        FieldSpec { snake: "type", wire: "type", location: FieldLocation::Body },
        FieldSpec { snake: "use_profile_webhooks", wire: "use_profile_webhooks", location: FieldLocation::Body },
        FieldSpec { snake: "webhook_failover_url", wire: "webhook_failover_url", location: FieldLocation::Body },
        FieldSpec { snake: "webhook_url", wire: "webhook_url", location: FieldLocation::Body },
    ],
    auth: &[
        AuthApply { secret_key: "BearerAuth", kind: AuthKind::Bearer },
    ],
};

const OP_MESSAGES_CREATE_NUMBER_POOL_MESSAGE: OpSpec = OpSpec {
    method: "POST",
    path_template: "/messages/number_pool",
    fields: &[
        FieldSpec { snake: "auto_detect", wire: "auto_detect", location: FieldLocation::Body },
        FieldSpec { snake: "media_urls", wire: "media_urls", location: FieldLocation::Body },
        FieldSpec { snake: "messaging_profile_id", wire: "messaging_profile_id", location: FieldLocation::Body },
        FieldSpec { snake: "subject", wire: "subject", location: FieldLocation::Body },
        FieldSpec { snake: "text", wire: "text", location: FieldLocation::Body },
        FieldSpec { snake: "to", wire: "to", location: FieldLocation::Body },
        FieldSpec { snake: "type", wire: "type", location: FieldLocation::Body },
        FieldSpec { snake: "use_profile_webhooks", wire: "use_profile_webhooks", location: FieldLocation::Body },
        FieldSpec { snake: "webhook_failover_url", wire: "webhook_failover_url", location: FieldLocation::Body },
        FieldSpec { snake: "webhook_url", wire: "webhook_url", location: FieldLocation::Body },
    ],
    auth: &[
        AuthApply { secret_key: "BearerAuth", kind: AuthKind::Bearer },
    ],
};

const OP_MESSAGES_CREATE_SHORT_CODE_MESSAGE: OpSpec = OpSpec {
    method: "POST",
    path_template: "/messages/short_code",
    fields: &[
        FieldSpec { snake: "auto_detect", wire: "auto_detect", location: FieldLocation::Body },
        FieldSpec { snake: "from", wire: "from", location: FieldLocation::Body },
        FieldSpec { snake: "media_urls", wire: "media_urls", location: FieldLocation::Body },
        FieldSpec { snake: "subject", wire: "subject", location: FieldLocation::Body },
        FieldSpec { snake: "text", wire: "text", location: FieldLocation::Body },
        FieldSpec { snake: "to", wire: "to", location: FieldLocation::Body },
        FieldSpec { snake: "type", wire: "type", location: FieldLocation::Body },
        FieldSpec { snake: "use_profile_webhooks", wire: "use_profile_webhooks", location: FieldLocation::Body },
        FieldSpec { snake: "webhook_failover_url", wire: "webhook_failover_url", location: FieldLocation::Body },
        FieldSpec { snake: "webhook_url", wire: "webhook_url", location: FieldLocation::Body },
    ],
    auth: &[
        AuthApply { secret_key: "BearerAuth", kind: AuthKind::Bearer },
    ],
};

const OP_MESSAGES_RETRIEVE_MESSAGE: OpSpec = OpSpec {
    method: "GET",
    path_template: "/messages/{id}",
    fields: &[
        FieldSpec { snake: "id", wire: "id", location: FieldLocation::Path },
    ],
    auth: &[
        AuthApply { secret_key: "BearerAuth", kind: AuthKind::Bearer },
    ],
};

fn iface_messages__create_message_request_type_op_enum__to_str(e: &iface_messages::CreateMessageRequestTypeOpEnum) -> &'static str {
    match e {
        iface_messages::CreateMessageRequestTypeOpEnum::Sms => "SMS",
        iface_messages::CreateMessageRequestTypeOpEnum::Mms => "MMS",
    }
}

fn iface_messages__outbound_message_payload_direction_enum__to_str(e: &iface_messages::OutboundMessagePayloadDirectionEnum) -> &'static str {
    match e {
        iface_messages::OutboundMessagePayloadDirectionEnum::Outbound => "outbound",
    }
}

fn iface_messages__outbound_message_payload_from_op_line_type_enum__to_str(e: &iface_messages::OutboundMessagePayloadFromOpLineTypeEnum) -> &'static str {
    match e {
        iface_messages::OutboundMessagePayloadFromOpLineTypeEnum::Wireline => "Wireline",
        iface_messages::OutboundMessagePayloadFromOpLineTypeEnum::Wireless => "Wireless",
        iface_messages::OutboundMessagePayloadFromOpLineTypeEnum::VoWiFi => "VoWiFi",
        iface_messages::OutboundMessagePayloadFromOpLineTypeEnum::VoIp => "VoIP",
        iface_messages::OutboundMessagePayloadFromOpLineTypeEnum::PrePaidWireless => "Pre-Paid Wireless",
        iface_messages::OutboundMessagePayloadFromOpLineTypeEnum::Empty => "",
    }
}

fn iface_messages__outbound_message_payload_record_type_enum__to_str(e: &iface_messages::OutboundMessagePayloadRecordTypeEnum) -> &'static str {
    match e {
        iface_messages::OutboundMessagePayloadRecordTypeEnum::Message => "message",
    }
}

fn iface_messages__outbound_message_payload_to_item_status_enum__to_str(e: &iface_messages::OutboundMessagePayloadToItemStatusEnum) -> &'static str {
    match e {
        iface_messages::OutboundMessagePayloadToItemStatusEnum::Queued => "queued",
        iface_messages::OutboundMessagePayloadToItemStatusEnum::Sending => "sending",
        iface_messages::OutboundMessagePayloadToItemStatusEnum::Sent => "sent",
        iface_messages::OutboundMessagePayloadToItemStatusEnum::Expired => "expired",
        iface_messages::OutboundMessagePayloadToItemStatusEnum::SendingFailed => "sending_failed",
        iface_messages::OutboundMessagePayloadToItemStatusEnum::DeliveryUnconfirmed => "delivery_unconfirmed",
        iface_messages::OutboundMessagePayloadToItemStatusEnum::Delivered => "delivered",
        iface_messages::OutboundMessagePayloadToItemStatusEnum::DeliveryFailed => "delivery_failed",
    }
}

fn iface_messages__create_message_response__to_json(p: &iface_messages::CreateMessageResponse) -> Value {
    let mut m = Map::new();
    m.insert("data".into(), match (&p.data) { Some(v) => iface_messages__outbound_message_payload__to_json(v), None => Value::Null });
    Value::Object(m)
}

fn iface_messages__outbound_message_payload__to_json(p: &iface_messages::OutboundMessagePayload) -> Value {
    let mut m = Map::new();
    m.insert("completed_at".into(), match (&p.completed_at) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("cost".into(), match (&p.cost) { Some(v) => iface_messages__outbound_message_payload_cost__to_json(v), None => Value::Null });
    m.insert("direction".into(), match (&p.direction) { Some(v) => Value::String(iface_messages__outbound_message_payload_direction_enum__to_str(v).into()), None => Value::Null });
    m.insert("encoding".into(), match (&p.encoding) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("errors".into(), match (&p.errors) { Some(v) => Value::Array((v).iter().map(|v| iface_messages__error__to_json(v)).collect()), None => Value::Null });
    m.insert("from".into(), match (&p.from_op) { Some(v) => iface_messages__outbound_message_payload_from_op__to_json(v), None => Value::Null });
    m.insert("id".into(), match (&p.id) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("media".into(), match (&p.media) { Some(v) => Value::Array((v).iter().map(|v| iface_messages__outbound_message_payload_media_item__to_json(v)).collect()), None => Value::Null });
    m.insert("messaging_profile_id".into(), match (&p.messaging_profile_id) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("organization_id".into(), match (&p.organization_id) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("parts".into(), match (&p.parts) { Some(v) => Value::Number(serde_json::Number::from(*(v))), None => Value::Null });
    m.insert("received_at".into(), match (&p.received_at) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("record_type".into(), match (&p.record_type) { Some(v) => Value::String(iface_messages__outbound_message_payload_record_type_enum__to_str(v).into()), None => Value::Null });
    m.insert("sent_at".into(), match (&p.sent_at) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("subject".into(), match (&p.subject) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("tags".into(), match (&p.tags) { Some(v) => Value::Array((v).iter().map(|v| Value::String((v).clone())).collect()), None => Value::Null });
    m.insert("text".into(), match (&p.text) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("to".into(), match (&p.to) { Some(v) => Value::Array((v).iter().map(|v| iface_messages__outbound_message_payload_to_item__to_json(v)).collect()), None => Value::Null });
    m.insert("type".into(), match (&p.type_op) { Some(v) => Value::String(iface_messages__create_message_request_type_op_enum__to_str(v).into()), None => Value::Null });
    m.insert("valid_until".into(), match (&p.valid_until) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("webhook_failover_url".into(), match (&p.webhook_failover_url) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("webhook_url".into(), match (&p.webhook_url) { Some(v) => Value::String((v).clone()), None => Value::Null });
    Value::Object(m)
}

fn iface_messages__outbound_message_payload_cost__to_json(p: &iface_messages::OutboundMessagePayloadCost) -> Value {
    let mut m = Map::new();
    m.insert("amount".into(), match (&p.amount) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("currency".into(), match (&p.currency) { Some(v) => Value::String((v).clone()), None => Value::Null });
    Value::Object(m)
}

fn iface_messages__error__to_json(p: &iface_messages::Error) -> Value {
    let mut m = Map::new();
    m.insert("code".into(), Value::String((&p.code).clone()));
    m.insert("detail".into(), match (&p.detail) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("meta".into(), match (&p.meta) { Some(v) => Value::Object((v).iter().map(|e| (e.key.clone(), Value::String((&e.value).clone()))).collect()), None => Value::Null });
    m.insert("source".into(), match (&p.source) { Some(v) => iface_messages__error_source__to_json(v), None => Value::Null });
    m.insert("title".into(), Value::String((&p.title).clone()));
    Value::Object(m)
}

fn iface_messages__error_meta_entry__to_json(p: &iface_messages::ErrorMetaEntry) -> Value {
    let mut m = Map::new();
    m.insert("key".into(), Value::String((&p.key).clone()));
    m.insert("value".into(), Value::String((&p.value).clone()));
    Value::Object(m)
}

fn iface_messages__error_source__to_json(p: &iface_messages::ErrorSource) -> Value {
    let mut m = Map::new();
    m.insert("parameter".into(), match (&p.parameter) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("pointer".into(), match (&p.pointer) { Some(v) => Value::String((v).clone()), None => Value::Null });
    Value::Object(m)
}

fn iface_messages__outbound_message_payload_from_op__to_json(p: &iface_messages::OutboundMessagePayloadFromOp) -> Value {
    let mut m = Map::new();
    m.insert("carrier".into(), match (&p.carrier) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("line_type".into(), match (&p.line_type) { Some(v) => Value::String(iface_messages__outbound_message_payload_from_op_line_type_enum__to_str(v).into()), None => Value::Null });
    m.insert("phone_number".into(), match (&p.phone_number) { Some(v) => Value::String((v).clone()), None => Value::Null });
    Value::Object(m)
}

fn iface_messages__outbound_message_payload_media_item__to_json(p: &iface_messages::OutboundMessagePayloadMediaItem) -> Value {
    let mut m = Map::new();
    m.insert("content_type".into(), match (&p.content_type) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("sha256".into(), match (&p.sha256) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("size".into(), match (&p.size) { Some(v) => Value::Number(serde_json::Number::from(*(v))), None => Value::Null });
    m.insert("url".into(), match (&p.url) { Some(v) => Value::String((v).clone()), None => Value::Null });
    Value::Object(m)
}

fn iface_messages__outbound_message_payload_to_item__to_json(p: &iface_messages::OutboundMessagePayloadToItem) -> Value {
    let mut m = Map::new();
    m.insert("carrier".into(), match (&p.carrier) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("line_type".into(), match (&p.line_type) { Some(v) => Value::String(iface_messages__outbound_message_payload_from_op_line_type_enum__to_str(v).into()), None => Value::Null });
    m.insert("phone_number".into(), match (&p.phone_number) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("status".into(), match (&p.status) { Some(v) => Value::String(iface_messages__outbound_message_payload_to_item_status_enum__to_str(v).into()), None => Value::Null });
    Value::Object(m)
}

fn iface_messages__create_long_code_message_response__to_json(p: &iface_messages::CreateLongCodeMessageResponse) -> Value {
    let mut m = Map::new();
    m.insert("data".into(), match (&p.data) { Some(v) => iface_messages__outbound_message_payload__to_json(v), None => Value::Null });
    Value::Object(m)
}

fn iface_messages__create_number_pool_message_response__to_json(p: &iface_messages::CreateNumberPoolMessageResponse) -> Value {
    let mut m = Map::new();
    m.insert("data".into(), match (&p.data) { Some(v) => iface_messages__outbound_message_payload__to_json(v), None => Value::Null });
    Value::Object(m)
}

fn iface_messages__create_short_code_message_response__to_json(p: &iface_messages::CreateShortCodeMessageResponse) -> Value {
    let mut m = Map::new();
    m.insert("data".into(), match (&p.data) { Some(v) => iface_messages__outbound_message_payload__to_json(v), None => Value::Null });
    Value::Object(m)
}

fn iface_messages__retrieve_message_response__to_json(p: &iface_messages::RetrieveMessageResponse) -> Value {
    let mut m = Map::new();
    m.insert("data".into(), match (&p.data) { Some(v) => iface_messages__outbound_message_payload__to_json(v), None => Value::Null });
    Value::Object(m)
}

fn iface_messages__create_message_params__to_json(p: &iface_messages::CreateMessageParams) -> Value {
    let mut m = Map::new();
    m.insert("auto_detect".into(), match (&p.auto_detect) { Some(v) => Value::Bool(*(v)), None => Value::Null });
    m.insert("from".into(), match (&p.from_op) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("media_urls".into(), match (&p.media_urls) { Some(v) => Value::Array((v).iter().map(|v| Value::String((v).clone())).collect()), None => Value::Null });
    m.insert("messaging_profile_id".into(), match (&p.messaging_profile_id) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("subject".into(), match (&p.subject) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("text".into(), match (&p.text) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("to".into(), Value::String((&p.to).clone()));
    m.insert("type".into(), match (&p.type_op) { Some(v) => Value::String(iface_messages__create_message_request_type_op_enum__to_str(v).into()), None => Value::Null });
    m.insert("use_profile_webhooks".into(), match (&p.use_profile_webhooks) { Some(v) => Value::Bool(*(v)), None => Value::Null });
    m.insert("webhook_failover_url".into(), match (&p.webhook_failover_url) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("webhook_url".into(), match (&p.webhook_url) { Some(v) => Value::String((v).clone()), None => Value::Null });
    Value::Object(m)
}

fn iface_messages__create_long_code_message_params__to_json(p: &iface_messages::CreateLongCodeMessageParams) -> Value {
    let mut m = Map::new();
    m.insert("auto_detect".into(), match (&p.auto_detect) { Some(v) => Value::Bool(*(v)), None => Value::Null });
    m.insert("from".into(), Value::String((&p.from_op).clone()));
    m.insert("media_urls".into(), match (&p.media_urls) { Some(v) => Value::Array((v).iter().map(|v| Value::String((v).clone())).collect()), None => Value::Null });
    m.insert("subject".into(), match (&p.subject) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("text".into(), match (&p.text) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("to".into(), Value::String((&p.to).clone()));
    m.insert("type".into(), match (&p.type_op) { Some(v) => Value::String(iface_messages__create_message_request_type_op_enum__to_str(v).into()), None => Value::Null });
    m.insert("use_profile_webhooks".into(), match (&p.use_profile_webhooks) { Some(v) => Value::Bool(*(v)), None => Value::Null });
    m.insert("webhook_failover_url".into(), match (&p.webhook_failover_url) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("webhook_url".into(), match (&p.webhook_url) { Some(v) => Value::String((v).clone()), None => Value::Null });
    Value::Object(m)
}

fn iface_messages__create_number_pool_message_params__to_json(p: &iface_messages::CreateNumberPoolMessageParams) -> Value {
    let mut m = Map::new();
    m.insert("auto_detect".into(), match (&p.auto_detect) { Some(v) => Value::Bool(*(v)), None => Value::Null });
    m.insert("media_urls".into(), match (&p.media_urls) { Some(v) => Value::Array((v).iter().map(|v| Value::String((v).clone())).collect()), None => Value::Null });
    m.insert("messaging_profile_id".into(), Value::String((&p.messaging_profile_id).clone()));
    m.insert("subject".into(), match (&p.subject) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("text".into(), match (&p.text) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("to".into(), Value::String((&p.to).clone()));
    m.insert("type".into(), match (&p.type_op) { Some(v) => Value::String(iface_messages__create_message_request_type_op_enum__to_str(v).into()), None => Value::Null });
    m.insert("use_profile_webhooks".into(), match (&p.use_profile_webhooks) { Some(v) => Value::Bool(*(v)), None => Value::Null });
    m.insert("webhook_failover_url".into(), match (&p.webhook_failover_url) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("webhook_url".into(), match (&p.webhook_url) { Some(v) => Value::String((v).clone()), None => Value::Null });
    Value::Object(m)
}

fn iface_messages__create_short_code_message_params__to_json(p: &iface_messages::CreateShortCodeMessageParams) -> Value {
    let mut m = Map::new();
    m.insert("auto_detect".into(), match (&p.auto_detect) { Some(v) => Value::Bool(*(v)), None => Value::Null });
    m.insert("from".into(), Value::String((&p.from_op).clone()));
    m.insert("media_urls".into(), match (&p.media_urls) { Some(v) => Value::Array((v).iter().map(|v| Value::String((v).clone())).collect()), None => Value::Null });
    m.insert("subject".into(), match (&p.subject) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("text".into(), match (&p.text) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("to".into(), Value::String((&p.to).clone()));
    m.insert("type".into(), match (&p.type_op) { Some(v) => Value::String(iface_messages__create_message_request_type_op_enum__to_str(v).into()), None => Value::Null });
    m.insert("use_profile_webhooks".into(), match (&p.use_profile_webhooks) { Some(v) => Value::Bool(*(v)), None => Value::Null });
    m.insert("webhook_failover_url".into(), match (&p.webhook_failover_url) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("webhook_url".into(), match (&p.webhook_url) { Some(v) => Value::String((v).clone()), None => Value::Null });
    Value::Object(m)
}

fn iface_messages__retrieve_message_params__to_json(p: &iface_messages::RetrieveMessageParams) -> Value {
    let mut m = Map::new();
    m.insert("id".into(), Value::String((&p.id).clone()));
    Value::Object(m)
}

fn iface_messages__create_message_response__from_json(v: &Value) -> Option<iface_messages::CreateMessageResponse> {
    let m = v.as_object()?;
    Some(iface_messages::CreateMessageResponse {
        data: m.get("data").filter(|v| !v.is_null()).and_then(|v| iface_messages__outbound_message_payload__from_json(v)),
    })
}

fn iface_messages__outbound_message_payload__from_json(v: &Value) -> Option<iface_messages::OutboundMessagePayload> {
    let m = v.as_object()?;
    Some(iface_messages::OutboundMessagePayload {
        completed_at: m.get("completed_at").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        cost: m.get("cost").filter(|v| !v.is_null()).and_then(|v| iface_messages__outbound_message_payload_cost__from_json(v)),
        direction: m.get("direction").filter(|v| !v.is_null()).and_then(|v| (v).as_str().and_then(iface_messages__outbound_message_payload_direction_enum__from_str)),
        encoding: m.get("encoding").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        errors: m.get("errors").filter(|v| !v.is_null()).and_then(|v| (v).as_array().map(|a| a.iter().filter_map(|x| iface_messages__error__from_json(x)).collect())),
        from_op: m.get("from").filter(|v| !v.is_null()).and_then(|v| iface_messages__outbound_message_payload_from_op__from_json(v)),
        id: m.get("id").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        media: m.get("media").filter(|v| !v.is_null()).and_then(|v| (v).as_array().map(|a| a.iter().filter_map(|x| iface_messages__outbound_message_payload_media_item__from_json(x)).collect())),
        messaging_profile_id: m.get("messaging_profile_id").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        organization_id: m.get("organization_id").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        parts: m.get("parts").filter(|v| !v.is_null()).and_then(|v| (v).as_i64().map(|n| n as i32)),
        received_at: m.get("received_at").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        record_type: m.get("record_type").filter(|v| !v.is_null()).and_then(|v| (v).as_str().and_then(iface_messages__outbound_message_payload_record_type_enum__from_str)),
        sent_at: m.get("sent_at").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        subject: m.get("subject").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        tags: m.get("tags").filter(|v| !v.is_null()).and_then(|v| (v).as_array().map(|a| a.iter().filter_map(|x| (x).as_str().map(|s| s.to_string())).collect())),
        text: m.get("text").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        to: m.get("to").filter(|v| !v.is_null()).and_then(|v| (v).as_array().map(|a| a.iter().filter_map(|x| iface_messages__outbound_message_payload_to_item__from_json(x)).collect())),
        type_op: m.get("type").filter(|v| !v.is_null()).and_then(|v| (v).as_str().and_then(iface_messages__create_message_request_type_op_enum__from_str)),
        valid_until: m.get("valid_until").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        webhook_failover_url: m.get("webhook_failover_url").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        webhook_url: m.get("webhook_url").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
    })
}

fn iface_messages__outbound_message_payload_cost__from_json(v: &Value) -> Option<iface_messages::OutboundMessagePayloadCost> {
    let m = v.as_object()?;
    Some(iface_messages::OutboundMessagePayloadCost {
        amount: m.get("amount").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        currency: m.get("currency").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
    })
}

fn iface_messages__error__from_json(v: &Value) -> Option<iface_messages::Error> {
    let m = v.as_object()?;
    Some(iface_messages::Error {
        code: m.get("code").and_then(|v| (v).as_str().map(|s| s.to_string())).unwrap_or_default(),
        detail: m.get("detail").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        meta: m.get("meta").filter(|v| !v.is_null()).and_then(|v| (v).as_object().map(|o| o.iter().filter_map(|(k, x)| ((x).as_str().map(|s| s.to_string())).map(|val| iface_messages::ErrorMetaEntry { key: k.clone(), value: val })).collect())),
        source: m.get("source").filter(|v| !v.is_null()).and_then(|v| iface_messages__error_source__from_json(v)),
        title: m.get("title").and_then(|v| (v).as_str().map(|s| s.to_string())).unwrap_or_default(),
    })
}

fn iface_messages__error_meta_entry__from_json(v: &Value) -> Option<iface_messages::ErrorMetaEntry> {
    let m = v.as_object()?;
    Some(iface_messages::ErrorMetaEntry {
        key: m.get("key").and_then(|v| (v).as_str().map(|s| s.to_string())).unwrap_or_default(),
        value: m.get("value").and_then(|v| (v).as_str().map(|s| s.to_string())).unwrap_or_default(),
    })
}

fn iface_messages__error_source__from_json(v: &Value) -> Option<iface_messages::ErrorSource> {
    let m = v.as_object()?;
    Some(iface_messages::ErrorSource {
        parameter: m.get("parameter").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        pointer: m.get("pointer").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
    })
}

fn iface_messages__outbound_message_payload_from_op__from_json(v: &Value) -> Option<iface_messages::OutboundMessagePayloadFromOp> {
    let m = v.as_object()?;
    Some(iface_messages::OutboundMessagePayloadFromOp {
        carrier: m.get("carrier").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        line_type: m.get("line_type").filter(|v| !v.is_null()).and_then(|v| (v).as_str().and_then(iface_messages__outbound_message_payload_from_op_line_type_enum__from_str)),
        phone_number: m.get("phone_number").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
    })
}

fn iface_messages__outbound_message_payload_media_item__from_json(v: &Value) -> Option<iface_messages::OutboundMessagePayloadMediaItem> {
    let m = v.as_object()?;
    Some(iface_messages::OutboundMessagePayloadMediaItem {
        content_type: m.get("content_type").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        sha256: m.get("sha256").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        size: m.get("size").filter(|v| !v.is_null()).and_then(|v| (v).as_i64().map(|n| n as i32)),
        url: m.get("url").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
    })
}

fn iface_messages__outbound_message_payload_to_item__from_json(v: &Value) -> Option<iface_messages::OutboundMessagePayloadToItem> {
    let m = v.as_object()?;
    Some(iface_messages::OutboundMessagePayloadToItem {
        carrier: m.get("carrier").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        line_type: m.get("line_type").filter(|v| !v.is_null()).and_then(|v| (v).as_str().and_then(iface_messages__outbound_message_payload_from_op_line_type_enum__from_str)),
        phone_number: m.get("phone_number").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        status: m.get("status").filter(|v| !v.is_null()).and_then(|v| (v).as_str().and_then(iface_messages__outbound_message_payload_to_item_status_enum__from_str)),
    })
}

fn iface_messages__create_long_code_message_response__from_json(v: &Value) -> Option<iface_messages::CreateLongCodeMessageResponse> {
    let m = v.as_object()?;
    Some(iface_messages::CreateLongCodeMessageResponse {
        data: m.get("data").filter(|v| !v.is_null()).and_then(|v| iface_messages__outbound_message_payload__from_json(v)),
    })
}

fn iface_messages__create_number_pool_message_response__from_json(v: &Value) -> Option<iface_messages::CreateNumberPoolMessageResponse> {
    let m = v.as_object()?;
    Some(iface_messages::CreateNumberPoolMessageResponse {
        data: m.get("data").filter(|v| !v.is_null()).and_then(|v| iface_messages__outbound_message_payload__from_json(v)),
    })
}

fn iface_messages__create_short_code_message_response__from_json(v: &Value) -> Option<iface_messages::CreateShortCodeMessageResponse> {
    let m = v.as_object()?;
    Some(iface_messages::CreateShortCodeMessageResponse {
        data: m.get("data").filter(|v| !v.is_null()).and_then(|v| iface_messages__outbound_message_payload__from_json(v)),
    })
}

fn iface_messages__retrieve_message_response__from_json(v: &Value) -> Option<iface_messages::RetrieveMessageResponse> {
    let m = v.as_object()?;
    Some(iface_messages::RetrieveMessageResponse {
        data: m.get("data").filter(|v| !v.is_null()).and_then(|v| iface_messages__outbound_message_payload__from_json(v)),
    })
}

fn iface_messages__create_message_request_type_op_enum__from_str(s: &str) -> Option<iface_messages::CreateMessageRequestTypeOpEnum> {
    match s {
        "SMS" => Some(iface_messages::CreateMessageRequestTypeOpEnum::Sms),
        "MMS" => Some(iface_messages::CreateMessageRequestTypeOpEnum::Mms),
        _ => None,
    }
}

fn iface_messages__outbound_message_payload_direction_enum__from_str(s: &str) -> Option<iface_messages::OutboundMessagePayloadDirectionEnum> {
    match s {
        "outbound" => Some(iface_messages::OutboundMessagePayloadDirectionEnum::Outbound),
        _ => None,
    }
}

fn iface_messages__outbound_message_payload_from_op_line_type_enum__from_str(s: &str) -> Option<iface_messages::OutboundMessagePayloadFromOpLineTypeEnum> {
    match s {
        "Wireline" => Some(iface_messages::OutboundMessagePayloadFromOpLineTypeEnum::Wireline),
        "Wireless" => Some(iface_messages::OutboundMessagePayloadFromOpLineTypeEnum::Wireless),
        "VoWiFi" => Some(iface_messages::OutboundMessagePayloadFromOpLineTypeEnum::VoWiFi),
        "VoIP" => Some(iface_messages::OutboundMessagePayloadFromOpLineTypeEnum::VoIp),
        "Pre-Paid Wireless" => Some(iface_messages::OutboundMessagePayloadFromOpLineTypeEnum::PrePaidWireless),
        "" => Some(iface_messages::OutboundMessagePayloadFromOpLineTypeEnum::Empty),
        _ => None,
    }
}

fn iface_messages__outbound_message_payload_record_type_enum__from_str(s: &str) -> Option<iface_messages::OutboundMessagePayloadRecordTypeEnum> {
    match s {
        "message" => Some(iface_messages::OutboundMessagePayloadRecordTypeEnum::Message),
        _ => None,
    }
}

fn iface_messages__outbound_message_payload_to_item_status_enum__from_str(s: &str) -> Option<iface_messages::OutboundMessagePayloadToItemStatusEnum> {
    match s {
        "queued" => Some(iface_messages::OutboundMessagePayloadToItemStatusEnum::Queued),
        "sending" => Some(iface_messages::OutboundMessagePayloadToItemStatusEnum::Sending),
        "sent" => Some(iface_messages::OutboundMessagePayloadToItemStatusEnum::Sent),
        "expired" => Some(iface_messages::OutboundMessagePayloadToItemStatusEnum::Expired),
        "sending_failed" => Some(iface_messages::OutboundMessagePayloadToItemStatusEnum::SendingFailed),
        "delivery_unconfirmed" => Some(iface_messages::OutboundMessagePayloadToItemStatusEnum::DeliveryUnconfirmed),
        "delivered" => Some(iface_messages::OutboundMessagePayloadToItemStatusEnum::Delivered),
        "delivery_failed" => Some(iface_messages::OutboundMessagePayloadToItemStatusEnum::DeliveryFailed),
        _ => None,
    }
}

fn iface_messages__create_message__ok(body: String) -> Result<iface_messages::CreateMessageResponse, crate::runtime::DispatchError> {
    let v: Value = match serde_json::from_str(&body) {
        Ok(v) => v,
        Err(e) => return Err(crate::runtime::DispatchError::Transport(format!("failed to decode response body as JSON: {e}"))),
    };
    match iface_messages__create_message_response__from_json(&v) {
        Some(x) => Ok(x),
        None => Err(crate::runtime::DispatchError::Transport("response body did not match the expected schema".to_string())),
    }
}

fn iface_messages__create_message__err(e: crate::runtime::DispatchError) -> String {
    match e {
        crate::runtime::DispatchError::Http { status, body } => format!("HTTP {status}: {body}"),
        crate::runtime::DispatchError::Transport(m) => m,
    }
}

fn iface_messages__create_long_code_message__ok(body: String) -> Result<iface_messages::CreateLongCodeMessageResponse, crate::runtime::DispatchError> {
    let v: Value = match serde_json::from_str(&body) {
        Ok(v) => v,
        Err(e) => return Err(crate::runtime::DispatchError::Transport(format!("failed to decode response body as JSON: {e}"))),
    };
    match iface_messages__create_long_code_message_response__from_json(&v) {
        Some(x) => Ok(x),
        None => Err(crate::runtime::DispatchError::Transport("response body did not match the expected schema".to_string())),
    }
}

fn iface_messages__create_long_code_message__err(e: crate::runtime::DispatchError) -> String {
    match e {
        crate::runtime::DispatchError::Http { status, body } => format!("HTTP {status}: {body}"),
        crate::runtime::DispatchError::Transport(m) => m,
    }
}

fn iface_messages__create_number_pool_message__ok(body: String) -> Result<iface_messages::CreateNumberPoolMessageResponse, crate::runtime::DispatchError> {
    let v: Value = match serde_json::from_str(&body) {
        Ok(v) => v,
        Err(e) => return Err(crate::runtime::DispatchError::Transport(format!("failed to decode response body as JSON: {e}"))),
    };
    match iface_messages__create_number_pool_message_response__from_json(&v) {
        Some(x) => Ok(x),
        None => Err(crate::runtime::DispatchError::Transport("response body did not match the expected schema".to_string())),
    }
}

fn iface_messages__create_number_pool_message__err(e: crate::runtime::DispatchError) -> String {
    match e {
        crate::runtime::DispatchError::Http { status, body } => format!("HTTP {status}: {body}"),
        crate::runtime::DispatchError::Transport(m) => m,
    }
}

fn iface_messages__create_short_code_message__ok(body: String) -> Result<iface_messages::CreateShortCodeMessageResponse, crate::runtime::DispatchError> {
    let v: Value = match serde_json::from_str(&body) {
        Ok(v) => v,
        Err(e) => return Err(crate::runtime::DispatchError::Transport(format!("failed to decode response body as JSON: {e}"))),
    };
    match iface_messages__create_short_code_message_response__from_json(&v) {
        Some(x) => Ok(x),
        None => Err(crate::runtime::DispatchError::Transport("response body did not match the expected schema".to_string())),
    }
}

fn iface_messages__create_short_code_message__err(e: crate::runtime::DispatchError) -> String {
    match e {
        crate::runtime::DispatchError::Http { status, body } => format!("HTTP {status}: {body}"),
        crate::runtime::DispatchError::Transport(m) => m,
    }
}

fn iface_messages__retrieve_message__ok(body: String) -> Result<iface_messages::RetrieveMessageResponse, crate::runtime::DispatchError> {
    let v: Value = match serde_json::from_str(&body) {
        Ok(v) => v,
        Err(e) => return Err(crate::runtime::DispatchError::Transport(format!("failed to decode response body as JSON: {e}"))),
    };
    match iface_messages__retrieve_message_response__from_json(&v) {
        Some(x) => Ok(x),
        None => Err(crate::runtime::DispatchError::Transport("response body did not match the expected schema".to_string())),
    }
}

fn iface_messages__retrieve_message__err(e: crate::runtime::DispatchError) -> String {
    match e {
        crate::runtime::DispatchError::Http { status, body } => format!("HTTP {status}: {body}"),
        crate::runtime::DispatchError::Transport(m) => m,
    }
}

impl iface_messages::Guest for crate::Component {
    fn create_message(params: iface_messages::CreateMessageParams) -> Result<iface_messages::CreateMessageResponse, String> {
        let json = iface_messages__create_message_params__to_json(&params);
        match dispatch(&OP_MESSAGES_CREATE_MESSAGE, json).and_then(iface_messages__create_message__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_messages__create_message__err(e)),
        }
    }
    fn create_long_code_message(params: iface_messages::CreateLongCodeMessageParams) -> Result<iface_messages::CreateLongCodeMessageResponse, String> {
        let json = iface_messages__create_long_code_message_params__to_json(&params);
        match dispatch(&OP_MESSAGES_CREATE_LONG_CODE_MESSAGE, json).and_then(iface_messages__create_long_code_message__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_messages__create_long_code_message__err(e)),
        }
    }
    fn create_number_pool_message(params: iface_messages::CreateNumberPoolMessageParams) -> Result<iface_messages::CreateNumberPoolMessageResponse, String> {
        let json = iface_messages__create_number_pool_message_params__to_json(&params);
        match dispatch(&OP_MESSAGES_CREATE_NUMBER_POOL_MESSAGE, json).and_then(iface_messages__create_number_pool_message__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_messages__create_number_pool_message__err(e)),
        }
    }
    fn create_short_code_message(params: iface_messages::CreateShortCodeMessageParams) -> Result<iface_messages::CreateShortCodeMessageResponse, String> {
        let json = iface_messages__create_short_code_message_params__to_json(&params);
        match dispatch(&OP_MESSAGES_CREATE_SHORT_CODE_MESSAGE, json).and_then(iface_messages__create_short_code_message__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_messages__create_short_code_message__err(e)),
        }
    }
    fn retrieve_message(params: iface_messages::RetrieveMessageParams) -> Result<iface_messages::RetrieveMessageResponse, String> {
        let json = iface_messages__retrieve_message_params__to_json(&params);
        match dispatch(&OP_MESSAGES_RETRIEVE_MESSAGE, json).and_then(iface_messages__retrieve_message__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_messages__retrieve_message__err(e)),
        }
    }
}
