// AUTOGENERATED by openapi-bindgen. Do not edit by hand.

use crate::runtime::{dispatch, AuthApply, AuthKind, FieldLocation, FieldSpec, OpSpec};
use crate::exports::autostamp::box_api::invites as iface_invites;
use serde_json::{Map, Value};

const OP_INVITES_POST_INVITES: OpSpec = OpSpec {
    method: "POST",
    path_template: "/invites",
    fields: &[
        FieldSpec { snake: "fields", wire: "fields", location: FieldLocation::Query },
        FieldSpec { snake: "actionable_by", wire: "actionable_by", location: FieldLocation::Body },
        FieldSpec { snake: "enterprise", wire: "enterprise", location: FieldLocation::Body },
    ],
    auth: &[
        AuthApply { secret_key: "OAuth2Security", kind: AuthKind::Bearer },
    ],
};

const OP_INVITES_GET_INVITES_ID: OpSpec = OpSpec {
    method: "GET",
    path_template: "/invites/{invite_id}",
    fields: &[
        FieldSpec { snake: "invite_id", wire: "invite_id", location: FieldLocation::Path },
        FieldSpec { snake: "fields", wire: "fields", location: FieldLocation::Query },
    ],
    auth: &[
        AuthApply { secret_key: "OAuth2Security", kind: AuthKind::Bearer },
    ],
};

fn iface_invites__invite_invited_to_type_op_enum__to_str(e: &iface_invites::InviteInvitedToTypeOpEnum) -> &'static str {
    match e {
        iface_invites::InviteInvitedToTypeOpEnum::Enterprise => "enterprise",
    }
}

fn iface_invites__invite_type_op_enum__to_str(e: &iface_invites::InviteTypeOpEnum) -> &'static str {
    match e {
        iface_invites::InviteTypeOpEnum::Invite => "invite",
    }
}

fn iface_invites__post_invites_body_actionable_by__to_json(p: &iface_invites::PostInvitesBodyActionableBy) -> Value {
    let mut m = Map::new();
    m.insert("login".into(), match (&p.login) { Some(v) => Value::String((v).clone()), None => Value::Null });
    Value::Object(m)
}

fn iface_invites__post_invites_body_enterprise__to_json(p: &iface_invites::PostInvitesBodyEnterprise) -> Value {
    let mut m = Map::new();
    m.insert("id".into(), Value::String((&p.id).clone()));
    Value::Object(m)
}

fn iface_invites__invite__to_json(p: &iface_invites::Invite) -> Value {
    let mut m = Map::new();
    m.insert("actionable_by".into(), match (&p.actionable_by) { Some(v) => iface_invites__user_mini__to_json(v), None => Value::Null });
    m.insert("created_at".into(), match (&p.created_at) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("id".into(), match (&p.id) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("invited_by".into(), match (&p.invited_by) { Some(v) => iface_invites__user_mini__to_json(v), None => Value::Null });
    m.insert("invited_to".into(), match (&p.invited_to) { Some(v) => iface_invites__invite_invited_to__to_json(v), None => Value::Null });
    m.insert("modified_at".into(), match (&p.modified_at) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("status".into(), match (&p.status) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("type".into(), match (&p.type_op) { Some(v) => Value::String(iface_invites__invite_type_op_enum__to_str(v).into()), None => Value::Null });
    Value::Object(m)
}

fn iface_invites__user_mini__to_json(p: &iface_invites::UserMini) -> Value {
    let mut m = Map::new();
    m.insert("data".into(), match (&p.data) { Some(v) => Value::String((v).clone()), None => Value::Null });
    Value::Object(m)
}

fn iface_invites__invite_invited_to__to_json(p: &iface_invites::InviteInvitedTo) -> Value {
    let mut m = Map::new();
    m.insert("id".into(), match (&p.id) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("name".into(), match (&p.name) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("type".into(), match (&p.type_op) { Some(v) => Value::String(iface_invites__invite_invited_to_type_op_enum__to_str(v).into()), None => Value::Null });
    Value::Object(m)
}

fn iface_invites__post_invites_params__to_json(p: &iface_invites::PostInvitesParams) -> Value {
    let mut m = Map::new();
    m.insert("fields".into(), match (&p.fields) { Some(v) => Value::Array((v).iter().map(|v| Value::String((v).clone())).collect()), None => Value::Null });
    m.insert("actionable_by".into(), iface_invites__post_invites_body_actionable_by__to_json(&p.actionable_by));
    m.insert("enterprise".into(), iface_invites__post_invites_body_enterprise__to_json(&p.enterprise));
    Value::Object(m)
}

fn iface_invites__get_invites_id_params__to_json(p: &iface_invites::GetInvitesIdParams) -> Value {
    let mut m = Map::new();
    m.insert("invite_id".into(), Value::String((&p.invite_id).clone()));
    m.insert("fields".into(), match (&p.fields) { Some(v) => Value::Array((v).iter().map(|v| Value::String((v).clone())).collect()), None => Value::Null });
    Value::Object(m)
}

fn iface_invites__invite__from_json(v: &Value) -> Option<iface_invites::Invite> {
    let m = v.as_object()?;
    Some(iface_invites::Invite {
        actionable_by: m.get("actionable_by").filter(|v| !v.is_null()).and_then(|v| iface_invites__user_mini__from_json(v)),
        created_at: m.get("created_at").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        id: m.get("id").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        invited_by: m.get("invited_by").filter(|v| !v.is_null()).and_then(|v| iface_invites__user_mini__from_json(v)),
        invited_to: m.get("invited_to").filter(|v| !v.is_null()).and_then(|v| iface_invites__invite_invited_to__from_json(v)),
        modified_at: m.get("modified_at").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        status: m.get("status").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        type_op: m.get("type").filter(|v| !v.is_null()).and_then(|v| (v).as_str().and_then(iface_invites__invite_type_op_enum__from_str)),
    })
}

fn iface_invites__user_mini__from_json(v: &Value) -> Option<iface_invites::UserMini> {
    let m = v.as_object()?;
    Some(iface_invites::UserMini {
        data: m.get("data").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
    })
}

fn iface_invites__invite_invited_to__from_json(v: &Value) -> Option<iface_invites::InviteInvitedTo> {
    let m = v.as_object()?;
    Some(iface_invites::InviteInvitedTo {
        id: m.get("id").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        name: m.get("name").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        type_op: m.get("type").filter(|v| !v.is_null()).and_then(|v| (v).as_str().and_then(iface_invites__invite_invited_to_type_op_enum__from_str)),
    })
}

fn iface_invites__invite_invited_to_type_op_enum__from_str(s: &str) -> Option<iface_invites::InviteInvitedToTypeOpEnum> {
    match s {
        "enterprise" => Some(iface_invites::InviteInvitedToTypeOpEnum::Enterprise),
        _ => None,
    }
}

fn iface_invites__invite_type_op_enum__from_str(s: &str) -> Option<iface_invites::InviteTypeOpEnum> {
    match s {
        "invite" => Some(iface_invites::InviteTypeOpEnum::Invite),
        _ => None,
    }
}

fn iface_invites__post_invites__ok(body: String) -> Result<iface_invites::Invite, crate::runtime::DispatchError> {
    let v: Value = match serde_json::from_str(&body) {
        Ok(v) => v,
        Err(e) => return Err(crate::runtime::DispatchError::Transport(format!("failed to decode response body as JSON: {e}"))),
    };
    match iface_invites__invite__from_json(&v) {
        Some(x) => Ok(x),
        None => Err(crate::runtime::DispatchError::Transport("response body did not match the expected schema".to_string())),
    }
}

fn iface_invites__post_invites__err(e: crate::runtime::DispatchError) -> String {
    match e {
        crate::runtime::DispatchError::Http { status, body } => format!("HTTP {status}: {body}"),
        crate::runtime::DispatchError::Transport(m) => m,
    }
}

fn iface_invites__get_invites_id__ok(body: String) -> Result<iface_invites::Invite, crate::runtime::DispatchError> {
    let v: Value = match serde_json::from_str(&body) {
        Ok(v) => v,
        Err(e) => return Err(crate::runtime::DispatchError::Transport(format!("failed to decode response body as JSON: {e}"))),
    };
    match iface_invites__invite__from_json(&v) {
        Some(x) => Ok(x),
        None => Err(crate::runtime::DispatchError::Transport("response body did not match the expected schema".to_string())),
    }
}

fn iface_invites__get_invites_id__err(e: crate::runtime::DispatchError) -> String {
    match e {
        crate::runtime::DispatchError::Http { status, body } => format!("HTTP {status}: {body}"),
        crate::runtime::DispatchError::Transport(m) => m,
    }
}

impl iface_invites::Guest for crate::Component {
    fn post_invites(params: iface_invites::PostInvitesParams) -> Result<iface_invites::Invite, String> {
        let json = iface_invites__post_invites_params__to_json(&params);
        match dispatch(&OP_INVITES_POST_INVITES, json).and_then(iface_invites__post_invites__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_invites__post_invites__err(e)),
        }
    }
    fn get_invites_id(params: iface_invites::GetInvitesIdParams) -> Result<iface_invites::Invite, String> {
        let json = iface_invites__get_invites_id_params__to_json(&params);
        match dispatch(&OP_INVITES_GET_INVITES_ID, json).and_then(iface_invites__get_invites_id__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_invites__get_invites_id__err(e)),
        }
    }
}
