// AUTOGENERATED by openapi-bindgen. Do not edit by hand.

use crate::runtime::{dispatch, AuthApply, AuthKind, FieldLocation, FieldSpec, OpSpec};
use crate::exports::autostamp::medium::search as iface_search;
use serde_json::{Map, Value};

const OP_SEARCH_GET_SEARCH_ARTICLES_QUERY_QUERY: OpSpec = OpSpec {
    method: "GET",
    path_template: "/search/articles?query={query}",
    fields: &[
        FieldSpec { snake: "query", wire: "query", location: FieldLocation::Query },
    ],
    auth: &[
    ],
};

const OP_SEARCH_GET_SEARCH_LISTS_QUERY_QUERY: OpSpec = OpSpec {
    method: "GET",
    path_template: "/search/lists?query={query}",
    fields: &[
        FieldSpec { snake: "query", wire: "query", location: FieldLocation::Query },
    ],
    auth: &[
    ],
};

const OP_SEARCH_GET_SEARCH_PUBLICATIONS_QUERY_QUERY: OpSpec = OpSpec {
    method: "GET",
    path_template: "/search/publications?query={query}",
    fields: &[
        FieldSpec { snake: "query", wire: "query", location: FieldLocation::Query },
    ],
    auth: &[
    ],
};

const OP_SEARCH_GET_SEARCH_TAGS_QUERY_QUERY: OpSpec = OpSpec {
    method: "GET",
    path_template: "/search/tags?query={query}",
    fields: &[
        FieldSpec { snake: "query", wire: "query", location: FieldLocation::Query },
    ],
    auth: &[
    ],
};

const OP_SEARCH_GET_SEARCH_USERS_QUERY_QUERY: OpSpec = OpSpec {
    method: "GET",
    path_template: "/search/users?query={query}",
    fields: &[
        FieldSpec { snake: "query", wire: "query", location: FieldLocation::Query },
    ],
    auth: &[
    ],
};

fn iface_search__get_search_articles_query_query_response__to_json(p: &iface_search::GetSearchArticlesQueryQueryResponse) -> Value {
    let mut m = Map::new();
    m.insert("articles".into(), match (&p.articles) { Some(v) => Value::Array((v).iter().map(|v| Value::String((v).clone())).collect()), None => Value::Null });
    m.insert("search_query".into(), match (&p.search_query) { Some(v) => Value::String((v).clone()), None => Value::Null });
    Value::Object(m)
}

fn iface_search__get_search_lists_query_query_response__to_json(p: &iface_search::GetSearchListsQueryQueryResponse) -> Value {
    let mut m = Map::new();
    m.insert("lists".into(), match (&p.lists) { Some(v) => Value::Array((v).iter().map(|v| Value::String((v).clone())).collect()), None => Value::Null });
    m.insert("search_query".into(), match (&p.search_query) { Some(v) => Value::String((v).clone()), None => Value::Null });
    Value::Object(m)
}

fn iface_search__get_search_publications_query_query_response__to_json(p: &iface_search::GetSearchPublicationsQueryQueryResponse) -> Value {
    let mut m = Map::new();
    m.insert("publications".into(), match (&p.publications) { Some(v) => Value::Array((v).iter().map(|v| Value::String((v).clone())).collect()), None => Value::Null });
    m.insert("search_query".into(), match (&p.search_query) { Some(v) => Value::String((v).clone()), None => Value::Null });
    Value::Object(m)
}

fn iface_search__get_search_tags_query_query_response__to_json(p: &iface_search::GetSearchTagsQueryQueryResponse) -> Value {
    let mut m = Map::new();
    m.insert("search_query".into(), match (&p.search_query) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("tags".into(), match (&p.tags) { Some(v) => Value::Array((v).iter().map(|v| Value::String((v).clone())).collect()), None => Value::Null });
    Value::Object(m)
}

fn iface_search__get_search_users_query_query_response__to_json(p: &iface_search::GetSearchUsersQueryQueryResponse) -> Value {
    let mut m = Map::new();
    m.insert("search_query".into(), match (&p.search_query) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("users".into(), match (&p.users) { Some(v) => Value::Array((v).iter().map(|v| Value::String((v).clone())).collect()), None => Value::Null });
    Value::Object(m)
}

fn iface_search__get_search_articles_query_query_params__to_json(p: &iface_search::GetSearchArticlesQueryQueryParams) -> Value {
    let mut m = Map::new();
    m.insert("query".into(), Value::String((&p.query).clone()));
    Value::Object(m)
}

fn iface_search__get_search_lists_query_query_params__to_json(p: &iface_search::GetSearchListsQueryQueryParams) -> Value {
    let mut m = Map::new();
    m.insert("query".into(), Value::String((&p.query).clone()));
    Value::Object(m)
}

fn iface_search__get_search_publications_query_query_params__to_json(p: &iface_search::GetSearchPublicationsQueryQueryParams) -> Value {
    let mut m = Map::new();
    m.insert("query".into(), Value::String((&p.query).clone()));
    Value::Object(m)
}

fn iface_search__get_search_tags_query_query_params__to_json(p: &iface_search::GetSearchTagsQueryQueryParams) -> Value {
    let mut m = Map::new();
    m.insert("query".into(), Value::String((&p.query).clone()));
    Value::Object(m)
}

fn iface_search__get_search_users_query_query_params__to_json(p: &iface_search::GetSearchUsersQueryQueryParams) -> Value {
    let mut m = Map::new();
    m.insert("query".into(), Value::String((&p.query).clone()));
    Value::Object(m)
}

fn iface_search__get_search_articles_query_query_response__from_json(v: &Value) -> Option<iface_search::GetSearchArticlesQueryQueryResponse> {
    let m = v.as_object()?;
    Some(iface_search::GetSearchArticlesQueryQueryResponse {
        articles: m.get("articles").filter(|v| !v.is_null()).and_then(|v| (v).as_array().map(|a| a.iter().filter_map(|x| (x).as_str().map(|s| s.to_string())).collect())),
        search_query: m.get("search_query").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
    })
}

fn iface_search__get_search_lists_query_query_response__from_json(v: &Value) -> Option<iface_search::GetSearchListsQueryQueryResponse> {
    let m = v.as_object()?;
    Some(iface_search::GetSearchListsQueryQueryResponse {
        lists: m.get("lists").filter(|v| !v.is_null()).and_then(|v| (v).as_array().map(|a| a.iter().filter_map(|x| (x).as_str().map(|s| s.to_string())).collect())),
        search_query: m.get("search_query").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
    })
}

fn iface_search__get_search_publications_query_query_response__from_json(v: &Value) -> Option<iface_search::GetSearchPublicationsQueryQueryResponse> {
    let m = v.as_object()?;
    Some(iface_search::GetSearchPublicationsQueryQueryResponse {
        publications: m.get("publications").filter(|v| !v.is_null()).and_then(|v| (v).as_array().map(|a| a.iter().filter_map(|x| (x).as_str().map(|s| s.to_string())).collect())),
        search_query: m.get("search_query").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
    })
}

fn iface_search__get_search_tags_query_query_response__from_json(v: &Value) -> Option<iface_search::GetSearchTagsQueryQueryResponse> {
    let m = v.as_object()?;
    Some(iface_search::GetSearchTagsQueryQueryResponse {
        search_query: m.get("search_query").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        tags: m.get("tags").filter(|v| !v.is_null()).and_then(|v| (v).as_array().map(|a| a.iter().filter_map(|x| (x).as_str().map(|s| s.to_string())).collect())),
    })
}

fn iface_search__get_search_users_query_query_response__from_json(v: &Value) -> Option<iface_search::GetSearchUsersQueryQueryResponse> {
    let m = v.as_object()?;
    Some(iface_search::GetSearchUsersQueryQueryResponse {
        search_query: m.get("search_query").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        users: m.get("users").filter(|v| !v.is_null()).and_then(|v| (v).as_array().map(|a| a.iter().filter_map(|x| (x).as_str().map(|s| s.to_string())).collect())),
    })
}

fn iface_search__get_search_articles_query_query__ok(body: String) -> Result<iface_search::GetSearchArticlesQueryQueryResponse, crate::runtime::DispatchError> {
    let v: Value = match serde_json::from_str(&body) {
        Ok(v) => v,
        Err(e) => return Err(crate::runtime::DispatchError::Transport(format!("failed to decode response body as JSON: {e}"))),
    };
    match iface_search__get_search_articles_query_query_response__from_json(&v) {
        Some(x) => Ok(x),
        None => Err(crate::runtime::DispatchError::Transport("response body did not match the expected schema".to_string())),
    }
}

fn iface_search__get_search_articles_query_query__err(e: crate::runtime::DispatchError) -> String {
    match e {
        crate::runtime::DispatchError::Http { status, body } => format!("HTTP {status}: {body}"),
        crate::runtime::DispatchError::Transport(m) => m,
    }
}

fn iface_search__get_search_lists_query_query__ok(body: String) -> Result<iface_search::GetSearchListsQueryQueryResponse, crate::runtime::DispatchError> {
    let v: Value = match serde_json::from_str(&body) {
        Ok(v) => v,
        Err(e) => return Err(crate::runtime::DispatchError::Transport(format!("failed to decode response body as JSON: {e}"))),
    };
    match iface_search__get_search_lists_query_query_response__from_json(&v) {
        Some(x) => Ok(x),
        None => Err(crate::runtime::DispatchError::Transport("response body did not match the expected schema".to_string())),
    }
}

fn iface_search__get_search_lists_query_query__err(e: crate::runtime::DispatchError) -> String {
    match e {
        crate::runtime::DispatchError::Http { status, body } => format!("HTTP {status}: {body}"),
        crate::runtime::DispatchError::Transport(m) => m,
    }
}

fn iface_search__get_search_publications_query_query__ok(body: String) -> Result<iface_search::GetSearchPublicationsQueryQueryResponse, crate::runtime::DispatchError> {
    let v: Value = match serde_json::from_str(&body) {
        Ok(v) => v,
        Err(e) => return Err(crate::runtime::DispatchError::Transport(format!("failed to decode response body as JSON: {e}"))),
    };
    match iface_search__get_search_publications_query_query_response__from_json(&v) {
        Some(x) => Ok(x),
        None => Err(crate::runtime::DispatchError::Transport("response body did not match the expected schema".to_string())),
    }
}

fn iface_search__get_search_publications_query_query__err(e: crate::runtime::DispatchError) -> String {
    match e {
        crate::runtime::DispatchError::Http { status, body } => format!("HTTP {status}: {body}"),
        crate::runtime::DispatchError::Transport(m) => m,
    }
}

fn iface_search__get_search_tags_query_query__ok(body: String) -> Result<iface_search::GetSearchTagsQueryQueryResponse, crate::runtime::DispatchError> {
    let v: Value = match serde_json::from_str(&body) {
        Ok(v) => v,
        Err(e) => return Err(crate::runtime::DispatchError::Transport(format!("failed to decode response body as JSON: {e}"))),
    };
    match iface_search__get_search_tags_query_query_response__from_json(&v) {
        Some(x) => Ok(x),
        None => Err(crate::runtime::DispatchError::Transport("response body did not match the expected schema".to_string())),
    }
}

fn iface_search__get_search_tags_query_query__err(e: crate::runtime::DispatchError) -> String {
    match e {
        crate::runtime::DispatchError::Http { status, body } => format!("HTTP {status}: {body}"),
        crate::runtime::DispatchError::Transport(m) => m,
    }
}

fn iface_search__get_search_users_query_query__ok(body: String) -> Result<iface_search::GetSearchUsersQueryQueryResponse, crate::runtime::DispatchError> {
    let v: Value = match serde_json::from_str(&body) {
        Ok(v) => v,
        Err(e) => return Err(crate::runtime::DispatchError::Transport(format!("failed to decode response body as JSON: {e}"))),
    };
    match iface_search__get_search_users_query_query_response__from_json(&v) {
        Some(x) => Ok(x),
        None => Err(crate::runtime::DispatchError::Transport("response body did not match the expected schema".to_string())),
    }
}

fn iface_search__get_search_users_query_query__err(e: crate::runtime::DispatchError) -> String {
    match e {
        crate::runtime::DispatchError::Http { status, body } => format!("HTTP {status}: {body}"),
        crate::runtime::DispatchError::Transport(m) => m,
    }
}

impl iface_search::Guest for crate::Component {
    fn get_search_articles_query_query(params: iface_search::GetSearchArticlesQueryQueryParams) -> Result<iface_search::GetSearchArticlesQueryQueryResponse, String> {
        let json = iface_search__get_search_articles_query_query_params__to_json(&params);
        match dispatch(&OP_SEARCH_GET_SEARCH_ARTICLES_QUERY_QUERY, json).and_then(iface_search__get_search_articles_query_query__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_search__get_search_articles_query_query__err(e)),
        }
    }
    fn get_search_lists_query_query(params: iface_search::GetSearchListsQueryQueryParams) -> Result<iface_search::GetSearchListsQueryQueryResponse, String> {
        let json = iface_search__get_search_lists_query_query_params__to_json(&params);
        match dispatch(&OP_SEARCH_GET_SEARCH_LISTS_QUERY_QUERY, json).and_then(iface_search__get_search_lists_query_query__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_search__get_search_lists_query_query__err(e)),
        }
    }
    fn get_search_publications_query_query(params: iface_search::GetSearchPublicationsQueryQueryParams) -> Result<iface_search::GetSearchPublicationsQueryQueryResponse, String> {
        let json = iface_search__get_search_publications_query_query_params__to_json(&params);
        match dispatch(&OP_SEARCH_GET_SEARCH_PUBLICATIONS_QUERY_QUERY, json).and_then(iface_search__get_search_publications_query_query__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_search__get_search_publications_query_query__err(e)),
        }
    }
    fn get_search_tags_query_query(params: iface_search::GetSearchTagsQueryQueryParams) -> Result<iface_search::GetSearchTagsQueryQueryResponse, String> {
        let json = iface_search__get_search_tags_query_query_params__to_json(&params);
        match dispatch(&OP_SEARCH_GET_SEARCH_TAGS_QUERY_QUERY, json).and_then(iface_search__get_search_tags_query_query__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_search__get_search_tags_query_query__err(e)),
        }
    }
    fn get_search_users_query_query(params: iface_search::GetSearchUsersQueryQueryParams) -> Result<iface_search::GetSearchUsersQueryQueryResponse, String> {
        let json = iface_search__get_search_users_query_query_params__to_json(&params);
        match dispatch(&OP_SEARCH_GET_SEARCH_USERS_QUERY_QUERY, json).and_then(iface_search__get_search_users_query_query__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_search__get_search_users_query_query__err(e)),
        }
    }
}
