// AUTOGENERATED by openapi-bindgen. Do not edit by hand.

use crate::runtime::{dispatch, AuthApply, AuthKind, FieldLocation, FieldSpec, OpSpec};
use crate::exports::autostamp::meilisearch::stats as iface_stats;
use serde_json::{Map, Value};

const OP_STATS_HEALTH: OpSpec = OpSpec {
    method: "GET",
    path_template: "/health",
    fields: &[
    ],
    auth: &[
    ],
};

const OP_STATS_OF_AN_INDEX: OpSpec = OpSpec {
    method: "GET",
    path_template: "/indexes/books/stats",
    fields: &[
    ],
    auth: &[
    ],
};

const OP_STATS_GLOBAL_STATS: OpSpec = OpSpec {
    method: "GET",
    path_template: "/stats",
    fields: &[
    ],
    auth: &[
    ],
};

const OP_STATS_VERSION: OpSpec = OpSpec {
    method: "GET",
    path_template: "/version",
    fields: &[
    ],
    auth: &[
    ],
};

fn iface_stats__health__ok(body: String) -> Result<String, crate::runtime::DispatchError> {
    Ok(body)
}

fn iface_stats__health__err(e: crate::runtime::DispatchError) -> String {
    match e {
        crate::runtime::DispatchError::Http { status, body } => format!("HTTP {status}: {body}"),
        crate::runtime::DispatchError::Transport(m) => m,
    }
}

fn iface_stats__of_an_index__ok(body: String) -> Result<String, crate::runtime::DispatchError> {
    Ok(body)
}

fn iface_stats__of_an_index__err(e: crate::runtime::DispatchError) -> String {
    match e {
        crate::runtime::DispatchError::Http { status, body } => format!("HTTP {status}: {body}"),
        crate::runtime::DispatchError::Transport(m) => m,
    }
}

fn iface_stats__global_stats__ok(body: String) -> Result<String, crate::runtime::DispatchError> {
    Ok(body)
}

fn iface_stats__global_stats__err(e: crate::runtime::DispatchError) -> String {
    match e {
        crate::runtime::DispatchError::Http { status, body } => format!("HTTP {status}: {body}"),
        crate::runtime::DispatchError::Transport(m) => m,
    }
}

fn iface_stats__version__ok(body: String) -> Result<String, crate::runtime::DispatchError> {
    Ok(body)
}

fn iface_stats__version__err(e: crate::runtime::DispatchError) -> String {
    match e {
        crate::runtime::DispatchError::Http { status, body } => format!("HTTP {status}: {body}"),
        crate::runtime::DispatchError::Transport(m) => m,
    }
}

impl iface_stats::Guest for crate::Component {
    fn health() -> Result<String, String> {
        match dispatch(&OP_STATS_HEALTH, Value::Object(Map::new())).and_then(iface_stats__health__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_stats__health__err(e)),
        }
    }
    fn of_an_index() -> Result<String, String> {
        match dispatch(&OP_STATS_OF_AN_INDEX, Value::Object(Map::new())).and_then(iface_stats__of_an_index__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_stats__of_an_index__err(e)),
        }
    }
    fn global_stats() -> Result<String, String> {
        match dispatch(&OP_STATS_GLOBAL_STATS, Value::Object(Map::new())).and_then(iface_stats__global_stats__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_stats__global_stats__err(e)),
        }
    }
    fn version() -> Result<String, String> {
        match dispatch(&OP_STATS_VERSION, Value::Object(Map::new())).and_then(iface_stats__version__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_stats__version__err(e)),
        }
    }
}
