// AUTOGENERATED by openapi-bindgen. Do not edit by hand.

use crate::runtime::{dispatch, AuthApply, AuthKind, FieldLocation, FieldSpec, OpSpec};
use crate::exports::autostamp::getpostman::user as iface_user;
use serde_json::{Map, Value};

const OP_USER_API_KEY_OWNER: OpSpec = OpSpec {
    method: "GET",
    path_template: "/me",
    fields: &[
    ],
    auth: &[
    ],
};

fn iface_user__api_key_owner_response__to_json(p: &iface_user::ApiKeyOwnerResponse) -> Value {
    let mut m = Map::new();
    m.insert("operations".into(), match (&p.operations) { Some(v) => Value::Array((v).iter().map(|v| iface_user__api_key_owner_response_operations_item__to_json(v)).collect()), None => Value::Null });
    m.insert("user".into(), match (&p.user) { Some(v) => iface_user__api_key_owner_response_user__to_json(v), None => Value::Null });
    Value::Object(m)
}

fn iface_user__api_key_owner_response_operations_item__to_json(p: &iface_user::ApiKeyOwnerResponseOperationsItem) -> Value {
    let mut m = Map::new();
    m.insert("limit".into(), match (&p.limit) { Some(v) => serde_json::Number::from_f64(*(v)).map(Value::Number).unwrap_or(Value::Null), None => Value::Null });
    m.insert("name".into(), match (&p.name) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("overage".into(), match (&p.overage) { Some(v) => serde_json::Number::from_f64(*(v)).map(Value::Number).unwrap_or(Value::Null), None => Value::Null });
    m.insert("usage".into(), match (&p.usage) { Some(v) => serde_json::Number::from_f64(*(v)).map(Value::Number).unwrap_or(Value::Null), None => Value::Null });
    Value::Object(m)
}

fn iface_user__api_key_owner_response_user__to_json(p: &iface_user::ApiKeyOwnerResponseUser) -> Value {
    let mut m = Map::new();
    m.insert("avatar".into(), match (&p.avatar) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("email".into(), match (&p.email) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("fullName".into(), match (&p.full_name) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("id".into(), match (&p.id) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("isPublic".into(), match (&p.is_public) { Some(v) => Value::Bool(*(v)), None => Value::Null });
    m.insert("username".into(), match (&p.username) { Some(v) => Value::String((v).clone()), None => Value::Null });
    Value::Object(m)
}

fn iface_user__api_key_owner_response__from_json(v: &Value) -> Option<iface_user::ApiKeyOwnerResponse> {
    let m = v.as_object()?;
    Some(iface_user::ApiKeyOwnerResponse {
        operations: m.get("operations").filter(|v| !v.is_null()).and_then(|v| (v).as_array().map(|a| a.iter().filter_map(|x| iface_user__api_key_owner_response_operations_item__from_json(x)).collect())),
        user: m.get("user").filter(|v| !v.is_null()).and_then(|v| iface_user__api_key_owner_response_user__from_json(v)),
    })
}

fn iface_user__api_key_owner_response_operations_item__from_json(v: &Value) -> Option<iface_user::ApiKeyOwnerResponseOperationsItem> {
    let m = v.as_object()?;
    Some(iface_user::ApiKeyOwnerResponseOperationsItem {
        limit: m.get("limit").filter(|v| !v.is_null()).and_then(|v| (v).as_f64()),
        name: m.get("name").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        overage: m.get("overage").filter(|v| !v.is_null()).and_then(|v| (v).as_f64()),
        usage: m.get("usage").filter(|v| !v.is_null()).and_then(|v| (v).as_f64()),
    })
}

fn iface_user__api_key_owner_response_user__from_json(v: &Value) -> Option<iface_user::ApiKeyOwnerResponseUser> {
    let m = v.as_object()?;
    Some(iface_user::ApiKeyOwnerResponseUser {
        avatar: m.get("avatar").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        email: m.get("email").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        full_name: m.get("fullName").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        id: m.get("id").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        is_public: m.get("isPublic").filter(|v| !v.is_null()).and_then(|v| (v).as_bool()),
        username: m.get("username").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
    })
}

fn iface_user__api_key_owner__ok(body: String) -> Result<iface_user::ApiKeyOwnerResponse, crate::runtime::DispatchError> {
    let v: Value = match serde_json::from_str(&body) {
        Ok(v) => v,
        Err(e) => return Err(crate::runtime::DispatchError::Transport(format!("failed to decode response body as JSON: {e}"))),
    };
    match iface_user__api_key_owner_response__from_json(&v) {
        Some(x) => Ok(x),
        None => Err(crate::runtime::DispatchError::Transport("response body did not match the expected schema".to_string())),
    }
}

fn iface_user__api_key_owner__err(e: crate::runtime::DispatchError) -> String {
    match e {
        crate::runtime::DispatchError::Http { status, body } => format!("HTTP {status}: {body}"),
        crate::runtime::DispatchError::Transport(m) => m,
    }
}

impl iface_user::Guest for crate::Component {
    fn api_key_owner() -> Result<iface_user::ApiKeyOwnerResponse, String> {
        match dispatch(&OP_USER_API_KEY_OWNER, Value::Object(Map::new())).and_then(iface_user__api_key_owner__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_user__api_key_owner__err(e)),
        }
    }
}
