// AUTOGENERATED by openapi-bindgen. Do not edit by hand.

use crate::runtime::{dispatch, AuthApply, AuthKind, FieldLocation, FieldSpec, OpSpec};
use crate::exports::autostamp::clicksend::reseller_accounts as iface_reseller_accounts;
use serde_json::{Map, Value};

const OP_RESELLER_ACCOUNTS_LIST_OF_RESELLER_ACCOUNTS: OpSpec = OpSpec {
    method: "GET",
    path_template: "/reseller/accounts",
    fields: &[
    ],
    auth: &[
    ],
};

const OP_RESELLER_ACCOUNTS_CREATE_RESELLER_ACCOUNT: OpSpec = OpSpec {
    method: "POST",
    path_template: "/reseller/accounts",
    fields: &[
        FieldSpec { snake: "account_name", wire: "account_name", location: FieldLocation::Body },
        FieldSpec { snake: "country", wire: "country", location: FieldLocation::Body },
        FieldSpec { snake: "password", wire: "password", location: FieldLocation::Body },
        FieldSpec { snake: "user_email", wire: "user_email", location: FieldLocation::Body },
        FieldSpec { snake: "user_first_name", wire: "user_first_name", location: FieldLocation::Body },
        FieldSpec { snake: "user_last_name", wire: "user_last_name", location: FieldLocation::Body },
        FieldSpec { snake: "user_phone", wire: "user_phone", location: FieldLocation::Body },
        FieldSpec { snake: "username", wire: "username", location: FieldLocation::Body },
    ],
    auth: &[
    ],
};

const OP_RESELLER_ACCOUNTS_CREATE_RESELLER_ACCOUNT_PUBLIC: OpSpec = OpSpec {
    method: "POST",
    path_template: "/reseller/accounts-public",
    fields: &[
        FieldSpec { snake: "account_name", wire: "account_name", location: FieldLocation::Body },
        FieldSpec { snake: "country", wire: "country", location: FieldLocation::Body },
        FieldSpec { snake: "password", wire: "password", location: FieldLocation::Body },
        FieldSpec { snake: "reseller_user_id", wire: "reseller_user_id", location: FieldLocation::Body },
        FieldSpec { snake: "user_email", wire: "user_email", location: FieldLocation::Body },
        FieldSpec { snake: "user_first_name", wire: "user_first_name", location: FieldLocation::Body },
        FieldSpec { snake: "user_last_name", wire: "user_last_name", location: FieldLocation::Body },
        FieldSpec { snake: "user_phone", wire: "user_phone", location: FieldLocation::Body },
        FieldSpec { snake: "username", wire: "username", location: FieldLocation::Body },
    ],
    auth: &[
    ],
};

const OP_RESELLER_ACCOUNTS_GET_RESELLER_ACCOUNT: OpSpec = OpSpec {
    method: "GET",
    path_template: "/reseller/accounts/{client_user_id}",
    fields: &[
        FieldSpec { snake: "client_user_id", wire: "client_user_id", location: FieldLocation::Path },
    ],
    auth: &[
    ],
};

const OP_RESELLER_ACCOUNTS_UPDATE_RESELLER_ACCOUNT: OpSpec = OpSpec {
    method: "PUT",
    path_template: "/reseller/accounts/{client_user_id}",
    fields: &[
        FieldSpec { snake: "client_user_id", wire: "client_user_id", location: FieldLocation::Path },
        FieldSpec { snake: "account_name", wire: "account_name", location: FieldLocation::Body },
        FieldSpec { snake: "country", wire: "country", location: FieldLocation::Body },
        FieldSpec { snake: "password", wire: "password", location: FieldLocation::Body },
        FieldSpec { snake: "user_email", wire: "user_email", location: FieldLocation::Body },
        FieldSpec { snake: "user_first_name", wire: "user_first_name", location: FieldLocation::Body },
        FieldSpec { snake: "user_last_name", wire: "user_last_name", location: FieldLocation::Body },
        FieldSpec { snake: "user_phone", wire: "user_phone", location: FieldLocation::Body },
        FieldSpec { snake: "username", wire: "username", location: FieldLocation::Body },
    ],
    auth: &[
    ],
};

const OP_RESELLER_ACCOUNTS_TRANSFER_CREDIT: OpSpec = OpSpec {
    method: "PUT",
    path_template: "/reseller/transfer-credit",
    fields: &[
        FieldSpec { snake: "balance", wire: "balance", location: FieldLocation::Body },
        FieldSpec { snake: "client_user_id", wire: "client_user_id", location: FieldLocation::Body },
        FieldSpec { snake: "currency", wire: "currency", location: FieldLocation::Body },
    ],
    auth: &[
        AuthApply { secret_key: "basic", kind: AuthKind::Basic },
    ],
};

fn iface_reseller_accounts__create_reseller_account_params__to_json(p: &iface_reseller_accounts::CreateResellerAccountParams) -> Value {
    let mut m = Map::new();
    m.insert("account_name".into(), Value::String((&p.account_name).clone()));
    m.insert("country".into(), Value::String((&p.country).clone()));
    m.insert("password".into(), Value::String((&p.password).clone()));
    m.insert("user_email".into(), Value::String((&p.user_email).clone()));
    m.insert("user_first_name".into(), Value::String((&p.user_first_name).clone()));
    m.insert("user_last_name".into(), Value::String((&p.user_last_name).clone()));
    m.insert("user_phone".into(), Value::String((&p.user_phone).clone()));
    m.insert("username".into(), Value::String((&p.username).clone()));
    Value::Object(m)
}

fn iface_reseller_accounts__create_reseller_account_public_params__to_json(p: &iface_reseller_accounts::CreateResellerAccountPublicParams) -> Value {
    let mut m = Map::new();
    m.insert("account_name".into(), Value::String((&p.account_name).clone()));
    m.insert("country".into(), Value::String((&p.country).clone()));
    m.insert("password".into(), Value::String((&p.password).clone()));
    m.insert("reseller_user_id".into(), serde_json::Number::from_f64(*(&p.reseller_user_id)).map(Value::Number).unwrap_or(Value::Null));
    m.insert("user_email".into(), Value::String((&p.user_email).clone()));
    m.insert("user_first_name".into(), Value::String((&p.user_first_name).clone()));
    m.insert("user_last_name".into(), Value::String((&p.user_last_name).clone()));
    m.insert("user_phone".into(), Value::String((&p.user_phone).clone()));
    m.insert("username".into(), Value::String((&p.username).clone()));
    Value::Object(m)
}

fn iface_reseller_accounts__get_reseller_account_params__to_json(p: &iface_reseller_accounts::GetResellerAccountParams) -> Value {
    let mut m = Map::new();
    m.insert("client_user_id".into(), Value::String((&p.client_user_id).clone()));
    Value::Object(m)
}

fn iface_reseller_accounts__update_reseller_account_params__to_json(p: &iface_reseller_accounts::UpdateResellerAccountParams) -> Value {
    let mut m = Map::new();
    m.insert("client_user_id".into(), Value::String((&p.client_user_id).clone()));
    m.insert("account_name".into(), Value::String((&p.account_name).clone()));
    m.insert("country".into(), Value::String((&p.country).clone()));
    m.insert("password".into(), Value::String((&p.password).clone()));
    m.insert("user_email".into(), Value::String((&p.user_email).clone()));
    m.insert("user_first_name".into(), Value::String((&p.user_first_name).clone()));
    m.insert("user_last_name".into(), Value::String((&p.user_last_name).clone()));
    m.insert("user_phone".into(), Value::String((&p.user_phone).clone()));
    m.insert("username".into(), Value::String((&p.username).clone()));
    Value::Object(m)
}

fn iface_reseller_accounts__transfer_credit_params__to_json(p: &iface_reseller_accounts::TransferCreditParams) -> Value {
    let mut m = Map::new();
    m.insert("balance".into(), serde_json::Number::from_f64(*(&p.balance)).map(Value::Number).unwrap_or(Value::Null));
    m.insert("client_user_id".into(), Value::String((&p.client_user_id).clone()));
    m.insert("currency".into(), Value::String((&p.currency).clone()));
    Value::Object(m)
}

fn iface_reseller_accounts__list_of_reseller_accounts__ok(body: String) -> Result<String, crate::runtime::DispatchError> {
    Ok(body)
}

fn iface_reseller_accounts__list_of_reseller_accounts__err(e: crate::runtime::DispatchError) -> String {
    match e {
        crate::runtime::DispatchError::Http { status, body } => format!("HTTP {status}: {body}"),
        crate::runtime::DispatchError::Transport(m) => m,
    }
}

fn iface_reseller_accounts__create_reseller_account__ok(body: String) -> Result<String, crate::runtime::DispatchError> {
    Ok(body)
}

fn iface_reseller_accounts__create_reseller_account__err(e: crate::runtime::DispatchError) -> String {
    match e {
        crate::runtime::DispatchError::Http { status, body } => format!("HTTP {status}: {body}"),
        crate::runtime::DispatchError::Transport(m) => m,
    }
}

fn iface_reseller_accounts__create_reseller_account_public__ok(body: String) -> Result<String, crate::runtime::DispatchError> {
    Ok(body)
}

fn iface_reseller_accounts__create_reseller_account_public__err(e: crate::runtime::DispatchError) -> String {
    match e {
        crate::runtime::DispatchError::Http { status, body } => format!("HTTP {status}: {body}"),
        crate::runtime::DispatchError::Transport(m) => m,
    }
}

fn iface_reseller_accounts__get_reseller_account__ok(body: String) -> Result<String, crate::runtime::DispatchError> {
    Ok(body)
}

fn iface_reseller_accounts__get_reseller_account__err(e: crate::runtime::DispatchError) -> String {
    match e {
        crate::runtime::DispatchError::Http { status, body } => format!("HTTP {status}: {body}"),
        crate::runtime::DispatchError::Transport(m) => m,
    }
}

fn iface_reseller_accounts__update_reseller_account__ok(body: String) -> Result<String, crate::runtime::DispatchError> {
    Ok(body)
}

fn iface_reseller_accounts__update_reseller_account__err(e: crate::runtime::DispatchError) -> String {
    match e {
        crate::runtime::DispatchError::Http { status, body } => format!("HTTP {status}: {body}"),
        crate::runtime::DispatchError::Transport(m) => m,
    }
}

fn iface_reseller_accounts__transfer_credit__ok(body: String) -> Result<String, crate::runtime::DispatchError> {
    Ok(body)
}

fn iface_reseller_accounts__transfer_credit__err(e: crate::runtime::DispatchError) -> String {
    match e {
        crate::runtime::DispatchError::Http { status, body } => format!("HTTP {status}: {body}"),
        crate::runtime::DispatchError::Transport(m) => m,
    }
}

impl iface_reseller_accounts::Guest for crate::Component {
    fn list_of_reseller_accounts() -> Result<String, String> {
        match dispatch(&OP_RESELLER_ACCOUNTS_LIST_OF_RESELLER_ACCOUNTS, Value::Object(Map::new())).and_then(iface_reseller_accounts__list_of_reseller_accounts__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_reseller_accounts__list_of_reseller_accounts__err(e)),
        }
    }
    fn create_reseller_account(params: iface_reseller_accounts::CreateResellerAccountParams) -> Result<String, String> {
        let json = iface_reseller_accounts__create_reseller_account_params__to_json(&params);
        match dispatch(&OP_RESELLER_ACCOUNTS_CREATE_RESELLER_ACCOUNT, json).and_then(iface_reseller_accounts__create_reseller_account__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_reseller_accounts__create_reseller_account__err(e)),
        }
    }
    fn create_reseller_account_public(params: iface_reseller_accounts::CreateResellerAccountPublicParams) -> Result<String, String> {
        let json = iface_reseller_accounts__create_reseller_account_public_params__to_json(&params);
        match dispatch(&OP_RESELLER_ACCOUNTS_CREATE_RESELLER_ACCOUNT_PUBLIC, json).and_then(iface_reseller_accounts__create_reseller_account_public__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_reseller_accounts__create_reseller_account_public__err(e)),
        }
    }
    fn get_reseller_account(params: iface_reseller_accounts::GetResellerAccountParams) -> Result<String, String> {
        let json = iface_reseller_accounts__get_reseller_account_params__to_json(&params);
        match dispatch(&OP_RESELLER_ACCOUNTS_GET_RESELLER_ACCOUNT, json).and_then(iface_reseller_accounts__get_reseller_account__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_reseller_accounts__get_reseller_account__err(e)),
        }
    }
    fn update_reseller_account(params: iface_reseller_accounts::UpdateResellerAccountParams) -> Result<String, String> {
        let json = iface_reseller_accounts__update_reseller_account_params__to_json(&params);
        match dispatch(&OP_RESELLER_ACCOUNTS_UPDATE_RESELLER_ACCOUNT, json).and_then(iface_reseller_accounts__update_reseller_account__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_reseller_accounts__update_reseller_account__err(e)),
        }
    }
    fn transfer_credit(params: iface_reseller_accounts::TransferCreditParams) -> Result<String, String> {
        let json = iface_reseller_accounts__transfer_credit_params__to_json(&params);
        match dispatch(&OP_RESELLER_ACCOUNTS_TRANSFER_CREDIT, json).and_then(iface_reseller_accounts__transfer_credit__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_reseller_accounts__transfer_credit__err(e)),
        }
    }
}
