// AUTOGENERATED by openapi-bindgen. Do not edit by hand.

use crate::runtime::{dispatch, AuthApply, AuthKind, FieldLocation, FieldSpec, OpSpec};
use crate::exports::autostamp::stackexchange::apps as iface_apps;
use serde_json::{Map, Value};

const OP_APPS_GET_APPS_ACCESS_TOKENS_DE_AUTHENTICATE: OpSpec = OpSpec {
    method: "GET",
    path_template: "/apps/{access_tokens}/de-authenticate",
    fields: &[
        FieldSpec { snake: "access_tokens", wire: "accessTokens", location: FieldLocation::Path },
        FieldSpec { snake: "pagesize", wire: "pagesize", location: FieldLocation::Query },
        FieldSpec { snake: "page", wire: "page", location: FieldLocation::Query },
        FieldSpec { snake: "filter", wire: "filter", location: FieldLocation::Query },
        FieldSpec { snake: "callback", wire: "callback", location: FieldLocation::Query },
    ],
    auth: &[
    ],
};

fn iface_apps__access_tokens__to_json(p: &iface_apps::AccessTokens) -> Value {
    let mut m = Map::new();
    m.insert("value".into(), Value::String((&p.value).clone()));
    Value::Object(m)
}

fn iface_apps__get_apps_access_tokens_de_authenticate_params__to_json(p: &iface_apps::GetAppsAccessTokensDeAuthenticateParams) -> Value {
    let mut m = Map::new();
    m.insert("access_tokens".into(), Value::String((&p.access_tokens).clone()));
    m.insert("pagesize".into(), match (&p.pagesize) { Some(v) => Value::Number(serde_json::Number::from(*(v))), None => Value::Null });
    m.insert("page".into(), match (&p.page) { Some(v) => Value::Number(serde_json::Number::from(*(v))), None => Value::Null });
    m.insert("filter".into(), match (&p.filter) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("callback".into(), match (&p.callback) { Some(v) => Value::String((v).clone()), None => Value::Null });
    Value::Object(m)
}

fn iface_apps__access_tokens__from_json(v: &Value) -> Option<iface_apps::AccessTokens> {
    let m = v.as_object()?;
    Some(iface_apps::AccessTokens {
        value: m.get("value").and_then(|v| (v).as_str().map(|s| s.to_string())).unwrap_or_default(),
    })
}

fn iface_apps__get_apps_access_tokens_de_authenticate__ok(body: String) -> Result<iface_apps::AccessTokens, crate::runtime::DispatchError> {
    let v: Value = match serde_json::from_str(&body) {
        Ok(v) => v,
        Err(e) => return Err(crate::runtime::DispatchError::Transport(format!("failed to decode response body as JSON: {e}"))),
    };
    match iface_apps__access_tokens__from_json(&v) {
        Some(x) => Ok(x),
        None => Err(crate::runtime::DispatchError::Transport("response body did not match the expected schema".to_string())),
    }
}

fn iface_apps__get_apps_access_tokens_de_authenticate__err(e: crate::runtime::DispatchError) -> iface_apps::GetAppsAccessTokensDeAuthenticateError {
    match e {
        crate::runtime::DispatchError::Http { status, body } => match status {
            400u16 => iface_apps::GetAppsAccessTokensDeAuthenticateError::BadRequest(body),
            401u16 => iface_apps::GetAppsAccessTokensDeAuthenticateError::Unauthorized(body),
            402u16 => iface_apps::GetAppsAccessTokensDeAuthenticateError::PaymentRequired(body),
            403u16 => iface_apps::GetAppsAccessTokensDeAuthenticateError::Forbidden(body),
            404u16 => iface_apps::GetAppsAccessTokensDeAuthenticateError::NotFound(body),
            405u16 => iface_apps::GetAppsAccessTokensDeAuthenticateError::MethodNotAllowed(body),
            406u16 => iface_apps::GetAppsAccessTokensDeAuthenticateError::NotAcceptable(body),
            500u16 => iface_apps::GetAppsAccessTokensDeAuthenticateError::InternalServerError(body),
            502u16 => iface_apps::GetAppsAccessTokensDeAuthenticateError::BadGateway(body),
            503u16 => iface_apps::GetAppsAccessTokensDeAuthenticateError::ServiceUnavailable(body),
            _ => iface_apps::GetAppsAccessTokensDeAuthenticateError::Other(body),
        },
        crate::runtime::DispatchError::Transport(m) => iface_apps::GetAppsAccessTokensDeAuthenticateError::Other(m),
    }
}

impl iface_apps::Guest for crate::Component {
    fn get_apps_access_tokens_de_authenticate(params: iface_apps::GetAppsAccessTokensDeAuthenticateParams) -> Result<iface_apps::AccessTokens, iface_apps::GetAppsAccessTokensDeAuthenticateError> {
        let json = iface_apps__get_apps_access_tokens_de_authenticate_params__to_json(&params);
        match dispatch(&OP_APPS_GET_APPS_ACCESS_TOKENS_DE_AUTHENTICATE, json).and_then(iface_apps__get_apps_access_tokens_de_authenticate__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_apps__get_apps_access_tokens_de_authenticate__err(e)),
        }
    }
}
