// AUTOGENERATED by openapi-bindgen. Do not edit by hand.

use crate::runtime::{dispatch, AuthApply, AuthKind, FieldLocation, FieldSpec, OpSpec};
use crate::exports::autostamp::stripe::transfers as iface_transfers;
use serde_json::{Map, Value};

const OP_TRANSFERS_GET_TRANSFERS: OpSpec = OpSpec {
    method: "GET",
    path_template: "/v1/transfers",
    fields: &[
        FieldSpec { snake: "created", wire: "created", location: FieldLocation::Query },
        FieldSpec { snake: "destination", wire: "destination", location: FieldLocation::Query },
        FieldSpec { snake: "ending_before", wire: "ending_before", location: FieldLocation::Query },
        FieldSpec { snake: "expand", wire: "expand", location: FieldLocation::Query },
        FieldSpec { snake: "limit", wire: "limit", location: FieldLocation::Query },
        FieldSpec { snake: "starting_after", wire: "starting_after", location: FieldLocation::Query },
        FieldSpec { snake: "transfer_group", wire: "transfer_group", location: FieldLocation::Query },
        FieldSpec { snake: "data", wire: "data", location: FieldLocation::Body },
    ],
    auth: &[
        AuthApply { secret_key: "basicAuth", kind: AuthKind::Basic },
    ],
};

const OP_TRANSFERS_POST_TRANSFERS: OpSpec = OpSpec {
    method: "POST",
    path_template: "/v1/transfers",
    fields: &[
        FieldSpec { snake: "amount", wire: "amount", location: FieldLocation::Body },
        FieldSpec { snake: "currency", wire: "currency", location: FieldLocation::Body },
        FieldSpec { snake: "description", wire: "description", location: FieldLocation::Body },
        FieldSpec { snake: "destination", wire: "destination", location: FieldLocation::Body },
        FieldSpec { snake: "expand", wire: "expand", location: FieldLocation::Body },
        FieldSpec { snake: "metadata", wire: "metadata", location: FieldLocation::Body },
        FieldSpec { snake: "source_transaction", wire: "source_transaction", location: FieldLocation::Body },
        FieldSpec { snake: "source_type", wire: "source_type", location: FieldLocation::Body },
        FieldSpec { snake: "transfer_group", wire: "transfer_group", location: FieldLocation::Body },
    ],
    auth: &[
        AuthApply { secret_key: "basicAuth", kind: AuthKind::Basic },
    ],
};

const OP_TRANSFERS_GET_TRANSFERS_ID_REVERSALS: OpSpec = OpSpec {
    method: "GET",
    path_template: "/v1/transfers/{id}/reversals",
    fields: &[
        FieldSpec { snake: "ending_before", wire: "ending_before", location: FieldLocation::Query },
        FieldSpec { snake: "expand", wire: "expand", location: FieldLocation::Query },
        FieldSpec { snake: "id", wire: "id", location: FieldLocation::Path },
        FieldSpec { snake: "limit", wire: "limit", location: FieldLocation::Query },
        FieldSpec { snake: "starting_after", wire: "starting_after", location: FieldLocation::Query },
        FieldSpec { snake: "data", wire: "data", location: FieldLocation::Body },
    ],
    auth: &[
        AuthApply { secret_key: "basicAuth", kind: AuthKind::Basic },
    ],
};

const OP_TRANSFERS_POST_TRANSFERS_ID_REVERSALS: OpSpec = OpSpec {
    method: "POST",
    path_template: "/v1/transfers/{id}/reversals",
    fields: &[
        FieldSpec { snake: "id", wire: "id", location: FieldLocation::Path },
        FieldSpec { snake: "amount", wire: "amount", location: FieldLocation::Body },
        FieldSpec { snake: "description", wire: "description", location: FieldLocation::Body },
        FieldSpec { snake: "expand", wire: "expand", location: FieldLocation::Body },
        FieldSpec { snake: "metadata", wire: "metadata", location: FieldLocation::Body },
        FieldSpec { snake: "refund_application_fee", wire: "refund_application_fee", location: FieldLocation::Body },
    ],
    auth: &[
        AuthApply { secret_key: "basicAuth", kind: AuthKind::Basic },
    ],
};

const OP_TRANSFERS_GET_TRANSFERS_TRANSFER: OpSpec = OpSpec {
    method: "GET",
    path_template: "/v1/transfers/{transfer}",
    fields: &[
        FieldSpec { snake: "expand", wire: "expand", location: FieldLocation::Query },
        FieldSpec { snake: "transfer", wire: "transfer", location: FieldLocation::Path },
        FieldSpec { snake: "data", wire: "data", location: FieldLocation::Body },
    ],
    auth: &[
        AuthApply { secret_key: "basicAuth", kind: AuthKind::Basic },
    ],
};

const OP_TRANSFERS_POST_TRANSFERS_TRANSFER: OpSpec = OpSpec {
    method: "POST",
    path_template: "/v1/transfers/{transfer}",
    fields: &[
        FieldSpec { snake: "transfer", wire: "transfer", location: FieldLocation::Path },
        FieldSpec { snake: "description", wire: "description", location: FieldLocation::Body },
        FieldSpec { snake: "expand", wire: "expand", location: FieldLocation::Body },
        FieldSpec { snake: "metadata", wire: "metadata", location: FieldLocation::Body },
    ],
    auth: &[
        AuthApply { secret_key: "basicAuth", kind: AuthKind::Basic },
    ],
};

const OP_TRANSFERS_GET_TRANSFERS_TRANSFER_REVERSALS_ID: OpSpec = OpSpec {
    method: "GET",
    path_template: "/v1/transfers/{transfer}/reversals/{id}",
    fields: &[
        FieldSpec { snake: "expand", wire: "expand", location: FieldLocation::Query },
        FieldSpec { snake: "id", wire: "id", location: FieldLocation::Path },
        FieldSpec { snake: "transfer", wire: "transfer", location: FieldLocation::Path },
        FieldSpec { snake: "data", wire: "data", location: FieldLocation::Body },
    ],
    auth: &[
        AuthApply { secret_key: "basicAuth", kind: AuthKind::Basic },
    ],
};

const OP_TRANSFERS_POST_TRANSFERS_TRANSFER_REVERSALS_ID: OpSpec = OpSpec {
    method: "POST",
    path_template: "/v1/transfers/{transfer}/reversals/{id}",
    fields: &[
        FieldSpec { snake: "id", wire: "id", location: FieldLocation::Path },
        FieldSpec { snake: "transfer", wire: "transfer", location: FieldLocation::Path },
        FieldSpec { snake: "expand", wire: "expand", location: FieldLocation::Body },
        FieldSpec { snake: "metadata", wire: "metadata", location: FieldLocation::Body },
    ],
    auth: &[
        AuthApply { secret_key: "basicAuth", kind: AuthKind::Basic },
    ],
};

fn iface_transfers__transfer_object_enum__to_str(e: &iface_transfers::TransferObjectEnum) -> &'static str {
    match e {
        iface_transfers::TransferObjectEnum::Transfer => "transfer",
    }
}

fn iface_transfers__transfer_reversal_object_enum__to_str(e: &iface_transfers::TransferReversalObjectEnum) -> &'static str {
    match e {
        iface_transfers::TransferReversalObjectEnum::TransferReversal => "transfer_reversal",
    }
}

fn iface_transfers__transfer_reversals_object_enum__to_str(e: &iface_transfers::TransferReversalsObjectEnum) -> &'static str {
    match e {
        iface_transfers::TransferReversalsObjectEnum::ListOp => "list",
    }
}

fn iface_transfers__post_transfers_body_source_type_enum__to_str(e: &iface_transfers::PostTransfersBodySourceTypeEnum) -> &'static str {
    match e {
        iface_transfers::PostTransfersBodySourceTypeEnum::BankAccount => "bank_account",
        iface_transfers::PostTransfersBodySourceTypeEnum::Card => "card",
        iface_transfers::PostTransfersBodySourceTypeEnum::Fpx => "fpx",
    }
}

fn iface_transfers__get_transfers_response__to_json(p: &iface_transfers::GetTransfersResponse) -> Value {
    let mut m = Map::new();
    m.insert("data".into(), Value::Array((&p.data).iter().map(|v| iface_transfers__transfer__to_json(v)).collect()));
    m.insert("has_more".into(), Value::Bool(*(&p.has_more)));
    m.insert("object".into(), Value::String(iface_transfers__transfer_reversals_object_enum__to_str(&p.object).into()));
    m.insert("url".into(), Value::String((&p.url).clone()));
    Value::Object(m)
}

fn iface_transfers__transfer__to_json(p: &iface_transfers::Transfer) -> Value {
    let mut m = Map::new();
    m.insert("amount".into(), Value::Number(serde_json::Number::from(*(&p.amount))));
    m.insert("amount_reversed".into(), Value::Number(serde_json::Number::from(*(&p.amount_reversed))));
    m.insert("balance_transaction".into(), match (&p.balance_transaction) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("created".into(), Value::Number(serde_json::Number::from(*(&p.created))));
    m.insert("currency".into(), Value::String((&p.currency).clone()));
    m.insert("description".into(), match (&p.description) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("destination".into(), match (&p.destination) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("destination_payment".into(), match (&p.destination_payment) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("id".into(), Value::String((&p.id).clone()));
    m.insert("livemode".into(), Value::Bool(*(&p.livemode)));
    m.insert("metadata".into(), Value::Object((&p.metadata).iter().map(|e| (e.key.clone(), Value::String((&e.value).clone()))).collect()));
    m.insert("object".into(), Value::String(iface_transfers__transfer_object_enum__to_str(&p.object).into()));
    m.insert("reversals".into(), iface_transfers__transfer_reversals__to_json(&p.reversals));
    m.insert("reversed".into(), Value::Bool(*(&p.reversed)));
    m.insert("source_transaction".into(), match (&p.source_transaction) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("source_type".into(), match (&p.source_type) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("transfer_group".into(), match (&p.transfer_group) { Some(v) => Value::String((v).clone()), None => Value::Null });
    Value::Object(m)
}

fn iface_transfers__transfer_metadata_entry__to_json(p: &iface_transfers::TransferMetadataEntry) -> Value {
    let mut m = Map::new();
    m.insert("key".into(), Value::String((&p.key).clone()));
    m.insert("value".into(), Value::String((&p.value).clone()));
    Value::Object(m)
}

fn iface_transfers__transfer_reversals__to_json(p: &iface_transfers::TransferReversals) -> Value {
    let mut m = Map::new();
    m.insert("data".into(), Value::Array((&p.data).iter().map(|v| iface_transfers__transfer_reversal__to_json(v)).collect()));
    m.insert("has_more".into(), Value::Bool(*(&p.has_more)));
    m.insert("object".into(), Value::String(iface_transfers__transfer_reversals_object_enum__to_str(&p.object).into()));
    m.insert("url".into(), Value::String((&p.url).clone()));
    Value::Object(m)
}

fn iface_transfers__transfer_reversal__to_json(p: &iface_transfers::TransferReversal) -> Value {
    let mut m = Map::new();
    m.insert("amount".into(), Value::Number(serde_json::Number::from(*(&p.amount))));
    m.insert("balance_transaction".into(), match (&p.balance_transaction) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("created".into(), Value::Number(serde_json::Number::from(*(&p.created))));
    m.insert("currency".into(), Value::String((&p.currency).clone()));
    m.insert("destination_payment_refund".into(), match (&p.destination_payment_refund) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("id".into(), Value::String((&p.id).clone()));
    m.insert("metadata".into(), match (&p.metadata) { Some(v) => Value::Object((v).iter().map(|e| (e.key.clone(), Value::String((&e.value).clone()))).collect()), None => Value::Null });
    m.insert("object".into(), Value::String(iface_transfers__transfer_reversal_object_enum__to_str(&p.object).into()));
    m.insert("source_refund".into(), match (&p.source_refund) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("transfer".into(), Value::String((&p.transfer).clone()));
    Value::Object(m)
}

fn iface_transfers__transfer_reversal_metadata_entry__to_json(p: &iface_transfers::TransferReversalMetadataEntry) -> Value {
    let mut m = Map::new();
    m.insert("key".into(), Value::String((&p.key).clone()));
    m.insert("value".into(), Value::String((&p.value).clone()));
    Value::Object(m)
}

fn iface_transfers__post_transfers_body_metadata_entry__to_json(p: &iface_transfers::PostTransfersBodyMetadataEntry) -> Value {
    let mut m = Map::new();
    m.insert("key".into(), Value::String((&p.key).clone()));
    m.insert("value".into(), Value::String((&p.value).clone()));
    Value::Object(m)
}

fn iface_transfers__get_transfers_id_reversals_response__to_json(p: &iface_transfers::GetTransfersIdReversalsResponse) -> Value {
    let mut m = Map::new();
    m.insert("data".into(), Value::Array((&p.data).iter().map(|v| iface_transfers__transfer_reversal__to_json(v)).collect()));
    m.insert("has_more".into(), Value::Bool(*(&p.has_more)));
    m.insert("object".into(), Value::String(iface_transfers__transfer_reversals_object_enum__to_str(&p.object).into()));
    m.insert("url".into(), Value::String((&p.url).clone()));
    Value::Object(m)
}

fn iface_transfers__get_transfers_params__to_json(p: &iface_transfers::GetTransfersParams) -> Value {
    let mut m = Map::new();
    m.insert("created".into(), match (&p.created) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("destination".into(), match (&p.destination) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("ending_before".into(), match (&p.ending_before) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("expand".into(), match (&p.expand) { Some(v) => Value::Array((v).iter().map(|v| Value::String((v).clone())).collect()), None => Value::Null });
    m.insert("limit".into(), match (&p.limit) { Some(v) => Value::Number(serde_json::Number::from(*(v))), None => Value::Null });
    m.insert("starting_after".into(), match (&p.starting_after) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("transfer_group".into(), match (&p.transfer_group) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("data".into(), match (&p.data) { Some(v) => Value::String((v).clone()), None => Value::Null });
    Value::Object(m)
}

fn iface_transfers__post_transfers_params__to_json(p: &iface_transfers::PostTransfersParams) -> Value {
    let mut m = Map::new();
    m.insert("amount".into(), match (&p.amount) { Some(v) => Value::Number(serde_json::Number::from(*(v))), None => Value::Null });
    m.insert("currency".into(), Value::String((&p.currency).clone()));
    m.insert("description".into(), match (&p.description) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("destination".into(), Value::String((&p.destination).clone()));
    m.insert("expand".into(), match (&p.expand) { Some(v) => Value::Array((v).iter().map(|v| Value::String((v).clone())).collect()), None => Value::Null });
    m.insert("metadata".into(), match (&p.metadata) { Some(v) => Value::Object((v).iter().map(|e| (e.key.clone(), Value::String((&e.value).clone()))).collect()), None => Value::Null });
    m.insert("source_transaction".into(), match (&p.source_transaction) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("source_type".into(), match (&p.source_type) { Some(v) => Value::String(iface_transfers__post_transfers_body_source_type_enum__to_str(v).into()), None => Value::Null });
    m.insert("transfer_group".into(), match (&p.transfer_group) { Some(v) => Value::String((v).clone()), None => Value::Null });
    Value::Object(m)
}

fn iface_transfers__get_transfers_id_reversals_params__to_json(p: &iface_transfers::GetTransfersIdReversalsParams) -> Value {
    let mut m = Map::new();
    m.insert("ending_before".into(), match (&p.ending_before) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("expand".into(), match (&p.expand) { Some(v) => Value::Array((v).iter().map(|v| Value::String((v).clone())).collect()), None => Value::Null });
    m.insert("id".into(), Value::String((&p.id).clone()));
    m.insert("limit".into(), match (&p.limit) { Some(v) => Value::Number(serde_json::Number::from(*(v))), None => Value::Null });
    m.insert("starting_after".into(), match (&p.starting_after) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("data".into(), match (&p.data) { Some(v) => Value::String((v).clone()), None => Value::Null });
    Value::Object(m)
}

fn iface_transfers__post_transfers_id_reversals_params__to_json(p: &iface_transfers::PostTransfersIdReversalsParams) -> Value {
    let mut m = Map::new();
    m.insert("id".into(), Value::String((&p.id).clone()));
    m.insert("amount".into(), match (&p.amount) { Some(v) => Value::Number(serde_json::Number::from(*(v))), None => Value::Null });
    m.insert("description".into(), match (&p.description) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("expand".into(), match (&p.expand) { Some(v) => Value::Array((v).iter().map(|v| Value::String((v).clone())).collect()), None => Value::Null });
    m.insert("metadata".into(), match (&p.metadata) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("refund_application_fee".into(), match (&p.refund_application_fee) { Some(v) => Value::Bool(*(v)), None => Value::Null });
    Value::Object(m)
}

fn iface_transfers__get_transfers_transfer_params__to_json(p: &iface_transfers::GetTransfersTransferParams) -> Value {
    let mut m = Map::new();
    m.insert("expand".into(), match (&p.expand) { Some(v) => Value::Array((v).iter().map(|v| Value::String((v).clone())).collect()), None => Value::Null });
    m.insert("transfer".into(), Value::String((&p.transfer).clone()));
    m.insert("data".into(), match (&p.data) { Some(v) => Value::String((v).clone()), None => Value::Null });
    Value::Object(m)
}

fn iface_transfers__post_transfers_transfer_params__to_json(p: &iface_transfers::PostTransfersTransferParams) -> Value {
    let mut m = Map::new();
    m.insert("transfer".into(), Value::String((&p.transfer).clone()));
    m.insert("description".into(), match (&p.description) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("expand".into(), match (&p.expand) { Some(v) => Value::Array((v).iter().map(|v| Value::String((v).clone())).collect()), None => Value::Null });
    m.insert("metadata".into(), match (&p.metadata) { Some(v) => Value::String((v).clone()), None => Value::Null });
    Value::Object(m)
}

fn iface_transfers__get_transfers_transfer_reversals_id_params__to_json(p: &iface_transfers::GetTransfersTransferReversalsIdParams) -> Value {
    let mut m = Map::new();
    m.insert("expand".into(), match (&p.expand) { Some(v) => Value::Array((v).iter().map(|v| Value::String((v).clone())).collect()), None => Value::Null });
    m.insert("id".into(), Value::String((&p.id).clone()));
    m.insert("transfer".into(), Value::String((&p.transfer).clone()));
    m.insert("data".into(), match (&p.data) { Some(v) => Value::String((v).clone()), None => Value::Null });
    Value::Object(m)
}

fn iface_transfers__post_transfers_transfer_reversals_id_params__to_json(p: &iface_transfers::PostTransfersTransferReversalsIdParams) -> Value {
    let mut m = Map::new();
    m.insert("id".into(), Value::String((&p.id).clone()));
    m.insert("transfer".into(), Value::String((&p.transfer).clone()));
    m.insert("expand".into(), match (&p.expand) { Some(v) => Value::Array((v).iter().map(|v| Value::String((v).clone())).collect()), None => Value::Null });
    m.insert("metadata".into(), match (&p.metadata) { Some(v) => Value::String((v).clone()), None => Value::Null });
    Value::Object(m)
}

fn iface_transfers__get_transfers_response__from_json(v: &Value) -> Option<iface_transfers::GetTransfersResponse> {
    let m = v.as_object()?;
    Some(iface_transfers::GetTransfersResponse {
        data: m.get("data").and_then(|v| (v).as_array().map(|a| a.iter().filter_map(|x| iface_transfers__transfer__from_json(x)).collect())).unwrap_or_default(),
        has_more: m.get("has_more").and_then(|v| (v).as_bool()).unwrap_or_default(),
        object: match m.get("object").and_then(|v| (v).as_str().and_then(iface_transfers__transfer_reversals_object_enum__from_str)) { Some(x) => x, None => return None },
        url: m.get("url").and_then(|v| (v).as_str().map(|s| s.to_string())).unwrap_or_default(),
    })
}

fn iface_transfers__transfer__from_json(v: &Value) -> Option<iface_transfers::Transfer> {
    let m = v.as_object()?;
    Some(iface_transfers::Transfer {
        amount: m.get("amount").and_then(|v| (v).as_i64().map(|n| n as i32)).unwrap_or_default(),
        amount_reversed: m.get("amount_reversed").and_then(|v| (v).as_i64().map(|n| n as i32)).unwrap_or_default(),
        balance_transaction: m.get("balance_transaction").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        created: m.get("created").and_then(|v| (v).as_i64().map(|n| n as i32)).unwrap_or_default(),
        currency: m.get("currency").and_then(|v| (v).as_str().map(|s| s.to_string())).unwrap_or_default(),
        description: m.get("description").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        destination: m.get("destination").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        destination_payment: m.get("destination_payment").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        id: m.get("id").and_then(|v| (v).as_str().map(|s| s.to_string())).unwrap_or_default(),
        livemode: m.get("livemode").and_then(|v| (v).as_bool()).unwrap_or_default(),
        metadata: m.get("metadata").and_then(|v| (v).as_object().map(|o| o.iter().filter_map(|(k, x)| ((x).as_str().map(|s| s.to_string())).map(|val| iface_transfers::TransferMetadataEntry { key: k.clone(), value: val })).collect())).unwrap_or_default(),
        object: match m.get("object").and_then(|v| (v).as_str().and_then(iface_transfers__transfer_object_enum__from_str)) { Some(x) => x, None => return None },
        reversals: match m.get("reversals").and_then(|v| iface_transfers__transfer_reversals__from_json(v)) { Some(x) => x, None => return None },
        reversed: m.get("reversed").and_then(|v| (v).as_bool()).unwrap_or_default(),
        source_transaction: m.get("source_transaction").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        source_type: m.get("source_type").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        transfer_group: m.get("transfer_group").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
    })
}

fn iface_transfers__transfer_metadata_entry__from_json(v: &Value) -> Option<iface_transfers::TransferMetadataEntry> {
    let m = v.as_object()?;
    Some(iface_transfers::TransferMetadataEntry {
        key: m.get("key").and_then(|v| (v).as_str().map(|s| s.to_string())).unwrap_or_default(),
        value: m.get("value").and_then(|v| (v).as_str().map(|s| s.to_string())).unwrap_or_default(),
    })
}

fn iface_transfers__transfer_reversals__from_json(v: &Value) -> Option<iface_transfers::TransferReversals> {
    let m = v.as_object()?;
    Some(iface_transfers::TransferReversals {
        data: m.get("data").and_then(|v| (v).as_array().map(|a| a.iter().filter_map(|x| iface_transfers__transfer_reversal__from_json(x)).collect())).unwrap_or_default(),
        has_more: m.get("has_more").and_then(|v| (v).as_bool()).unwrap_or_default(),
        object: match m.get("object").and_then(|v| (v).as_str().and_then(iface_transfers__transfer_reversals_object_enum__from_str)) { Some(x) => x, None => return None },
        url: m.get("url").and_then(|v| (v).as_str().map(|s| s.to_string())).unwrap_or_default(),
    })
}

fn iface_transfers__transfer_reversal__from_json(v: &Value) -> Option<iface_transfers::TransferReversal> {
    let m = v.as_object()?;
    Some(iface_transfers::TransferReversal {
        amount: m.get("amount").and_then(|v| (v).as_i64().map(|n| n as i32)).unwrap_or_default(),
        balance_transaction: m.get("balance_transaction").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        created: m.get("created").and_then(|v| (v).as_i64().map(|n| n as i32)).unwrap_or_default(),
        currency: m.get("currency").and_then(|v| (v).as_str().map(|s| s.to_string())).unwrap_or_default(),
        destination_payment_refund: m.get("destination_payment_refund").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        id: m.get("id").and_then(|v| (v).as_str().map(|s| s.to_string())).unwrap_or_default(),
        metadata: m.get("metadata").filter(|v| !v.is_null()).and_then(|v| (v).as_object().map(|o| o.iter().filter_map(|(k, x)| ((x).as_str().map(|s| s.to_string())).map(|val| iface_transfers::TransferReversalMetadataEntry { key: k.clone(), value: val })).collect())),
        object: match m.get("object").and_then(|v| (v).as_str().and_then(iface_transfers__transfer_reversal_object_enum__from_str)) { Some(x) => x, None => return None },
        source_refund: m.get("source_refund").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        transfer: m.get("transfer").and_then(|v| (v).as_str().map(|s| s.to_string())).unwrap_or_default(),
    })
}

fn iface_transfers__transfer_reversal_metadata_entry__from_json(v: &Value) -> Option<iface_transfers::TransferReversalMetadataEntry> {
    let m = v.as_object()?;
    Some(iface_transfers::TransferReversalMetadataEntry {
        key: m.get("key").and_then(|v| (v).as_str().map(|s| s.to_string())).unwrap_or_default(),
        value: m.get("value").and_then(|v| (v).as_str().map(|s| s.to_string())).unwrap_or_default(),
    })
}

fn iface_transfers__get_transfers_id_reversals_response__from_json(v: &Value) -> Option<iface_transfers::GetTransfersIdReversalsResponse> {
    let m = v.as_object()?;
    Some(iface_transfers::GetTransfersIdReversalsResponse {
        data: m.get("data").and_then(|v| (v).as_array().map(|a| a.iter().filter_map(|x| iface_transfers__transfer_reversal__from_json(x)).collect())).unwrap_or_default(),
        has_more: m.get("has_more").and_then(|v| (v).as_bool()).unwrap_or_default(),
        object: match m.get("object").and_then(|v| (v).as_str().and_then(iface_transfers__transfer_reversals_object_enum__from_str)) { Some(x) => x, None => return None },
        url: m.get("url").and_then(|v| (v).as_str().map(|s| s.to_string())).unwrap_or_default(),
    })
}

fn iface_transfers__transfer_object_enum__from_str(s: &str) -> Option<iface_transfers::TransferObjectEnum> {
    match s {
        "transfer" => Some(iface_transfers::TransferObjectEnum::Transfer),
        _ => None,
    }
}

fn iface_transfers__transfer_reversal_object_enum__from_str(s: &str) -> Option<iface_transfers::TransferReversalObjectEnum> {
    match s {
        "transfer_reversal" => Some(iface_transfers::TransferReversalObjectEnum::TransferReversal),
        _ => None,
    }
}

fn iface_transfers__transfer_reversals_object_enum__from_str(s: &str) -> Option<iface_transfers::TransferReversalsObjectEnum> {
    match s {
        "list" => Some(iface_transfers::TransferReversalsObjectEnum::ListOp),
        _ => None,
    }
}

fn iface_transfers__get_transfers__ok(body: String) -> Result<iface_transfers::GetTransfersResponse, crate::runtime::DispatchError> {
    let v: Value = match serde_json::from_str(&body) {
        Ok(v) => v,
        Err(e) => return Err(crate::runtime::DispatchError::Transport(format!("failed to decode response body as JSON: {e}"))),
    };
    match iface_transfers__get_transfers_response__from_json(&v) {
        Some(x) => Ok(x),
        None => Err(crate::runtime::DispatchError::Transport("response body did not match the expected schema".to_string())),
    }
}

fn iface_transfers__get_transfers__err(e: crate::runtime::DispatchError) -> String {
    match e {
        crate::runtime::DispatchError::Http { status, body } => format!("HTTP {status}: {body}"),
        crate::runtime::DispatchError::Transport(m) => m,
    }
}

fn iface_transfers__post_transfers__ok(body: String) -> Result<iface_transfers::Transfer, crate::runtime::DispatchError> {
    let v: Value = match serde_json::from_str(&body) {
        Ok(v) => v,
        Err(e) => return Err(crate::runtime::DispatchError::Transport(format!("failed to decode response body as JSON: {e}"))),
    };
    match iface_transfers__transfer__from_json(&v) {
        Some(x) => Ok(x),
        None => Err(crate::runtime::DispatchError::Transport("response body did not match the expected schema".to_string())),
    }
}

fn iface_transfers__post_transfers__err(e: crate::runtime::DispatchError) -> String {
    match e {
        crate::runtime::DispatchError::Http { status, body } => format!("HTTP {status}: {body}"),
        crate::runtime::DispatchError::Transport(m) => m,
    }
}

fn iface_transfers__get_transfers_id_reversals__ok(body: String) -> Result<iface_transfers::GetTransfersIdReversalsResponse, crate::runtime::DispatchError> {
    let v: Value = match serde_json::from_str(&body) {
        Ok(v) => v,
        Err(e) => return Err(crate::runtime::DispatchError::Transport(format!("failed to decode response body as JSON: {e}"))),
    };
    match iface_transfers__get_transfers_id_reversals_response__from_json(&v) {
        Some(x) => Ok(x),
        None => Err(crate::runtime::DispatchError::Transport("response body did not match the expected schema".to_string())),
    }
}

fn iface_transfers__get_transfers_id_reversals__err(e: crate::runtime::DispatchError) -> String {
    match e {
        crate::runtime::DispatchError::Http { status, body } => format!("HTTP {status}: {body}"),
        crate::runtime::DispatchError::Transport(m) => m,
    }
}

fn iface_transfers__post_transfers_id_reversals__ok(body: String) -> Result<iface_transfers::TransferReversal, crate::runtime::DispatchError> {
    let v: Value = match serde_json::from_str(&body) {
        Ok(v) => v,
        Err(e) => return Err(crate::runtime::DispatchError::Transport(format!("failed to decode response body as JSON: {e}"))),
    };
    match iface_transfers__transfer_reversal__from_json(&v) {
        Some(x) => Ok(x),
        None => Err(crate::runtime::DispatchError::Transport("response body did not match the expected schema".to_string())),
    }
}

fn iface_transfers__post_transfers_id_reversals__err(e: crate::runtime::DispatchError) -> String {
    match e {
        crate::runtime::DispatchError::Http { status, body } => format!("HTTP {status}: {body}"),
        crate::runtime::DispatchError::Transport(m) => m,
    }
}

fn iface_transfers__get_transfers_transfer__ok(body: String) -> Result<iface_transfers::Transfer, crate::runtime::DispatchError> {
    let v: Value = match serde_json::from_str(&body) {
        Ok(v) => v,
        Err(e) => return Err(crate::runtime::DispatchError::Transport(format!("failed to decode response body as JSON: {e}"))),
    };
    match iface_transfers__transfer__from_json(&v) {
        Some(x) => Ok(x),
        None => Err(crate::runtime::DispatchError::Transport("response body did not match the expected schema".to_string())),
    }
}

fn iface_transfers__get_transfers_transfer__err(e: crate::runtime::DispatchError) -> String {
    match e {
        crate::runtime::DispatchError::Http { status, body } => format!("HTTP {status}: {body}"),
        crate::runtime::DispatchError::Transport(m) => m,
    }
}

fn iface_transfers__post_transfers_transfer__ok(body: String) -> Result<iface_transfers::Transfer, crate::runtime::DispatchError> {
    let v: Value = match serde_json::from_str(&body) {
        Ok(v) => v,
        Err(e) => return Err(crate::runtime::DispatchError::Transport(format!("failed to decode response body as JSON: {e}"))),
    };
    match iface_transfers__transfer__from_json(&v) {
        Some(x) => Ok(x),
        None => Err(crate::runtime::DispatchError::Transport("response body did not match the expected schema".to_string())),
    }
}

fn iface_transfers__post_transfers_transfer__err(e: crate::runtime::DispatchError) -> String {
    match e {
        crate::runtime::DispatchError::Http { status, body } => format!("HTTP {status}: {body}"),
        crate::runtime::DispatchError::Transport(m) => m,
    }
}

fn iface_transfers__get_transfers_transfer_reversals_id__ok(body: String) -> Result<iface_transfers::TransferReversal, crate::runtime::DispatchError> {
    let v: Value = match serde_json::from_str(&body) {
        Ok(v) => v,
        Err(e) => return Err(crate::runtime::DispatchError::Transport(format!("failed to decode response body as JSON: {e}"))),
    };
    match iface_transfers__transfer_reversal__from_json(&v) {
        Some(x) => Ok(x),
        None => Err(crate::runtime::DispatchError::Transport("response body did not match the expected schema".to_string())),
    }
}

fn iface_transfers__get_transfers_transfer_reversals_id__err(e: crate::runtime::DispatchError) -> String {
    match e {
        crate::runtime::DispatchError::Http { status, body } => format!("HTTP {status}: {body}"),
        crate::runtime::DispatchError::Transport(m) => m,
    }
}

fn iface_transfers__post_transfers_transfer_reversals_id__ok(body: String) -> Result<iface_transfers::TransferReversal, crate::runtime::DispatchError> {
    let v: Value = match serde_json::from_str(&body) {
        Ok(v) => v,
        Err(e) => return Err(crate::runtime::DispatchError::Transport(format!("failed to decode response body as JSON: {e}"))),
    };
    match iface_transfers__transfer_reversal__from_json(&v) {
        Some(x) => Ok(x),
        None => Err(crate::runtime::DispatchError::Transport("response body did not match the expected schema".to_string())),
    }
}

fn iface_transfers__post_transfers_transfer_reversals_id__err(e: crate::runtime::DispatchError) -> String {
    match e {
        crate::runtime::DispatchError::Http { status, body } => format!("HTTP {status}: {body}"),
        crate::runtime::DispatchError::Transport(m) => m,
    }
}

impl iface_transfers::Guest for crate::Component {
    fn get_transfers(params: iface_transfers::GetTransfersParams) -> Result<iface_transfers::GetTransfersResponse, String> {
        let json = iface_transfers__get_transfers_params__to_json(&params);
        match dispatch(&OP_TRANSFERS_GET_TRANSFERS, json).and_then(iface_transfers__get_transfers__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_transfers__get_transfers__err(e)),
        }
    }
    fn post_transfers(params: iface_transfers::PostTransfersParams) -> Result<iface_transfers::Transfer, String> {
        let json = iface_transfers__post_transfers_params__to_json(&params);
        match dispatch(&OP_TRANSFERS_POST_TRANSFERS, json).and_then(iface_transfers__post_transfers__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_transfers__post_transfers__err(e)),
        }
    }
    fn get_transfers_id_reversals(params: iface_transfers::GetTransfersIdReversalsParams) -> Result<iface_transfers::GetTransfersIdReversalsResponse, String> {
        let json = iface_transfers__get_transfers_id_reversals_params__to_json(&params);
        match dispatch(&OP_TRANSFERS_GET_TRANSFERS_ID_REVERSALS, json).and_then(iface_transfers__get_transfers_id_reversals__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_transfers__get_transfers_id_reversals__err(e)),
        }
    }
    fn post_transfers_id_reversals(params: iface_transfers::PostTransfersIdReversalsParams) -> Result<iface_transfers::TransferReversal, String> {
        let json = iface_transfers__post_transfers_id_reversals_params__to_json(&params);
        match dispatch(&OP_TRANSFERS_POST_TRANSFERS_ID_REVERSALS, json).and_then(iface_transfers__post_transfers_id_reversals__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_transfers__post_transfers_id_reversals__err(e)),
        }
    }
    fn get_transfers_transfer(params: iface_transfers::GetTransfersTransferParams) -> Result<iface_transfers::Transfer, String> {
        let json = iface_transfers__get_transfers_transfer_params__to_json(&params);
        match dispatch(&OP_TRANSFERS_GET_TRANSFERS_TRANSFER, json).and_then(iface_transfers__get_transfers_transfer__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_transfers__get_transfers_transfer__err(e)),
        }
    }
    fn post_transfers_transfer(params: iface_transfers::PostTransfersTransferParams) -> Result<iface_transfers::Transfer, String> {
        let json = iface_transfers__post_transfers_transfer_params__to_json(&params);
        match dispatch(&OP_TRANSFERS_POST_TRANSFERS_TRANSFER, json).and_then(iface_transfers__post_transfers_transfer__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_transfers__post_transfers_transfer__err(e)),
        }
    }
    fn get_transfers_transfer_reversals_id(params: iface_transfers::GetTransfersTransferReversalsIdParams) -> Result<iface_transfers::TransferReversal, String> {
        let json = iface_transfers__get_transfers_transfer_reversals_id_params__to_json(&params);
        match dispatch(&OP_TRANSFERS_GET_TRANSFERS_TRANSFER_REVERSALS_ID, json).and_then(iface_transfers__get_transfers_transfer_reversals_id__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_transfers__get_transfers_transfer_reversals_id__err(e)),
        }
    }
    fn post_transfers_transfer_reversals_id(params: iface_transfers::PostTransfersTransferReversalsIdParams) -> Result<iface_transfers::TransferReversal, String> {
        let json = iface_transfers__post_transfers_transfer_reversals_id_params__to_json(&params);
        match dispatch(&OP_TRANSFERS_POST_TRANSFERS_TRANSFER_REVERSALS_ID, json).and_then(iface_transfers__post_transfers_transfer_reversals_id__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_transfers__post_transfers_transfer_reversals_id__err(e)),
        }
    }
}
