// AUTOGENERATED by openapi-bindgen. Do not edit by hand.

use crate::runtime::{dispatch, AuthApply, AuthKind, FieldLocation, FieldSpec, OpSpec};
use crate::exports::autostamp::stripe::apple_pay as iface_apple_pay;
use serde_json::{Map, Value};

const OP_APPLE_PAY_GET_APPLE_PAY_DOMAINS: OpSpec = OpSpec {
    method: "GET",
    path_template: "/v1/apple_pay/domains",
    fields: &[
        FieldSpec { snake: "domain_name", wire: "domain_name", location: FieldLocation::Query },
        FieldSpec { snake: "ending_before", wire: "ending_before", location: FieldLocation::Query },
        FieldSpec { snake: "expand", wire: "expand", location: FieldLocation::Query },
        FieldSpec { snake: "limit", wire: "limit", location: FieldLocation::Query },
        FieldSpec { snake: "starting_after", wire: "starting_after", location: FieldLocation::Query },
        FieldSpec { snake: "data", wire: "data", location: FieldLocation::Body },
    ],
    auth: &[
        AuthApply { secret_key: "basicAuth", kind: AuthKind::Basic },
    ],
};

const OP_APPLE_PAY_POST_APPLE_PAY_DOMAINS: OpSpec = OpSpec {
    method: "POST",
    path_template: "/v1/apple_pay/domains",
    fields: &[
        FieldSpec { snake: "domain_name", wire: "domain_name", location: FieldLocation::Body },
        FieldSpec { snake: "expand", wire: "expand", location: FieldLocation::Body },
    ],
    auth: &[
        AuthApply { secret_key: "basicAuth", kind: AuthKind::Basic },
    ],
};

const OP_APPLE_PAY_GET_APPLE_PAY_DOMAINS_DOMAIN: OpSpec = OpSpec {
    method: "GET",
    path_template: "/v1/apple_pay/domains/{domain}",
    fields: &[
        FieldSpec { snake: "domain", wire: "domain", location: FieldLocation::Path },
        FieldSpec { snake: "expand", wire: "expand", location: FieldLocation::Query },
        FieldSpec { snake: "data", wire: "data", location: FieldLocation::Body },
    ],
    auth: &[
        AuthApply { secret_key: "basicAuth", kind: AuthKind::Basic },
    ],
};

const OP_APPLE_PAY_DELETE_APPLE_PAY_DOMAINS_DOMAIN: OpSpec = OpSpec {
    method: "DELETE",
    path_template: "/v1/apple_pay/domains/{domain}",
    fields: &[
        FieldSpec { snake: "domain", wire: "domain", location: FieldLocation::Path },
        FieldSpec { snake: "data", wire: "data", location: FieldLocation::Body },
    ],
    auth: &[
        AuthApply { secret_key: "basicAuth", kind: AuthKind::Basic },
    ],
};

fn iface_apple_pay__domain_object_enum__to_str(e: &iface_apple_pay::DomainObjectEnum) -> &'static str {
    match e {
        iface_apple_pay::DomainObjectEnum::ApplePayDomain => "apple_pay_domain",
    }
}

fn iface_apple_pay__get_apple_pay_domains_response_object_enum__to_str(e: &iface_apple_pay::GetApplePayDomainsResponseObjectEnum) -> &'static str {
    match e {
        iface_apple_pay::GetApplePayDomainsResponseObjectEnum::ListOp => "list",
    }
}

fn iface_apple_pay__get_apple_pay_domains_response__to_json(p: &iface_apple_pay::GetApplePayDomainsResponse) -> Value {
    let mut m = Map::new();
    m.insert("data".into(), Value::Array((&p.data).iter().map(|v| iface_apple_pay__domain__to_json(v)).collect()));
    m.insert("has_more".into(), Value::Bool(*(&p.has_more)));
    m.insert("object".into(), Value::String(iface_apple_pay__get_apple_pay_domains_response_object_enum__to_str(&p.object).into()));
    m.insert("url".into(), Value::String((&p.url).clone()));
    Value::Object(m)
}

fn iface_apple_pay__domain__to_json(p: &iface_apple_pay::Domain) -> Value {
    let mut m = Map::new();
    m.insert("created".into(), Value::Number(serde_json::Number::from(*(&p.created))));
    m.insert("domain_name".into(), Value::String((&p.domain_name).clone()));
    m.insert("id".into(), Value::String((&p.id).clone()));
    m.insert("livemode".into(), Value::Bool(*(&p.livemode)));
    m.insert("object".into(), Value::String(iface_apple_pay__domain_object_enum__to_str(&p.object).into()));
    Value::Object(m)
}

fn iface_apple_pay__deleted_apple_pay_domain__to_json(p: &iface_apple_pay::DeletedApplePayDomain) -> Value {
    let mut m = Map::new();
    m.insert("deleted".into(), Value::Bool(*(&p.deleted)));
    m.insert("id".into(), Value::String((&p.id).clone()));
    m.insert("object".into(), Value::String(iface_apple_pay__domain_object_enum__to_str(&p.object).into()));
    Value::Object(m)
}

fn iface_apple_pay__get_apple_pay_domains_params__to_json(p: &iface_apple_pay::GetApplePayDomainsParams) -> Value {
    let mut m = Map::new();
    m.insert("domain_name".into(), match (&p.domain_name) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("ending_before".into(), match (&p.ending_before) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("expand".into(), match (&p.expand) { Some(v) => Value::Array((v).iter().map(|v| Value::String((v).clone())).collect()), None => Value::Null });
    m.insert("limit".into(), match (&p.limit) { Some(v) => Value::Number(serde_json::Number::from(*(v))), None => Value::Null });
    m.insert("starting_after".into(), match (&p.starting_after) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("data".into(), match (&p.data) { Some(v) => Value::String((v).clone()), None => Value::Null });
    Value::Object(m)
}

fn iface_apple_pay__post_apple_pay_domains_params__to_json(p: &iface_apple_pay::PostApplePayDomainsParams) -> Value {
    let mut m = Map::new();
    m.insert("domain_name".into(), Value::String((&p.domain_name).clone()));
    m.insert("expand".into(), match (&p.expand) { Some(v) => Value::Array((v).iter().map(|v| Value::String((v).clone())).collect()), None => Value::Null });
    Value::Object(m)
}

fn iface_apple_pay__get_apple_pay_domains_domain_params__to_json(p: &iface_apple_pay::GetApplePayDomainsDomainParams) -> Value {
    let mut m = Map::new();
    m.insert("domain".into(), Value::String((&p.domain).clone()));
    m.insert("expand".into(), match (&p.expand) { Some(v) => Value::Array((v).iter().map(|v| Value::String((v).clone())).collect()), None => Value::Null });
    m.insert("data".into(), match (&p.data) { Some(v) => Value::String((v).clone()), None => Value::Null });
    Value::Object(m)
}

fn iface_apple_pay__delete_apple_pay_domains_domain_params__to_json(p: &iface_apple_pay::DeleteApplePayDomainsDomainParams) -> Value {
    let mut m = Map::new();
    m.insert("domain".into(), Value::String((&p.domain).clone()));
    m.insert("data".into(), match (&p.data) { Some(v) => Value::String((v).clone()), None => Value::Null });
    Value::Object(m)
}

fn iface_apple_pay__get_apple_pay_domains_response__from_json(v: &Value) -> Option<iface_apple_pay::GetApplePayDomainsResponse> {
    let m = v.as_object()?;
    Some(iface_apple_pay::GetApplePayDomainsResponse {
        data: m.get("data").and_then(|v| (v).as_array().map(|a| a.iter().filter_map(|x| iface_apple_pay__domain__from_json(x)).collect())).unwrap_or_default(),
        has_more: m.get("has_more").and_then(|v| (v).as_bool()).unwrap_or_default(),
        object: match m.get("object").and_then(|v| (v).as_str().and_then(iface_apple_pay__get_apple_pay_domains_response_object_enum__from_str)) { Some(x) => x, None => return None },
        url: m.get("url").and_then(|v| (v).as_str().map(|s| s.to_string())).unwrap_or_default(),
    })
}

fn iface_apple_pay__domain__from_json(v: &Value) -> Option<iface_apple_pay::Domain> {
    let m = v.as_object()?;
    Some(iface_apple_pay::Domain {
        created: m.get("created").and_then(|v| (v).as_i64().map(|n| n as i32)).unwrap_or_default(),
        domain_name: m.get("domain_name").and_then(|v| (v).as_str().map(|s| s.to_string())).unwrap_or_default(),
        id: m.get("id").and_then(|v| (v).as_str().map(|s| s.to_string())).unwrap_or_default(),
        livemode: m.get("livemode").and_then(|v| (v).as_bool()).unwrap_or_default(),
        object: match m.get("object").and_then(|v| (v).as_str().and_then(iface_apple_pay__domain_object_enum__from_str)) { Some(x) => x, None => return None },
    })
}

fn iface_apple_pay__deleted_apple_pay_domain__from_json(v: &Value) -> Option<iface_apple_pay::DeletedApplePayDomain> {
    let m = v.as_object()?;
    Some(iface_apple_pay::DeletedApplePayDomain {
        deleted: m.get("deleted").and_then(|v| (v).as_bool()).unwrap_or_default(),
        id: m.get("id").and_then(|v| (v).as_str().map(|s| s.to_string())).unwrap_or_default(),
        object: match m.get("object").and_then(|v| (v).as_str().and_then(iface_apple_pay__domain_object_enum__from_str)) { Some(x) => x, None => return None },
    })
}

fn iface_apple_pay__domain_object_enum__from_str(s: &str) -> Option<iface_apple_pay::DomainObjectEnum> {
    match s {
        "apple_pay_domain" => Some(iface_apple_pay::DomainObjectEnum::ApplePayDomain),
        _ => None,
    }
}

fn iface_apple_pay__get_apple_pay_domains_response_object_enum__from_str(s: &str) -> Option<iface_apple_pay::GetApplePayDomainsResponseObjectEnum> {
    match s {
        "list" => Some(iface_apple_pay::GetApplePayDomainsResponseObjectEnum::ListOp),
        _ => None,
    }
}

fn iface_apple_pay__get_apple_pay_domains__ok(body: String) -> Result<iface_apple_pay::GetApplePayDomainsResponse, crate::runtime::DispatchError> {
    let v: Value = match serde_json::from_str(&body) {
        Ok(v) => v,
        Err(e) => return Err(crate::runtime::DispatchError::Transport(format!("failed to decode response body as JSON: {e}"))),
    };
    match iface_apple_pay__get_apple_pay_domains_response__from_json(&v) {
        Some(x) => Ok(x),
        None => Err(crate::runtime::DispatchError::Transport("response body did not match the expected schema".to_string())),
    }
}

fn iface_apple_pay__get_apple_pay_domains__err(e: crate::runtime::DispatchError) -> String {
    match e {
        crate::runtime::DispatchError::Http { status, body } => format!("HTTP {status}: {body}"),
        crate::runtime::DispatchError::Transport(m) => m,
    }
}

fn iface_apple_pay__post_apple_pay_domains__ok(body: String) -> Result<iface_apple_pay::Domain, crate::runtime::DispatchError> {
    let v: Value = match serde_json::from_str(&body) {
        Ok(v) => v,
        Err(e) => return Err(crate::runtime::DispatchError::Transport(format!("failed to decode response body as JSON: {e}"))),
    };
    match iface_apple_pay__domain__from_json(&v) {
        Some(x) => Ok(x),
        None => Err(crate::runtime::DispatchError::Transport("response body did not match the expected schema".to_string())),
    }
}

fn iface_apple_pay__post_apple_pay_domains__err(e: crate::runtime::DispatchError) -> String {
    match e {
        crate::runtime::DispatchError::Http { status, body } => format!("HTTP {status}: {body}"),
        crate::runtime::DispatchError::Transport(m) => m,
    }
}

fn iface_apple_pay__get_apple_pay_domains_domain__ok(body: String) -> Result<iface_apple_pay::Domain, crate::runtime::DispatchError> {
    let v: Value = match serde_json::from_str(&body) {
        Ok(v) => v,
        Err(e) => return Err(crate::runtime::DispatchError::Transport(format!("failed to decode response body as JSON: {e}"))),
    };
    match iface_apple_pay__domain__from_json(&v) {
        Some(x) => Ok(x),
        None => Err(crate::runtime::DispatchError::Transport("response body did not match the expected schema".to_string())),
    }
}

fn iface_apple_pay__get_apple_pay_domains_domain__err(e: crate::runtime::DispatchError) -> String {
    match e {
        crate::runtime::DispatchError::Http { status, body } => format!("HTTP {status}: {body}"),
        crate::runtime::DispatchError::Transport(m) => m,
    }
}

fn iface_apple_pay__delete_apple_pay_domains_domain__ok(body: String) -> Result<iface_apple_pay::DeletedApplePayDomain, crate::runtime::DispatchError> {
    let v: Value = match serde_json::from_str(&body) {
        Ok(v) => v,
        Err(e) => return Err(crate::runtime::DispatchError::Transport(format!("failed to decode response body as JSON: {e}"))),
    };
    match iface_apple_pay__deleted_apple_pay_domain__from_json(&v) {
        Some(x) => Ok(x),
        None => Err(crate::runtime::DispatchError::Transport("response body did not match the expected schema".to_string())),
    }
}

fn iface_apple_pay__delete_apple_pay_domains_domain__err(e: crate::runtime::DispatchError) -> String {
    match e {
        crate::runtime::DispatchError::Http { status, body } => format!("HTTP {status}: {body}"),
        crate::runtime::DispatchError::Transport(m) => m,
    }
}

impl iface_apple_pay::Guest for crate::Component {
    fn get_apple_pay_domains(params: iface_apple_pay::GetApplePayDomainsParams) -> Result<iface_apple_pay::GetApplePayDomainsResponse, String> {
        let json = iface_apple_pay__get_apple_pay_domains_params__to_json(&params);
        match dispatch(&OP_APPLE_PAY_GET_APPLE_PAY_DOMAINS, json).and_then(iface_apple_pay__get_apple_pay_domains__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_apple_pay__get_apple_pay_domains__err(e)),
        }
    }
    fn post_apple_pay_domains(params: iface_apple_pay::PostApplePayDomainsParams) -> Result<iface_apple_pay::Domain, String> {
        let json = iface_apple_pay__post_apple_pay_domains_params__to_json(&params);
        match dispatch(&OP_APPLE_PAY_POST_APPLE_PAY_DOMAINS, json).and_then(iface_apple_pay__post_apple_pay_domains__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_apple_pay__post_apple_pay_domains__err(e)),
        }
    }
    fn get_apple_pay_domains_domain(params: iface_apple_pay::GetApplePayDomainsDomainParams) -> Result<iface_apple_pay::Domain, String> {
        let json = iface_apple_pay__get_apple_pay_domains_domain_params__to_json(&params);
        match dispatch(&OP_APPLE_PAY_GET_APPLE_PAY_DOMAINS_DOMAIN, json).and_then(iface_apple_pay__get_apple_pay_domains_domain__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_apple_pay__get_apple_pay_domains_domain__err(e)),
        }
    }
    fn delete_apple_pay_domains_domain(params: iface_apple_pay::DeleteApplePayDomainsDomainParams) -> Result<iface_apple_pay::DeletedApplePayDomain, String> {
        let json = iface_apple_pay__delete_apple_pay_domains_domain_params__to_json(&params);
        match dispatch(&OP_APPLE_PAY_DELETE_APPLE_PAY_DOMAINS_DOMAIN, json).and_then(iface_apple_pay__delete_apple_pay_domains_domain__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_apple_pay__delete_apple_pay_domains_domain__err(e)),
        }
    }
}
