// AUTOGENERATED by openapi-bindgen. Do not edit by hand.

use crate::runtime::{dispatch, AuthApply, AuthKind, FieldLocation, FieldSpec, OpSpec};
use crate::exports::autostamp::sendgrid::contacts_api_lists as iface_contacts_api_lists;
use serde_json::{Map, Value};

const OP_CONTACTS_API_LISTS_GET_CONTACTDB_LISTS: OpSpec = OpSpec {
    method: "GET",
    path_template: "/contactdb/lists",
    fields: &[
        FieldSpec { snake: "on_behalf_of", wire: "on-behalf-of", location: FieldLocation::Header },
    ],
    auth: &[
        AuthApply { secret_key: "Authorization", kind: AuthKind::ApiKeyHeader("Authorization") },
    ],
};

const OP_CONTACTS_API_LISTS_POST_CONTACTDB_LISTS: OpSpec = OpSpec {
    method: "POST",
    path_template: "/contactdb/lists",
    fields: &[
        FieldSpec { snake: "on_behalf_of", wire: "on-behalf-of", location: FieldLocation::Header },
        FieldSpec { snake: "name", wire: "name", location: FieldLocation::Body },
    ],
    auth: &[
        AuthApply { secret_key: "Authorization", kind: AuthKind::ApiKeyHeader("Authorization") },
    ],
};

const OP_CONTACTS_API_LISTS_DELETE_CONTACTDB_LISTS: OpSpec = OpSpec {
    method: "DELETE",
    path_template: "/contactdb/lists",
    fields: &[
        FieldSpec { snake: "on_behalf_of", wire: "on-behalf-of", location: FieldLocation::Header },
        FieldSpec { snake: "body", wire: "body", location: FieldLocation::Body },
    ],
    auth: &[
        AuthApply { secret_key: "Authorization", kind: AuthKind::ApiKeyHeader("Authorization") },
    ],
};

const OP_CONTACTS_API_LISTS_GET_CONTACTDB_LISTS_LIST_ID: OpSpec = OpSpec {
    method: "GET",
    path_template: "/contactdb/lists/{list_id}",
    fields: &[
        FieldSpec { snake: "list_id", wire: "list_id", location: FieldLocation::Path },
        FieldSpec { snake: "list_id_v2", wire: "list_id", location: FieldLocation::Query },
        FieldSpec { snake: "on_behalf_of", wire: "on-behalf-of", location: FieldLocation::Header },
    ],
    auth: &[
        AuthApply { secret_key: "Authorization", kind: AuthKind::ApiKeyHeader("Authorization") },
    ],
};

const OP_CONTACTS_API_LISTS_PATCH_CONTACTDB_LISTS_LIST_ID: OpSpec = OpSpec {
    method: "PATCH",
    path_template: "/contactdb/lists/{list_id}",
    fields: &[
        FieldSpec { snake: "list_id", wire: "list_id", location: FieldLocation::Path },
        FieldSpec { snake: "list_id_v2", wire: "list_id", location: FieldLocation::Query },
        FieldSpec { snake: "on_behalf_of", wire: "on-behalf-of", location: FieldLocation::Header },
        FieldSpec { snake: "name", wire: "name", location: FieldLocation::Body },
    ],
    auth: &[
        AuthApply { secret_key: "Authorization", kind: AuthKind::ApiKeyHeader("Authorization") },
    ],
};

const OP_CONTACTS_API_LISTS_DELETE_CONTACTDB_LISTS_LIST_ID: OpSpec = OpSpec {
    method: "DELETE",
    path_template: "/contactdb/lists/{list_id}",
    fields: &[
        FieldSpec { snake: "list_id", wire: "list_id", location: FieldLocation::Path },
        FieldSpec { snake: "delete_contacts", wire: "delete_contacts", location: FieldLocation::Query },
        FieldSpec { snake: "on_behalf_of", wire: "on-behalf-of", location: FieldLocation::Header },
        FieldSpec { snake: "body", wire: "body", location: FieldLocation::Body },
    ],
    auth: &[
        AuthApply { secret_key: "Authorization", kind: AuthKind::ApiKeyHeader("Authorization") },
    ],
};

const OP_CONTACTS_API_LISTS_GET_CONTACTDB_LISTS_LIST_ID_RECIPIENTS: OpSpec = OpSpec {
    method: "GET",
    path_template: "/contactdb/lists/{list_id}/recipients",
    fields: &[
        FieldSpec { snake: "list_id", wire: "list_id", location: FieldLocation::Path },
        FieldSpec { snake: "page", wire: "page", location: FieldLocation::Query },
        FieldSpec { snake: "page_size", wire: "page_size", location: FieldLocation::Query },
        FieldSpec { snake: "list_id_v2", wire: "list_id", location: FieldLocation::Query },
        FieldSpec { snake: "on_behalf_of", wire: "on-behalf-of", location: FieldLocation::Header },
    ],
    auth: &[
        AuthApply { secret_key: "Authorization", kind: AuthKind::ApiKeyHeader("Authorization") },
    ],
};

const OP_CONTACTS_API_LISTS_POST_CONTACTDB_LISTS_LIST_ID_RECIPIENTS: OpSpec = OpSpec {
    method: "POST",
    path_template: "/contactdb/lists/{list_id}/recipients",
    fields: &[
        FieldSpec { snake: "list_id", wire: "list_id", location: FieldLocation::Path },
        FieldSpec { snake: "on_behalf_of", wire: "on-behalf-of", location: FieldLocation::Header },
        FieldSpec { snake: "body", wire: "body", location: FieldLocation::Body },
    ],
    auth: &[
        AuthApply { secret_key: "Authorization", kind: AuthKind::ApiKeyHeader("Authorization") },
    ],
};

const OP_CONTACTS_API_LISTS_POST_CONTACTDB_LISTS_LIST_ID_RECIPIENTS_RECIPIENT_ID: OpSpec = OpSpec {
    method: "POST",
    path_template: "/contactdb/lists/{list_id}/recipients/{recipient_id}",
    fields: &[
        FieldSpec { snake: "list_id", wire: "list_id", location: FieldLocation::Path },
        FieldSpec { snake: "recipient_id", wire: "recipient_id", location: FieldLocation::Path },
        FieldSpec { snake: "on_behalf_of", wire: "on-behalf-of", location: FieldLocation::Header },
    ],
    auth: &[
        AuthApply { secret_key: "Authorization", kind: AuthKind::ApiKeyHeader("Authorization") },
    ],
};

const OP_CONTACTS_API_LISTS_DELETE_CONTACTDB_LISTS_LIST_ID_RECIPIENTS_RECIPIENT_ID: OpSpec = OpSpec {
    method: "DELETE",
    path_template: "/contactdb/lists/{list_id}/recipients/{recipient_id}",
    fields: &[
        FieldSpec { snake: "list_id", wire: "list_id", location: FieldLocation::Path },
        FieldSpec { snake: "recipient_id", wire: "recipient_id", location: FieldLocation::Path },
        FieldSpec { snake: "list_id_v2", wire: "list_id", location: FieldLocation::Query },
        FieldSpec { snake: "recipient_id_v2", wire: "recipient_id", location: FieldLocation::Query },
        FieldSpec { snake: "on_behalf_of", wire: "on-behalf-of", location: FieldLocation::Header },
        FieldSpec { snake: "body", wire: "body", location: FieldLocation::Body },
    ],
    auth: &[
        AuthApply { secret_key: "Authorization", kind: AuthKind::ApiKeyHeader("Authorization") },
    ],
};

fn iface_contacts_api_lists__contactdb_custom_field_with_id_value_type_op_enum__to_str(e: &iface_contacts_api_lists::ContactdbCustomFieldWithIdValueTypeOpEnum) -> &'static str {
    match e {
        iface_contacts_api_lists::ContactdbCustomFieldWithIdValueTypeOpEnum::Date => "date",
        iface_contacts_api_lists::ContactdbCustomFieldWithIdValueTypeOpEnum::Text => "text",
        iface_contacts_api_lists::ContactdbCustomFieldWithIdValueTypeOpEnum::Number => "number",
    }
}

fn iface_contacts_api_lists__get_contactdb_lists_response__to_json(p: &iface_contacts_api_lists::GetContactdbListsResponse) -> Value {
    let mut m = Map::new();
    m.insert("lists".into(), Value::Array((&p.lists).iter().map(|v| iface_contacts_api_lists__contactdb_list__to_json(v)).collect()));
    Value::Object(m)
}

fn iface_contacts_api_lists__contactdb_list__to_json(p: &iface_contacts_api_lists::ContactdbList) -> Value {
    let mut m = Map::new();
    m.insert("id".into(), Value::Number(serde_json::Number::from(*(&p.id))));
    m.insert("name".into(), Value::String((&p.name).clone()));
    m.insert("recipient_count".into(), Value::Number(serde_json::Number::from(*(&p.recipient_count))));
    Value::Object(m)
}

fn iface_contacts_api_lists__patch_contactdb_lists_list_id_response__to_json(p: &iface_contacts_api_lists::PatchContactdbListsListIdResponse) -> Value {
    let mut m = Map::new();
    m.insert("id".into(), match (&p.id) { Some(v) => Value::Number(serde_json::Number::from(*(v))), None => Value::Null });
    m.insert("name".into(), match (&p.name) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("recipient_count".into(), match (&p.recipient_count) { Some(v) => Value::Number(serde_json::Number::from(*(v))), None => Value::Null });
    Value::Object(m)
}

fn iface_contacts_api_lists__get_contactdb_lists_list_id_recipients_response__to_json(p: &iface_contacts_api_lists::GetContactdbListsListIdRecipientsResponse) -> Value {
    let mut m = Map::new();
    m.insert("recipients".into(), match (&p.recipients) { Some(v) => Value::Array((v).iter().map(|v| iface_contacts_api_lists__contactdb_recipient__to_json(v)).collect()), None => Value::Null });
    Value::Object(m)
}

fn iface_contacts_api_lists__contactdb_recipient__to_json(p: &iface_contacts_api_lists::ContactdbRecipient) -> Value {
    let mut m = Map::new();
    m.insert("recipients".into(), match (&p.recipients) { Some(v) => Value::Array((v).iter().map(|v| iface_contacts_api_lists__contactdb_recipient_recipients_item__to_json(v)).collect()), None => Value::Null });
    Value::Object(m)
}

fn iface_contacts_api_lists__contactdb_recipient_recipients_item__to_json(p: &iface_contacts_api_lists::ContactdbRecipientRecipientsItem) -> Value {
    let mut m = Map::new();
    m.insert("created_at".into(), match (&p.created_at) { Some(v) => serde_json::Number::from_f64(*(v)).map(Value::Number).unwrap_or(Value::Null), None => Value::Null });
    m.insert("custom_fields".into(), match (&p.custom_fields) { Some(v) => Value::Array((v).iter().map(|v| iface_contacts_api_lists__contactdb_custom_field_with_id_value__to_json(v)).collect()), None => Value::Null });
    m.insert("email".into(), Value::String((&p.email).clone()));
    m.insert("first_name".into(), match (&p.first_name) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("id".into(), match (&p.id) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("last_clicked".into(), match (&p.last_clicked) { Some(v) => serde_json::Number::from_f64(*(v)).map(Value::Number).unwrap_or(Value::Null), None => Value::Null });
    m.insert("last_emailed".into(), match (&p.last_emailed) { Some(v) => serde_json::Number::from_f64(*(v)).map(Value::Number).unwrap_or(Value::Null), None => Value::Null });
    m.insert("last_name".into(), match (&p.last_name) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("last_opened".into(), match (&p.last_opened) { Some(v) => serde_json::Number::from_f64(*(v)).map(Value::Number).unwrap_or(Value::Null), None => Value::Null });
    m.insert("updated_at".into(), match (&p.updated_at) { Some(v) => serde_json::Number::from_f64(*(v)).map(Value::Number).unwrap_or(Value::Null), None => Value::Null });
    Value::Object(m)
}

fn iface_contacts_api_lists__contactdb_custom_field_with_id_value__to_json(p: &iface_contacts_api_lists::ContactdbCustomFieldWithIdValue) -> Value {
    let mut m = Map::new();
    m.insert("name".into(), match (&p.name) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("type".into(), match (&p.type_op) { Some(v) => Value::String(iface_contacts_api_lists__contactdb_custom_field_with_id_value_type_op_enum__to_str(v).into()), None => Value::Null });
    m.insert("id".into(), match (&p.id) { Some(v) => serde_json::Number::from_f64(*(v)).map(Value::Number).unwrap_or(Value::Null), None => Value::Null });
    m.insert("value".into(), match (&p.value) { Some(v) => Value::String((v).clone()), None => Value::Null });
    Value::Object(m)
}

fn iface_contacts_api_lists__get_contactdb_lists_params__to_json(p: &iface_contacts_api_lists::GetContactdbListsParams) -> Value {
    let mut m = Map::new();
    m.insert("on_behalf_of".into(), match (&p.on_behalf_of) { Some(v) => Value::String((v).clone()), None => Value::Null });
    Value::Object(m)
}

fn iface_contacts_api_lists__post_contactdb_lists_params__to_json(p: &iface_contacts_api_lists::PostContactdbListsParams) -> Value {
    let mut m = Map::new();
    m.insert("on_behalf_of".into(), match (&p.on_behalf_of) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("name".into(), Value::String((&p.name).clone()));
    Value::Object(m)
}

fn iface_contacts_api_lists__delete_contactdb_lists_params__to_json(p: &iface_contacts_api_lists::DeleteContactdbListsParams) -> Value {
    let mut m = Map::new();
    m.insert("on_behalf_of".into(), match (&p.on_behalf_of) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("body".into(), match (&p.body) { Some(v) => Value::Array((v).iter().map(|v| Value::Number(serde_json::Number::from(*(v)))).collect()), None => Value::Null });
    Value::Object(m)
}

fn iface_contacts_api_lists__get_contactdb_lists_list_id_params__to_json(p: &iface_contacts_api_lists::GetContactdbListsListIdParams) -> Value {
    let mut m = Map::new();
    m.insert("list_id".into(), Value::String((&p.list_id).clone()));
    m.insert("list_id_v2".into(), match (&p.list_id_v2) { Some(v) => Value::Number(serde_json::Number::from(*(v))), None => Value::Null });
    m.insert("on_behalf_of".into(), match (&p.on_behalf_of) { Some(v) => Value::String((v).clone()), None => Value::Null });
    Value::Object(m)
}

fn iface_contacts_api_lists__patch_contactdb_lists_list_id_params__to_json(p: &iface_contacts_api_lists::PatchContactdbListsListIdParams) -> Value {
    let mut m = Map::new();
    m.insert("list_id".into(), Value::String((&p.list_id).clone()));
    m.insert("list_id_v2".into(), Value::Number(serde_json::Number::from(*(&p.list_id_v2))));
    m.insert("on_behalf_of".into(), match (&p.on_behalf_of) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("name".into(), Value::String((&p.name).clone()));
    Value::Object(m)
}

fn iface_contacts_api_lists__delete_contactdb_lists_list_id_params__to_json(p: &iface_contacts_api_lists::DeleteContactdbListsListIdParams) -> Value {
    let mut m = Map::new();
    m.insert("list_id".into(), Value::String((&p.list_id).clone()));
    m.insert("delete_contacts".into(), match (&p.delete_contacts) { Some(v) => Value::Bool(*(v)), None => Value::Null });
    m.insert("on_behalf_of".into(), match (&p.on_behalf_of) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("body".into(), match (&p.body) { Some(v) => Value::String((v).clone()), None => Value::Null });
    Value::Object(m)
}

fn iface_contacts_api_lists__get_contactdb_lists_list_id_recipients_params__to_json(p: &iface_contacts_api_lists::GetContactdbListsListIdRecipientsParams) -> Value {
    let mut m = Map::new();
    m.insert("list_id".into(), Value::String((&p.list_id).clone()));
    m.insert("page".into(), match (&p.page) { Some(v) => Value::Number(serde_json::Number::from(*(v))), None => Value::Null });
    m.insert("page_size".into(), match (&p.page_size) { Some(v) => Value::Number(serde_json::Number::from(*(v))), None => Value::Null });
    m.insert("list_id_v2".into(), Value::Number(serde_json::Number::from(*(&p.list_id_v2))));
    m.insert("on_behalf_of".into(), match (&p.on_behalf_of) { Some(v) => Value::String((v).clone()), None => Value::Null });
    Value::Object(m)
}

fn iface_contacts_api_lists__post_contactdb_lists_list_id_recipients_params__to_json(p: &iface_contacts_api_lists::PostContactdbListsListIdRecipientsParams) -> Value {
    let mut m = Map::new();
    m.insert("list_id".into(), Value::String((&p.list_id).clone()));
    m.insert("on_behalf_of".into(), match (&p.on_behalf_of) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("body".into(), match (&p.body) { Some(v) => Value::Array((v).iter().map(|v| Value::Number(serde_json::Number::from(*(v)))).collect()), None => Value::Null });
    Value::Object(m)
}

fn iface_contacts_api_lists__post_contactdb_lists_list_id_recipients_recipient_id_params__to_json(p: &iface_contacts_api_lists::PostContactdbListsListIdRecipientsRecipientIdParams) -> Value {
    let mut m = Map::new();
    m.insert("list_id".into(), Value::String((&p.list_id).clone()));
    m.insert("recipient_id".into(), Value::String((&p.recipient_id).clone()));
    m.insert("on_behalf_of".into(), match (&p.on_behalf_of) { Some(v) => Value::String((v).clone()), None => Value::Null });
    Value::Object(m)
}

fn iface_contacts_api_lists__delete_contactdb_lists_list_id_recipients_recipient_id_params__to_json(p: &iface_contacts_api_lists::DeleteContactdbListsListIdRecipientsRecipientIdParams) -> Value {
    let mut m = Map::new();
    m.insert("list_id".into(), Value::String((&p.list_id).clone()));
    m.insert("recipient_id".into(), Value::String((&p.recipient_id).clone()));
    m.insert("list_id_v2".into(), Value::Number(serde_json::Number::from(*(&p.list_id_v2))));
    m.insert("recipient_id_v2".into(), Value::Number(serde_json::Number::from(*(&p.recipient_id_v2))));
    m.insert("on_behalf_of".into(), match (&p.on_behalf_of) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("body".into(), match (&p.body) { Some(v) => Value::String((v).clone()), None => Value::Null });
    Value::Object(m)
}

fn iface_contacts_api_lists__get_contactdb_lists_response__from_json(v: &Value) -> Option<iface_contacts_api_lists::GetContactdbListsResponse> {
    let m = v.as_object()?;
    Some(iface_contacts_api_lists::GetContactdbListsResponse {
        lists: m.get("lists").and_then(|v| (v).as_array().map(|a| a.iter().filter_map(|x| iface_contacts_api_lists__contactdb_list__from_json(x)).collect())).unwrap_or_default(),
    })
}

fn iface_contacts_api_lists__contactdb_list__from_json(v: &Value) -> Option<iface_contacts_api_lists::ContactdbList> {
    let m = v.as_object()?;
    Some(iface_contacts_api_lists::ContactdbList {
        id: m.get("id").and_then(|v| (v).as_i64().map(|n| n as i32)).unwrap_or_default(),
        name: m.get("name").and_then(|v| (v).as_str().map(|s| s.to_string())).unwrap_or_default(),
        recipient_count: m.get("recipient_count").and_then(|v| (v).as_i64().map(|n| n as i32)).unwrap_or_default(),
    })
}

fn iface_contacts_api_lists__patch_contactdb_lists_list_id_response__from_json(v: &Value) -> Option<iface_contacts_api_lists::PatchContactdbListsListIdResponse> {
    let m = v.as_object()?;
    Some(iface_contacts_api_lists::PatchContactdbListsListIdResponse {
        id: m.get("id").filter(|v| !v.is_null()).and_then(|v| (v).as_i64().map(|n| n as i32)),
        name: m.get("name").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        recipient_count: m.get("recipient_count").filter(|v| !v.is_null()).and_then(|v| (v).as_i64().map(|n| n as i32)),
    })
}

fn iface_contacts_api_lists__get_contactdb_lists_list_id_recipients_response__from_json(v: &Value) -> Option<iface_contacts_api_lists::GetContactdbListsListIdRecipientsResponse> {
    let m = v.as_object()?;
    Some(iface_contacts_api_lists::GetContactdbListsListIdRecipientsResponse {
        recipients: m.get("recipients").filter(|v| !v.is_null()).and_then(|v| (v).as_array().map(|a| a.iter().filter_map(|x| iface_contacts_api_lists__contactdb_recipient__from_json(x)).collect())),
    })
}

fn iface_contacts_api_lists__contactdb_recipient__from_json(v: &Value) -> Option<iface_contacts_api_lists::ContactdbRecipient> {
    let m = v.as_object()?;
    Some(iface_contacts_api_lists::ContactdbRecipient {
        recipients: m.get("recipients").filter(|v| !v.is_null()).and_then(|v| (v).as_array().map(|a| a.iter().filter_map(|x| iface_contacts_api_lists__contactdb_recipient_recipients_item__from_json(x)).collect())),
    })
}

fn iface_contacts_api_lists__contactdb_recipient_recipients_item__from_json(v: &Value) -> Option<iface_contacts_api_lists::ContactdbRecipientRecipientsItem> {
    let m = v.as_object()?;
    Some(iface_contacts_api_lists::ContactdbRecipientRecipientsItem {
        created_at: m.get("created_at").filter(|v| !v.is_null()).and_then(|v| (v).as_f64()),
        custom_fields: m.get("custom_fields").filter(|v| !v.is_null()).and_then(|v| (v).as_array().map(|a| a.iter().filter_map(|x| iface_contacts_api_lists__contactdb_custom_field_with_id_value__from_json(x)).collect())),
        email: m.get("email").and_then(|v| (v).as_str().map(|s| s.to_string())).unwrap_or_default(),
        first_name: m.get("first_name").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        id: m.get("id").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        last_clicked: m.get("last_clicked").filter(|v| !v.is_null()).and_then(|v| (v).as_f64()),
        last_emailed: m.get("last_emailed").filter(|v| !v.is_null()).and_then(|v| (v).as_f64()),
        last_name: m.get("last_name").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        last_opened: m.get("last_opened").filter(|v| !v.is_null()).and_then(|v| (v).as_f64()),
        updated_at: m.get("updated_at").filter(|v| !v.is_null()).and_then(|v| (v).as_f64()),
    })
}

fn iface_contacts_api_lists__contactdb_custom_field_with_id_value__from_json(v: &Value) -> Option<iface_contacts_api_lists::ContactdbCustomFieldWithIdValue> {
    let m = v.as_object()?;
    Some(iface_contacts_api_lists::ContactdbCustomFieldWithIdValue {
        name: m.get("name").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        type_op: m.get("type").filter(|v| !v.is_null()).and_then(|v| (v).as_str().and_then(iface_contacts_api_lists__contactdb_custom_field_with_id_value_type_op_enum__from_str)),
        id: m.get("id").filter(|v| !v.is_null()).and_then(|v| (v).as_f64()),
        value: m.get("value").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
    })
}

fn iface_contacts_api_lists__contactdb_custom_field_with_id_value_type_op_enum__from_str(s: &str) -> Option<iface_contacts_api_lists::ContactdbCustomFieldWithIdValueTypeOpEnum> {
    match s {
        "date" => Some(iface_contacts_api_lists::ContactdbCustomFieldWithIdValueTypeOpEnum::Date),
        "text" => Some(iface_contacts_api_lists::ContactdbCustomFieldWithIdValueTypeOpEnum::Text),
        "number" => Some(iface_contacts_api_lists::ContactdbCustomFieldWithIdValueTypeOpEnum::Number),
        _ => None,
    }
}

fn iface_contacts_api_lists__get_contactdb_lists__ok(body: String) -> Result<iface_contacts_api_lists::GetContactdbListsResponse, crate::runtime::DispatchError> {
    let v: Value = match serde_json::from_str(&body) {
        Ok(v) => v,
        Err(e) => return Err(crate::runtime::DispatchError::Transport(format!("failed to decode response body as JSON: {e}"))),
    };
    match iface_contacts_api_lists__get_contactdb_lists_response__from_json(&v) {
        Some(x) => Ok(x),
        None => Err(crate::runtime::DispatchError::Transport("response body did not match the expected schema".to_string())),
    }
}

fn iface_contacts_api_lists__get_contactdb_lists__err(e: crate::runtime::DispatchError) -> String {
    match e {
        crate::runtime::DispatchError::Http { status, body } => format!("HTTP {status}: {body}"),
        crate::runtime::DispatchError::Transport(m) => m,
    }
}

fn iface_contacts_api_lists__post_contactdb_lists__ok(body: String) -> Result<iface_contacts_api_lists::ContactdbList, crate::runtime::DispatchError> {
    let v: Value = match serde_json::from_str(&body) {
        Ok(v) => v,
        Err(e) => return Err(crate::runtime::DispatchError::Transport(format!("failed to decode response body as JSON: {e}"))),
    };
    match iface_contacts_api_lists__contactdb_list__from_json(&v) {
        Some(x) => Ok(x),
        None => Err(crate::runtime::DispatchError::Transport("response body did not match the expected schema".to_string())),
    }
}

fn iface_contacts_api_lists__post_contactdb_lists__err(e: crate::runtime::DispatchError) -> iface_contacts_api_lists::PostContactdbListsError {
    match e {
        crate::runtime::DispatchError::Http { status, body } => match status {
            400u16 => iface_contacts_api_lists::PostContactdbListsError::BadRequest(body),
            401u16 => iface_contacts_api_lists::PostContactdbListsError::Unauthorized(body),
            _ => iface_contacts_api_lists::PostContactdbListsError::Other(body),
        },
        crate::runtime::DispatchError::Transport(m) => iface_contacts_api_lists::PostContactdbListsError::Other(m),
    }
}

fn iface_contacts_api_lists__delete_contactdb_lists__ok(body: String) -> Result<String, crate::runtime::DispatchError> {
    Ok(body)
}

fn iface_contacts_api_lists__delete_contactdb_lists__err(e: crate::runtime::DispatchError) -> iface_contacts_api_lists::DeleteContactdbListsError {
    match e {
        crate::runtime::DispatchError::Http { status, body } => match status {
            400u16 => iface_contacts_api_lists::DeleteContactdbListsError::BadRequest(body),
            401u16 => iface_contacts_api_lists::DeleteContactdbListsError::Unauthorized(body),
            _ => iface_contacts_api_lists::DeleteContactdbListsError::Other(body),
        },
        crate::runtime::DispatchError::Transport(m) => iface_contacts_api_lists::DeleteContactdbListsError::Other(m),
    }
}

fn iface_contacts_api_lists__get_contactdb_lists_list_id__ok(body: String) -> Result<iface_contacts_api_lists::ContactdbList, crate::runtime::DispatchError> {
    let v: Value = match serde_json::from_str(&body) {
        Ok(v) => v,
        Err(e) => return Err(crate::runtime::DispatchError::Transport(format!("failed to decode response body as JSON: {e}"))),
    };
    match iface_contacts_api_lists__contactdb_list__from_json(&v) {
        Some(x) => Ok(x),
        None => Err(crate::runtime::DispatchError::Transport("response body did not match the expected schema".to_string())),
    }
}

fn iface_contacts_api_lists__get_contactdb_lists_list_id__err(e: crate::runtime::DispatchError) -> iface_contacts_api_lists::GetContactdbListsListIdError {
    match e {
        crate::runtime::DispatchError::Http { status, body } => match status {
            400u16 => iface_contacts_api_lists::GetContactdbListsListIdError::BadRequest(body),
            401u16 => iface_contacts_api_lists::GetContactdbListsListIdError::Unauthorized(body),
            404u16 => iface_contacts_api_lists::GetContactdbListsListIdError::NotFound(body),
            _ => iface_contacts_api_lists::GetContactdbListsListIdError::Other(body),
        },
        crate::runtime::DispatchError::Transport(m) => iface_contacts_api_lists::GetContactdbListsListIdError::Other(m),
    }
}

fn iface_contacts_api_lists__patch_contactdb_lists_list_id__ok(body: String) -> Result<iface_contacts_api_lists::PatchContactdbListsListIdResponse, crate::runtime::DispatchError> {
    let v: Value = match serde_json::from_str(&body) {
        Ok(v) => v,
        Err(e) => return Err(crate::runtime::DispatchError::Transport(format!("failed to decode response body as JSON: {e}"))),
    };
    match iface_contacts_api_lists__patch_contactdb_lists_list_id_response__from_json(&v) {
        Some(x) => Ok(x),
        None => Err(crate::runtime::DispatchError::Transport("response body did not match the expected schema".to_string())),
    }
}

fn iface_contacts_api_lists__patch_contactdb_lists_list_id__err(e: crate::runtime::DispatchError) -> iface_contacts_api_lists::PatchContactdbListsListIdError {
    match e {
        crate::runtime::DispatchError::Http { status, body } => match status {
            400u16 => iface_contacts_api_lists::PatchContactdbListsListIdError::BadRequest(body),
            404u16 => iface_contacts_api_lists::PatchContactdbListsListIdError::NotFound(body),
            _ => iface_contacts_api_lists::PatchContactdbListsListIdError::Other(body),
        },
        crate::runtime::DispatchError::Transport(m) => iface_contacts_api_lists::PatchContactdbListsListIdError::Other(m),
    }
}

fn iface_contacts_api_lists__delete_contactdb_lists_list_id__ok(body: String) -> Result<String, crate::runtime::DispatchError> {
    Ok(body)
}

fn iface_contacts_api_lists__delete_contactdb_lists_list_id__err(e: crate::runtime::DispatchError) -> iface_contacts_api_lists::DeleteContactdbListsListIdError {
    match e {
        crate::runtime::DispatchError::Http { status, body } => match status {
            400u16 => iface_contacts_api_lists::DeleteContactdbListsListIdError::BadRequest(body),
            401u16 => iface_contacts_api_lists::DeleteContactdbListsListIdError::Unauthorized(body),
            404u16 => iface_contacts_api_lists::DeleteContactdbListsListIdError::NotFound(body),
            _ => iface_contacts_api_lists::DeleteContactdbListsListIdError::Other(body),
        },
        crate::runtime::DispatchError::Transport(m) => iface_contacts_api_lists::DeleteContactdbListsListIdError::Other(m),
    }
}

fn iface_contacts_api_lists__get_contactdb_lists_list_id_recipients__ok(body: String) -> Result<iface_contacts_api_lists::GetContactdbListsListIdRecipientsResponse, crate::runtime::DispatchError> {
    let v: Value = match serde_json::from_str(&body) {
        Ok(v) => v,
        Err(e) => return Err(crate::runtime::DispatchError::Transport(format!("failed to decode response body as JSON: {e}"))),
    };
    match iface_contacts_api_lists__get_contactdb_lists_list_id_recipients_response__from_json(&v) {
        Some(x) => Ok(x),
        None => Err(crate::runtime::DispatchError::Transport("response body did not match the expected schema".to_string())),
    }
}

fn iface_contacts_api_lists__get_contactdb_lists_list_id_recipients__err(e: crate::runtime::DispatchError) -> iface_contacts_api_lists::GetContactdbListsListIdRecipientsError {
    match e {
        crate::runtime::DispatchError::Http { status, body } => match status {
            400u16 => iface_contacts_api_lists::GetContactdbListsListIdRecipientsError::BadRequest(body),
            404u16 => iface_contacts_api_lists::GetContactdbListsListIdRecipientsError::NotFound(body),
            _ => iface_contacts_api_lists::GetContactdbListsListIdRecipientsError::Other(body),
        },
        crate::runtime::DispatchError::Transport(m) => iface_contacts_api_lists::GetContactdbListsListIdRecipientsError::Other(m),
    }
}

fn iface_contacts_api_lists__post_contactdb_lists_list_id_recipients__ok(body: String) -> Result<String, crate::runtime::DispatchError> {
    Ok(body)
}

fn iface_contacts_api_lists__post_contactdb_lists_list_id_recipients__err(e: crate::runtime::DispatchError) -> iface_contacts_api_lists::PostContactdbListsListIdRecipientsError {
    match e {
        crate::runtime::DispatchError::Http { status, body } => match status {
            400u16 => iface_contacts_api_lists::PostContactdbListsListIdRecipientsError::BadRequest(body),
            401u16 => iface_contacts_api_lists::PostContactdbListsListIdRecipientsError::Unauthorized(body),
            404u16 => iface_contacts_api_lists::PostContactdbListsListIdRecipientsError::NotFound(body),
            _ => iface_contacts_api_lists::PostContactdbListsListIdRecipientsError::Other(body),
        },
        crate::runtime::DispatchError::Transport(m) => iface_contacts_api_lists::PostContactdbListsListIdRecipientsError::Other(m),
    }
}

fn iface_contacts_api_lists__post_contactdb_lists_list_id_recipients_recipient_id__ok(body: String) -> Result<String, crate::runtime::DispatchError> {
    Ok(body)
}

fn iface_contacts_api_lists__post_contactdb_lists_list_id_recipients_recipient_id__err(e: crate::runtime::DispatchError) -> iface_contacts_api_lists::PostContactdbListsListIdRecipientsRecipientIdError {
    match e {
        crate::runtime::DispatchError::Http { status, body } => match status {
            400u16 => iface_contacts_api_lists::PostContactdbListsListIdRecipientsRecipientIdError::BadRequest(body),
            401u16 => iface_contacts_api_lists::PostContactdbListsListIdRecipientsRecipientIdError::Unauthorized(body),
            404u16 => iface_contacts_api_lists::PostContactdbListsListIdRecipientsRecipientIdError::NotFound(body),
            _ => iface_contacts_api_lists::PostContactdbListsListIdRecipientsRecipientIdError::Other(body),
        },
        crate::runtime::DispatchError::Transport(m) => iface_contacts_api_lists::PostContactdbListsListIdRecipientsRecipientIdError::Other(m),
    }
}

fn iface_contacts_api_lists__delete_contactdb_lists_list_id_recipients_recipient_id__ok(body: String) -> Result<String, crate::runtime::DispatchError> {
    Ok(body)
}

fn iface_contacts_api_lists__delete_contactdb_lists_list_id_recipients_recipient_id__err(e: crate::runtime::DispatchError) -> iface_contacts_api_lists::DeleteContactdbListsListIdRecipientsRecipientIdError {
    match e {
        crate::runtime::DispatchError::Http { status, body } => match status {
            400u16 => iface_contacts_api_lists::DeleteContactdbListsListIdRecipientsRecipientIdError::BadRequest(body),
            401u16 => iface_contacts_api_lists::DeleteContactdbListsListIdRecipientsRecipientIdError::Unauthorized(body),
            404u16 => iface_contacts_api_lists::DeleteContactdbListsListIdRecipientsRecipientIdError::NotFound(body),
            _ => iface_contacts_api_lists::DeleteContactdbListsListIdRecipientsRecipientIdError::Other(body),
        },
        crate::runtime::DispatchError::Transport(m) => iface_contacts_api_lists::DeleteContactdbListsListIdRecipientsRecipientIdError::Other(m),
    }
}

impl iface_contacts_api_lists::Guest for crate::Component {
    fn get_contactdb_lists(params: iface_contacts_api_lists::GetContactdbListsParams) -> Result<iface_contacts_api_lists::GetContactdbListsResponse, String> {
        let json = iface_contacts_api_lists__get_contactdb_lists_params__to_json(&params);
        match dispatch(&OP_CONTACTS_API_LISTS_GET_CONTACTDB_LISTS, json).and_then(iface_contacts_api_lists__get_contactdb_lists__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_contacts_api_lists__get_contactdb_lists__err(e)),
        }
    }
    fn post_contactdb_lists(params: iface_contacts_api_lists::PostContactdbListsParams) -> Result<iface_contacts_api_lists::ContactdbList, iface_contacts_api_lists::PostContactdbListsError> {
        let json = iface_contacts_api_lists__post_contactdb_lists_params__to_json(&params);
        match dispatch(&OP_CONTACTS_API_LISTS_POST_CONTACTDB_LISTS, json).and_then(iface_contacts_api_lists__post_contactdb_lists__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_contacts_api_lists__post_contactdb_lists__err(e)),
        }
    }
    fn delete_contactdb_lists(params: iface_contacts_api_lists::DeleteContactdbListsParams) -> Result<String, iface_contacts_api_lists::DeleteContactdbListsError> {
        let json = iface_contacts_api_lists__delete_contactdb_lists_params__to_json(&params);
        match dispatch(&OP_CONTACTS_API_LISTS_DELETE_CONTACTDB_LISTS, json).and_then(iface_contacts_api_lists__delete_contactdb_lists__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_contacts_api_lists__delete_contactdb_lists__err(e)),
        }
    }
    fn get_contactdb_lists_list_id(params: iface_contacts_api_lists::GetContactdbListsListIdParams) -> Result<iface_contacts_api_lists::ContactdbList, iface_contacts_api_lists::GetContactdbListsListIdError> {
        let json = iface_contacts_api_lists__get_contactdb_lists_list_id_params__to_json(&params);
        match dispatch(&OP_CONTACTS_API_LISTS_GET_CONTACTDB_LISTS_LIST_ID, json).and_then(iface_contacts_api_lists__get_contactdb_lists_list_id__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_contacts_api_lists__get_contactdb_lists_list_id__err(e)),
        }
    }
    fn patch_contactdb_lists_list_id(params: iface_contacts_api_lists::PatchContactdbListsListIdParams) -> Result<iface_contacts_api_lists::PatchContactdbListsListIdResponse, iface_contacts_api_lists::PatchContactdbListsListIdError> {
        let json = iface_contacts_api_lists__patch_contactdb_lists_list_id_params__to_json(&params);
        match dispatch(&OP_CONTACTS_API_LISTS_PATCH_CONTACTDB_LISTS_LIST_ID, json).and_then(iface_contacts_api_lists__patch_contactdb_lists_list_id__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_contacts_api_lists__patch_contactdb_lists_list_id__err(e)),
        }
    }
    fn delete_contactdb_lists_list_id(params: iface_contacts_api_lists::DeleteContactdbListsListIdParams) -> Result<String, iface_contacts_api_lists::DeleteContactdbListsListIdError> {
        let json = iface_contacts_api_lists__delete_contactdb_lists_list_id_params__to_json(&params);
        match dispatch(&OP_CONTACTS_API_LISTS_DELETE_CONTACTDB_LISTS_LIST_ID, json).and_then(iface_contacts_api_lists__delete_contactdb_lists_list_id__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_contacts_api_lists__delete_contactdb_lists_list_id__err(e)),
        }
    }
    fn get_contactdb_lists_list_id_recipients(params: iface_contacts_api_lists::GetContactdbListsListIdRecipientsParams) -> Result<iface_contacts_api_lists::GetContactdbListsListIdRecipientsResponse, iface_contacts_api_lists::GetContactdbListsListIdRecipientsError> {
        let json = iface_contacts_api_lists__get_contactdb_lists_list_id_recipients_params__to_json(&params);
        match dispatch(&OP_CONTACTS_API_LISTS_GET_CONTACTDB_LISTS_LIST_ID_RECIPIENTS, json).and_then(iface_contacts_api_lists__get_contactdb_lists_list_id_recipients__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_contacts_api_lists__get_contactdb_lists_list_id_recipients__err(e)),
        }
    }
    fn post_contactdb_lists_list_id_recipients(params: iface_contacts_api_lists::PostContactdbListsListIdRecipientsParams) -> Result<String, iface_contacts_api_lists::PostContactdbListsListIdRecipientsError> {
        let json = iface_contacts_api_lists__post_contactdb_lists_list_id_recipients_params__to_json(&params);
        match dispatch(&OP_CONTACTS_API_LISTS_POST_CONTACTDB_LISTS_LIST_ID_RECIPIENTS, json).and_then(iface_contacts_api_lists__post_contactdb_lists_list_id_recipients__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_contacts_api_lists__post_contactdb_lists_list_id_recipients__err(e)),
        }
    }
    fn post_contactdb_lists_list_id_recipients_recipient_id(params: iface_contacts_api_lists::PostContactdbListsListIdRecipientsRecipientIdParams) -> Result<String, iface_contacts_api_lists::PostContactdbListsListIdRecipientsRecipientIdError> {
        let json = iface_contacts_api_lists__post_contactdb_lists_list_id_recipients_recipient_id_params__to_json(&params);
        match dispatch(&OP_CONTACTS_API_LISTS_POST_CONTACTDB_LISTS_LIST_ID_RECIPIENTS_RECIPIENT_ID, json).and_then(iface_contacts_api_lists__post_contactdb_lists_list_id_recipients_recipient_id__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_contacts_api_lists__post_contactdb_lists_list_id_recipients_recipient_id__err(e)),
        }
    }
    fn delete_contactdb_lists_list_id_recipients_recipient_id(params: iface_contacts_api_lists::DeleteContactdbListsListIdRecipientsRecipientIdParams) -> Result<String, iface_contacts_api_lists::DeleteContactdbListsListIdRecipientsRecipientIdError> {
        let json = iface_contacts_api_lists__delete_contactdb_lists_list_id_recipients_recipient_id_params__to_json(&params);
        match dispatch(&OP_CONTACTS_API_LISTS_DELETE_CONTACTDB_LISTS_LIST_ID_RECIPIENTS_RECIPIENT_ID, json).and_then(iface_contacts_api_lists__delete_contactdb_lists_list_id_recipients_recipient_id__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_contacts_api_lists__delete_contactdb_lists_list_id_recipients_recipient_id__err(e)),
        }
    }
}
