// AUTOGENERATED by openapi-bindgen. Do not edit by hand.

use crate::runtime::{dispatch, AuthApply, AuthKind, FieldLocation, FieldSpec, OpSpec};
use crate::exports::autostamp::zoom::common_area_phones as iface_common_area_phones;
use serde_json::{Map, Value};

const OP_COMMON_AREA_PHONES_LIST_COMMON_AREA_PHONES: OpSpec = OpSpec {
    method: "GET",
    path_template: "/phone/common_area_phones",
    fields: &[
        FieldSpec { snake: "page_size", wire: "page_size", location: FieldLocation::Query },
        FieldSpec { snake: "next_page_token", wire: "next_page_token", location: FieldLocation::Query },
    ],
    auth: &[
        AuthApply { secret_key: "OAuth", kind: AuthKind::Bearer },
    ],
};

const OP_COMMON_AREA_PHONES_ADD_COMMON_AREA_PHONE: OpSpec = OpSpec {
    method: "POST",
    path_template: "/phone/common_area_phones",
    fields: &[
        FieldSpec { snake: "description", wire: "description", location: FieldLocation::Body },
        FieldSpec { snake: "display_name", wire: "display_name", location: FieldLocation::Body },
        FieldSpec { snake: "extension_number", wire: "extension_number", location: FieldLocation::Body },
        FieldSpec { snake: "mac_address", wire: "mac_address", location: FieldLocation::Body },
        FieldSpec { snake: "model", wire: "model", location: FieldLocation::Body },
        FieldSpec { snake: "site_id", wire: "site_id", location: FieldLocation::Body },
        FieldSpec { snake: "time_zone", wire: "time_zone", location: FieldLocation::Body },
        FieldSpec { snake: "type", wire: "type", location: FieldLocation::Body },
    ],
    auth: &[
        AuthApply { secret_key: "OAuth", kind: AuthKind::Bearer },
    ],
};

const OP_COMMON_AREA_PHONES_GET_A_COMMON_AREA_PHONE: OpSpec = OpSpec {
    method: "GET",
    path_template: "/phone/common_area_phones/{common_area_phone_id}",
    fields: &[
        FieldSpec { snake: "common_area_phone_id", wire: "commonAreaPhoneId", location: FieldLocation::Path },
    ],
    auth: &[
        AuthApply { secret_key: "OAuth", kind: AuthKind::Bearer },
    ],
};

const OP_COMMON_AREA_PHONES_UPDATE_COMMON_AREA_PHONE: OpSpec = OpSpec {
    method: "PATCH",
    path_template: "/phone/common_area_phones/{common_area_phone_id}",
    fields: &[
        FieldSpec { snake: "common_area_phone_id", wire: "commonAreaPhoneId", location: FieldLocation::Path },
        FieldSpec { snake: "display_name", wire: "display_name", location: FieldLocation::Body },
        FieldSpec { snake: "extension_number", wire: "extension_number", location: FieldLocation::Body },
        FieldSpec { snake: "mac_address", wire: "mac_address", location: FieldLocation::Body },
        FieldSpec { snake: "site_id", wire: "site_id", location: FieldLocation::Body },
    ],
    auth: &[
        AuthApply { secret_key: "OAuth", kind: AuthKind::Bearer },
    ],
};

const OP_COMMON_AREA_PHONES_DELETE_COMMON_AREA_PHONE: OpSpec = OpSpec {
    method: "DELETE",
    path_template: "/phone/common_area_phones/{common_area_phone_id}",
    fields: &[
        FieldSpec { snake: "common_area_phone_id", wire: "commonAreaPhoneId", location: FieldLocation::Path },
    ],
    auth: &[
        AuthApply { secret_key: "OAuth", kind: AuthKind::Bearer },
    ],
};

fn iface_common_area_phones__list_common_area_phones_response_common_area_phones_item_phone_numbers_item_source_enum__to_str(e: &iface_common_area_phones::ListCommonAreaPhonesResponseCommonAreaPhonesItemPhoneNumbersItemSourceEnum) -> &'static str {
    match e {
        iface_common_area_phones::ListCommonAreaPhonesResponseCommonAreaPhonesItemPhoneNumbersItemSourceEnum::Internal => "internal",
        iface_common_area_phones::ListCommonAreaPhonesResponseCommonAreaPhonesItemPhoneNumbersItemSourceEnum::External => "external",
    }
}

fn iface_common_area_phones__get_a_common_area_phone_response_provision_type_op_enum__to_str(e: &iface_common_area_phones::GetACommonAreaPhoneResponseProvisionTypeOpEnum) -> &'static str {
    match e {
        iface_common_area_phones::GetACommonAreaPhoneResponseProvisionTypeOpEnum::Assisted => "assisted",
        iface_common_area_phones::GetACommonAreaPhoneResponseProvisionTypeOpEnum::Ztp => "ztp",
        iface_common_area_phones::GetACommonAreaPhoneResponseProvisionTypeOpEnum::Manual => "manual",
    }
}

fn iface_common_area_phones__list_common_area_phones_response__to_json(p: &iface_common_area_phones::ListCommonAreaPhonesResponse) -> Value {
    let mut m = Map::new();
    m.insert("common_area_phones".into(), match (&p.common_area_phones) { Some(v) => Value::Array((v).iter().map(|v| iface_common_area_phones__list_common_area_phones_response_common_area_phones_item__to_json(v)).collect()), None => Value::Null });
    m.insert("next_page_token".into(), match (&p.next_page_token) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("page_size".into(), match (&p.page_size) { Some(v) => Value::Number(serde_json::Number::from(*(v))), None => Value::Null });
    m.insert("total_records".into(), match (&p.total_records) { Some(v) => Value::Number(serde_json::Number::from(*(v))), None => Value::Null });
    Value::Object(m)
}

fn iface_common_area_phones__list_common_area_phones_response_common_area_phones_item__to_json(p: &iface_common_area_phones::ListCommonAreaPhonesResponseCommonAreaPhonesItem) -> Value {
    let mut m = Map::new();
    m.insert("calling_plans".into(), match (&p.calling_plans) { Some(v) => Value::Array((v).iter().map(|v| iface_common_area_phones__list_common_area_phones_response_common_area_phones_item_calling_plans_item__to_json(v)).collect()), None => Value::Null });
    m.insert("device_type".into(), match (&p.device_type) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("display_name".into(), match (&p.display_name) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("id".into(), match (&p.id) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("mac_address".into(), match (&p.mac_address) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("phone_numbers".into(), match (&p.phone_numbers) { Some(v) => Value::Array((v).iter().map(|v| iface_common_area_phones__list_common_area_phones_response_common_area_phones_item_phone_numbers_item__to_json(v)).collect()), None => Value::Null });
    m.insert("site".into(), match (&p.site) { Some(v) => iface_common_area_phones__list_common_area_phones_response_common_area_phones_item_site__to_json(v), None => Value::Null });
    m.insert("status".into(), match (&p.status) { Some(v) => Value::String((v).clone()), None => Value::Null });
    Value::Object(m)
}

fn iface_common_area_phones__list_common_area_phones_response_common_area_phones_item_calling_plans_item__to_json(p: &iface_common_area_phones::ListCommonAreaPhonesResponseCommonAreaPhonesItemCallingPlansItem) -> Value {
    let mut m = Map::new();
    m.insert("name".into(), match (&p.name) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("type".into(), match (&p.type_op) { Some(v) => Value::String((v).clone()), None => Value::Null });
    Value::Object(m)
}

fn iface_common_area_phones__list_common_area_phones_response_common_area_phones_item_phone_numbers_item__to_json(p: &iface_common_area_phones::ListCommonAreaPhonesResponseCommonAreaPhonesItemPhoneNumbersItem) -> Value {
    let mut m = Map::new();
    m.insert("id".into(), match (&p.id) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("number".into(), match (&p.number) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("source".into(), match (&p.source) { Some(v) => Value::String(iface_common_area_phones__list_common_area_phones_response_common_area_phones_item_phone_numbers_item_source_enum__to_str(v).into()), None => Value::Null });
    Value::Object(m)
}

fn iface_common_area_phones__list_common_area_phones_response_common_area_phones_item_site__to_json(p: &iface_common_area_phones::ListCommonAreaPhonesResponseCommonAreaPhonesItemSite) -> Value {
    let mut m = Map::new();
    m.insert("id".into(), match (&p.id) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("name".into(), match (&p.name) { Some(v) => Value::String((v).clone()), None => Value::Null });
    Value::Object(m)
}

fn iface_common_area_phones__add_common_area_phone_response__to_json(p: &iface_common_area_phones::AddCommonAreaPhoneResponse) -> Value {
    let mut m = Map::new();
    m.insert("display_name".into(), match (&p.display_name) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("id".into(), match (&p.id) { Some(v) => Value::String((v).clone()), None => Value::Null });
    Value::Object(m)
}

fn iface_common_area_phones__get_a_common_area_phone_response__to_json(p: &iface_common_area_phones::GetACommonAreaPhoneResponse) -> Value {
    let mut m = Map::new();
    m.insert("device_type".into(), match (&p.device_type) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("id".into(), match (&p.id) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("mac_address".into(), match (&p.mac_address) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("name".into(), match (&p.name) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("provision".into(), match (&p.provision) { Some(v) => iface_common_area_phones__get_a_common_area_phone_response_provision__to_json(v), None => Value::Null });
    m.insert("site".into(), match (&p.site) { Some(v) => iface_common_area_phones__get_a_common_area_phone_response_site__to_json(v), None => Value::Null });
    m.insert("status".into(), match (&p.status) { Some(v) => Value::String((v).clone()), None => Value::Null });
    Value::Object(m)
}

fn iface_common_area_phones__get_a_common_area_phone_response_provision__to_json(p: &iface_common_area_phones::GetACommonAreaPhoneResponseProvision) -> Value {
    let mut m = Map::new();
    m.insert("sip_accounts".into(), match (&p.sip_accounts) { Some(v) => Value::Array((v).iter().map(|v| iface_common_area_phones__get_a_common_area_phone_response_provision_sip_accounts_item__to_json(v)).collect()), None => Value::Null });
    m.insert("type".into(), match (&p.type_op) { Some(v) => Value::String(iface_common_area_phones__get_a_common_area_phone_response_provision_type_op_enum__to_str(v).into()), None => Value::Null });
    m.insert("url".into(), match (&p.url) { Some(v) => Value::String((v).clone()), None => Value::Null });
    Value::Object(m)
}

fn iface_common_area_phones__get_a_common_area_phone_response_provision_sip_accounts_item__to_json(p: &iface_common_area_phones::GetACommonAreaPhoneResponseProvisionSipAccountsItem) -> Value {
    let mut m = Map::new();
    m.insert("authorization_id".into(), match (&p.authorization_id) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("outbound_proxy".into(), match (&p.outbound_proxy) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("password".into(), match (&p.password) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("sip_domain".into(), match (&p.sip_domain) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("user_name".into(), match (&p.user_name) { Some(v) => Value::String((v).clone()), None => Value::Null });
    Value::Object(m)
}

fn iface_common_area_phones__get_a_common_area_phone_response_site__to_json(p: &iface_common_area_phones::GetACommonAreaPhoneResponseSite) -> Value {
    let mut m = Map::new();
    m.insert("id".into(), match (&p.id) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("name".into(), match (&p.name) { Some(v) => Value::String((v).clone()), None => Value::Null });
    Value::Object(m)
}

fn iface_common_area_phones__list_common_area_phones_params__to_json(p: &iface_common_area_phones::ListCommonAreaPhonesParams) -> Value {
    let mut m = Map::new();
    m.insert("page_size".into(), match (&p.page_size) { Some(v) => Value::Number(serde_json::Number::from(*(v))), None => Value::Null });
    m.insert("next_page_token".into(), match (&p.next_page_token) { Some(v) => Value::String((v).clone()), None => Value::Null });
    Value::Object(m)
}

fn iface_common_area_phones__add_common_area_phone_params__to_json(p: &iface_common_area_phones::AddCommonAreaPhoneParams) -> Value {
    let mut m = Map::new();
    m.insert("description".into(), match (&p.description) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("display_name".into(), Value::String((&p.display_name).clone()));
    m.insert("extension_number".into(), Value::Number(serde_json::Number::from(*(&p.extension_number))));
    m.insert("mac_address".into(), Value::String((&p.mac_address).clone()));
    m.insert("model".into(), match (&p.model) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("site_id".into(), match (&p.site_id) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("time_zone".into(), match (&p.time_zone) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("type".into(), Value::String((&p.type_op).clone()));
    Value::Object(m)
}

fn iface_common_area_phones__get_a_common_area_phone_params__to_json(p: &iface_common_area_phones::GetACommonAreaPhoneParams) -> Value {
    let mut m = Map::new();
    m.insert("common_area_phone_id".into(), Value::String((&p.common_area_phone_id).clone()));
    Value::Object(m)
}

fn iface_common_area_phones__update_common_area_phone_params__to_json(p: &iface_common_area_phones::UpdateCommonAreaPhoneParams) -> Value {
    let mut m = Map::new();
    m.insert("common_area_phone_id".into(), Value::String((&p.common_area_phone_id).clone()));
    m.insert("display_name".into(), match (&p.display_name) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("extension_number".into(), match (&p.extension_number) { Some(v) => Value::Number(serde_json::Number::from(*(v))), None => Value::Null });
    m.insert("mac_address".into(), match (&p.mac_address) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("site_id".into(), match (&p.site_id) { Some(v) => Value::String((v).clone()), None => Value::Null });
    Value::Object(m)
}

fn iface_common_area_phones__delete_common_area_phone_params__to_json(p: &iface_common_area_phones::DeleteCommonAreaPhoneParams) -> Value {
    let mut m = Map::new();
    m.insert("common_area_phone_id".into(), Value::String((&p.common_area_phone_id).clone()));
    Value::Object(m)
}

fn iface_common_area_phones__list_common_area_phones_response__from_json(v: &Value) -> Option<iface_common_area_phones::ListCommonAreaPhonesResponse> {
    let m = v.as_object()?;
    Some(iface_common_area_phones::ListCommonAreaPhonesResponse {
        common_area_phones: m.get("common_area_phones").filter(|v| !v.is_null()).and_then(|v| (v).as_array().map(|a| a.iter().filter_map(|x| iface_common_area_phones__list_common_area_phones_response_common_area_phones_item__from_json(x)).collect())),
        next_page_token: m.get("next_page_token").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        page_size: m.get("page_size").filter(|v| !v.is_null()).and_then(|v| (v).as_i64().map(|n| n as i32)),
        total_records: m.get("total_records").filter(|v| !v.is_null()).and_then(|v| (v).as_i64().map(|n| n as i32)),
    })
}

fn iface_common_area_phones__list_common_area_phones_response_common_area_phones_item__from_json(v: &Value) -> Option<iface_common_area_phones::ListCommonAreaPhonesResponseCommonAreaPhonesItem> {
    let m = v.as_object()?;
    Some(iface_common_area_phones::ListCommonAreaPhonesResponseCommonAreaPhonesItem {
        calling_plans: m.get("calling_plans").filter(|v| !v.is_null()).and_then(|v| (v).as_array().map(|a| a.iter().filter_map(|x| iface_common_area_phones__list_common_area_phones_response_common_area_phones_item_calling_plans_item__from_json(x)).collect())),
        device_type: m.get("device_type").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        display_name: m.get("display_name").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        id: m.get("id").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        mac_address: m.get("mac_address").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        phone_numbers: m.get("phone_numbers").filter(|v| !v.is_null()).and_then(|v| (v).as_array().map(|a| a.iter().filter_map(|x| iface_common_area_phones__list_common_area_phones_response_common_area_phones_item_phone_numbers_item__from_json(x)).collect())),
        site: m.get("site").filter(|v| !v.is_null()).and_then(|v| iface_common_area_phones__list_common_area_phones_response_common_area_phones_item_site__from_json(v)),
        status: m.get("status").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
    })
}

fn iface_common_area_phones__list_common_area_phones_response_common_area_phones_item_calling_plans_item__from_json(v: &Value) -> Option<iface_common_area_phones::ListCommonAreaPhonesResponseCommonAreaPhonesItemCallingPlansItem> {
    let m = v.as_object()?;
    Some(iface_common_area_phones::ListCommonAreaPhonesResponseCommonAreaPhonesItemCallingPlansItem {
        name: m.get("name").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        type_op: m.get("type").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
    })
}

fn iface_common_area_phones__list_common_area_phones_response_common_area_phones_item_phone_numbers_item__from_json(v: &Value) -> Option<iface_common_area_phones::ListCommonAreaPhonesResponseCommonAreaPhonesItemPhoneNumbersItem> {
    let m = v.as_object()?;
    Some(iface_common_area_phones::ListCommonAreaPhonesResponseCommonAreaPhonesItemPhoneNumbersItem {
        id: m.get("id").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        number: m.get("number").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        source: m.get("source").filter(|v| !v.is_null()).and_then(|v| (v).as_str().and_then(iface_common_area_phones__list_common_area_phones_response_common_area_phones_item_phone_numbers_item_source_enum__from_str)),
    })
}

fn iface_common_area_phones__list_common_area_phones_response_common_area_phones_item_site__from_json(v: &Value) -> Option<iface_common_area_phones::ListCommonAreaPhonesResponseCommonAreaPhonesItemSite> {
    let m = v.as_object()?;
    Some(iface_common_area_phones::ListCommonAreaPhonesResponseCommonAreaPhonesItemSite {
        id: m.get("id").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        name: m.get("name").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
    })
}

fn iface_common_area_phones__add_common_area_phone_response__from_json(v: &Value) -> Option<iface_common_area_phones::AddCommonAreaPhoneResponse> {
    let m = v.as_object()?;
    Some(iface_common_area_phones::AddCommonAreaPhoneResponse {
        display_name: m.get("display_name").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        id: m.get("id").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
    })
}

fn iface_common_area_phones__get_a_common_area_phone_response__from_json(v: &Value) -> Option<iface_common_area_phones::GetACommonAreaPhoneResponse> {
    let m = v.as_object()?;
    Some(iface_common_area_phones::GetACommonAreaPhoneResponse {
        device_type: m.get("device_type").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        id: m.get("id").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        mac_address: m.get("mac_address").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        name: m.get("name").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        provision: m.get("provision").filter(|v| !v.is_null()).and_then(|v| iface_common_area_phones__get_a_common_area_phone_response_provision__from_json(v)),
        site: m.get("site").filter(|v| !v.is_null()).and_then(|v| iface_common_area_phones__get_a_common_area_phone_response_site__from_json(v)),
        status: m.get("status").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
    })
}

fn iface_common_area_phones__get_a_common_area_phone_response_provision__from_json(v: &Value) -> Option<iface_common_area_phones::GetACommonAreaPhoneResponseProvision> {
    let m = v.as_object()?;
    Some(iface_common_area_phones::GetACommonAreaPhoneResponseProvision {
        sip_accounts: m.get("sip_accounts").filter(|v| !v.is_null()).and_then(|v| (v).as_array().map(|a| a.iter().filter_map(|x| iface_common_area_phones__get_a_common_area_phone_response_provision_sip_accounts_item__from_json(x)).collect())),
        type_op: m.get("type").filter(|v| !v.is_null()).and_then(|v| (v).as_str().and_then(iface_common_area_phones__get_a_common_area_phone_response_provision_type_op_enum__from_str)),
        url: m.get("url").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
    })
}

fn iface_common_area_phones__get_a_common_area_phone_response_provision_sip_accounts_item__from_json(v: &Value) -> Option<iface_common_area_phones::GetACommonAreaPhoneResponseProvisionSipAccountsItem> {
    let m = v.as_object()?;
    Some(iface_common_area_phones::GetACommonAreaPhoneResponseProvisionSipAccountsItem {
        authorization_id: m.get("authorization_id").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        outbound_proxy: m.get("outbound_proxy").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        password: m.get("password").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        sip_domain: m.get("sip_domain").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        user_name: m.get("user_name").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
    })
}

fn iface_common_area_phones__get_a_common_area_phone_response_site__from_json(v: &Value) -> Option<iface_common_area_phones::GetACommonAreaPhoneResponseSite> {
    let m = v.as_object()?;
    Some(iface_common_area_phones::GetACommonAreaPhoneResponseSite {
        id: m.get("id").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        name: m.get("name").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
    })
}

fn iface_common_area_phones__list_common_area_phones_response_common_area_phones_item_phone_numbers_item_source_enum__from_str(s: &str) -> Option<iface_common_area_phones::ListCommonAreaPhonesResponseCommonAreaPhonesItemPhoneNumbersItemSourceEnum> {
    match s {
        "internal" => Some(iface_common_area_phones::ListCommonAreaPhonesResponseCommonAreaPhonesItemPhoneNumbersItemSourceEnum::Internal),
        "external" => Some(iface_common_area_phones::ListCommonAreaPhonesResponseCommonAreaPhonesItemPhoneNumbersItemSourceEnum::External),
        _ => None,
    }
}

fn iface_common_area_phones__get_a_common_area_phone_response_provision_type_op_enum__from_str(s: &str) -> Option<iface_common_area_phones::GetACommonAreaPhoneResponseProvisionTypeOpEnum> {
    match s {
        "assisted" => Some(iface_common_area_phones::GetACommonAreaPhoneResponseProvisionTypeOpEnum::Assisted),
        "ztp" => Some(iface_common_area_phones::GetACommonAreaPhoneResponseProvisionTypeOpEnum::Ztp),
        "manual" => Some(iface_common_area_phones::GetACommonAreaPhoneResponseProvisionTypeOpEnum::Manual),
        _ => None,
    }
}

fn iface_common_area_phones__list_common_area_phones__ok(body: String) -> Result<iface_common_area_phones::ListCommonAreaPhonesResponse, crate::runtime::DispatchError> {
    let v: Value = match serde_json::from_str(&body) {
        Ok(v) => v,
        Err(e) => return Err(crate::runtime::DispatchError::Transport(format!("failed to decode response body as JSON: {e}"))),
    };
    match iface_common_area_phones__list_common_area_phones_response__from_json(&v) {
        Some(x) => Ok(x),
        None => Err(crate::runtime::DispatchError::Transport("response body did not match the expected schema".to_string())),
    }
}

fn iface_common_area_phones__list_common_area_phones__err(e: crate::runtime::DispatchError) -> String {
    match e {
        crate::runtime::DispatchError::Http { status, body } => format!("HTTP {status}: {body}"),
        crate::runtime::DispatchError::Transport(m) => m,
    }
}

fn iface_common_area_phones__add_common_area_phone__ok(body: String) -> Result<iface_common_area_phones::AddCommonAreaPhoneResponse, crate::runtime::DispatchError> {
    let v: Value = match serde_json::from_str(&body) {
        Ok(v) => v,
        Err(e) => return Err(crate::runtime::DispatchError::Transport(format!("failed to decode response body as JSON: {e}"))),
    };
    match iface_common_area_phones__add_common_area_phone_response__from_json(&v) {
        Some(x) => Ok(x),
        None => Err(crate::runtime::DispatchError::Transport("response body did not match the expected schema".to_string())),
    }
}

fn iface_common_area_phones__add_common_area_phone__err(e: crate::runtime::DispatchError) -> iface_common_area_phones::AddCommonAreaPhoneError {
    match e {
        crate::runtime::DispatchError::Http { status, body } => match status {
            400u16 => iface_common_area_phones::AddCommonAreaPhoneError::BadRequest(body),
            409u16 => iface_common_area_phones::AddCommonAreaPhoneError::Conflict(body),
            _ => iface_common_area_phones::AddCommonAreaPhoneError::Other(body),
        },
        crate::runtime::DispatchError::Transport(m) => iface_common_area_phones::AddCommonAreaPhoneError::Other(m),
    }
}

fn iface_common_area_phones__get_a_common_area_phone__ok(body: String) -> Result<iface_common_area_phones::GetACommonAreaPhoneResponse, crate::runtime::DispatchError> {
    let v: Value = match serde_json::from_str(&body) {
        Ok(v) => v,
        Err(e) => return Err(crate::runtime::DispatchError::Transport(format!("failed to decode response body as JSON: {e}"))),
    };
    match iface_common_area_phones__get_a_common_area_phone_response__from_json(&v) {
        Some(x) => Ok(x),
        None => Err(crate::runtime::DispatchError::Transport("response body did not match the expected schema".to_string())),
    }
}

fn iface_common_area_phones__get_a_common_area_phone__err(e: crate::runtime::DispatchError) -> iface_common_area_phones::GetACommonAreaPhoneError {
    match e {
        crate::runtime::DispatchError::Http { status, body } => match status {
            400u16 => iface_common_area_phones::GetACommonAreaPhoneError::BadRequest(body),
            _ => iface_common_area_phones::GetACommonAreaPhoneError::Other(body),
        },
        crate::runtime::DispatchError::Transport(m) => iface_common_area_phones::GetACommonAreaPhoneError::Other(m),
    }
}

fn iface_common_area_phones__update_common_area_phone__ok(body: String) -> Result<String, crate::runtime::DispatchError> {
    Ok(body)
}

fn iface_common_area_phones__update_common_area_phone__err(e: crate::runtime::DispatchError) -> iface_common_area_phones::UpdateCommonAreaPhoneError {
    match e {
        crate::runtime::DispatchError::Http { status, body } => match status {
            400u16 => iface_common_area_phones::UpdateCommonAreaPhoneError::BadRequest(body),
            _ => iface_common_area_phones::UpdateCommonAreaPhoneError::Other(body),
        },
        crate::runtime::DispatchError::Transport(m) => iface_common_area_phones::UpdateCommonAreaPhoneError::Other(m),
    }
}

fn iface_common_area_phones__delete_common_area_phone__ok(body: String) -> Result<String, crate::runtime::DispatchError> {
    Ok(body)
}

fn iface_common_area_phones__delete_common_area_phone__err(e: crate::runtime::DispatchError) -> iface_common_area_phones::DeleteCommonAreaPhoneError {
    match e {
        crate::runtime::DispatchError::Http { status, body } => match status {
            400u16 => iface_common_area_phones::DeleteCommonAreaPhoneError::BadRequest(body),
            _ => iface_common_area_phones::DeleteCommonAreaPhoneError::Other(body),
        },
        crate::runtime::DispatchError::Transport(m) => iface_common_area_phones::DeleteCommonAreaPhoneError::Other(m),
    }
}

impl iface_common_area_phones::Guest for crate::Component {
    fn list_common_area_phones(params: iface_common_area_phones::ListCommonAreaPhonesParams) -> Result<iface_common_area_phones::ListCommonAreaPhonesResponse, String> {
        let json = iface_common_area_phones__list_common_area_phones_params__to_json(&params);
        match dispatch(&OP_COMMON_AREA_PHONES_LIST_COMMON_AREA_PHONES, json).and_then(iface_common_area_phones__list_common_area_phones__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_common_area_phones__list_common_area_phones__err(e)),
        }
    }
    fn add_common_area_phone(params: iface_common_area_phones::AddCommonAreaPhoneParams) -> Result<iface_common_area_phones::AddCommonAreaPhoneResponse, iface_common_area_phones::AddCommonAreaPhoneError> {
        let json = iface_common_area_phones__add_common_area_phone_params__to_json(&params);
        match dispatch(&OP_COMMON_AREA_PHONES_ADD_COMMON_AREA_PHONE, json).and_then(iface_common_area_phones__add_common_area_phone__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_common_area_phones__add_common_area_phone__err(e)),
        }
    }
    fn get_a_common_area_phone(params: iface_common_area_phones::GetACommonAreaPhoneParams) -> Result<iface_common_area_phones::GetACommonAreaPhoneResponse, iface_common_area_phones::GetACommonAreaPhoneError> {
        let json = iface_common_area_phones__get_a_common_area_phone_params__to_json(&params);
        match dispatch(&OP_COMMON_AREA_PHONES_GET_A_COMMON_AREA_PHONE, json).and_then(iface_common_area_phones__get_a_common_area_phone__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_common_area_phones__get_a_common_area_phone__err(e)),
        }
    }
    fn update_common_area_phone(params: iface_common_area_phones::UpdateCommonAreaPhoneParams) -> Result<String, iface_common_area_phones::UpdateCommonAreaPhoneError> {
        let json = iface_common_area_phones__update_common_area_phone_params__to_json(&params);
        match dispatch(&OP_COMMON_AREA_PHONES_UPDATE_COMMON_AREA_PHONE, json).and_then(iface_common_area_phones__update_common_area_phone__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_common_area_phones__update_common_area_phone__err(e)),
        }
    }
    fn delete_common_area_phone(params: iface_common_area_phones::DeleteCommonAreaPhoneParams) -> Result<String, iface_common_area_phones::DeleteCommonAreaPhoneError> {
        let json = iface_common_area_phones__delete_common_area_phone_params__to_json(&params);
        match dispatch(&OP_COMMON_AREA_PHONES_DELETE_COMMON_AREA_PHONE, json).and_then(iface_common_area_phones__delete_common_area_phone__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_common_area_phones__delete_common_area_phone__err(e)),
        }
    }
}
