// AUTOGENERATED by openapi-bindgen. Do not edit by hand.

use crate::runtime::{dispatch, AuthApply, AuthKind, FieldLocation, FieldSpec, OpSpec};
use crate::exports::autostamp::magento::guest_carts as iface_guest_carts;
use serde_json::{Map, Value};

const OP_GUEST_CARTS_QUOTE_GUEST_CART_MANAGEMENT_V1_CREATE_EMPTY_CART_POST: OpSpec = OpSpec {
    method: "POST",
    path_template: "/V1/guest-carts",
    fields: &[
    ],
    auth: &[
    ],
};

fn iface_guest_carts__quote_guest_cart_management_v1_create_empty_cart_post__ok(body: String) -> Result<String, crate::runtime::DispatchError> {
    Ok(body)
}

fn iface_guest_carts__quote_guest_cart_management_v1_create_empty_cart_post__err(e: crate::runtime::DispatchError) -> iface_guest_carts::QuoteGuestCartManagementV1CreateEmptyCartPostError {
    match e {
        crate::runtime::DispatchError::Http { status, body } => match status {
            400u16 => iface_guest_carts::QuoteGuestCartManagementV1CreateEmptyCartPostError::BadRequest(body),
            _ => iface_guest_carts::QuoteGuestCartManagementV1CreateEmptyCartPostError::Other(body),
        },
        crate::runtime::DispatchError::Transport(m) => iface_guest_carts::QuoteGuestCartManagementV1CreateEmptyCartPostError::Other(m),
    }
}

impl iface_guest_carts::Guest for crate::Component {
    fn quote_guest_cart_management_v1_create_empty_cart_post() -> Result<String, iface_guest_carts::QuoteGuestCartManagementV1CreateEmptyCartPostError> {
        match dispatch(&OP_GUEST_CARTS_QUOTE_GUEST_CART_MANAGEMENT_V1_CREATE_EMPTY_CART_POST, Value::Object(Map::new())).and_then(iface_guest_carts__quote_guest_cart_management_v1_create_empty_cart_post__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_guest_carts__quote_guest_cart_management_v1_create_empty_cart_post__err(e)),
        }
    }
}
