// AUTOGENERATED by openapi-bindgen. Do not edit by hand.

use crate::runtime::{dispatch, AuthApply, AuthKind, FieldLocation, FieldSpec, OpSpec};
use crate::exports::autostamp::magento::carts_mine_order as iface_carts_mine_order;
use serde_json::{Map, Value};

const OP_CARTS_MINE_ORDER_QUOTE_CART_MANAGEMENT_V1_PLACE_ORDER_PUT: OpSpec = OpSpec {
    method: "PUT",
    path_template: "/V1/carts/mine/order",
    fields: &[
        FieldSpec { snake: "payment_method", wire: "paymentMethod", location: FieldLocation::Body },
    ],
    auth: &[
    ],
};

fn iface_carts_mine_order__quote_data_payment_interface__to_json(p: &iface_carts_mine_order::QuoteDataPaymentInterface) -> Value {
    let mut m = Map::new();
    m.insert("additional_data".into(), match (&p.additional_data) { Some(v) => Value::Array((v).iter().map(|v| Value::String((v).clone())).collect()), None => Value::Null });
    m.insert("extension_attributes".into(), match (&p.extension_attributes) { Some(v) => iface_carts_mine_order__quote_data_payment_extension_interface__to_json(v), None => Value::Null });
    m.insert("method".into(), Value::String((&p.method).clone()));
    m.insert("po_number".into(), match (&p.po_number) { Some(v) => Value::String((v).clone()), None => Value::Null });
    Value::Object(m)
}

fn iface_carts_mine_order__quote_data_payment_extension_interface__to_json(p: &iface_carts_mine_order::QuoteDataPaymentExtensionInterface) -> Value {
    let mut m = Map::new();
    m.insert("agreement_ids".into(), match (&p.agreement_ids) { Some(v) => Value::Array((v).iter().map(|v| Value::String((v).clone())).collect()), None => Value::Null });
    Value::Object(m)
}

fn iface_carts_mine_order__quote_cart_management_v1_place_order_put_params__to_json(p: &iface_carts_mine_order::QuoteCartManagementV1PlaceOrderPutParams) -> Value {
    let mut m = Map::new();
    m.insert("payment_method".into(), match (&p.payment_method) { Some(v) => iface_carts_mine_order__quote_data_payment_interface__to_json(v), None => Value::Null });
    Value::Object(m)
}

fn iface_carts_mine_order__quote_cart_management_v1_place_order_put__ok(body: String) -> Result<i32, crate::runtime::DispatchError> {
    let v: Value = match serde_json::from_str(&body) {
        Ok(v) => v,
        Err(e) => return Err(crate::runtime::DispatchError::Transport(format!("failed to decode response body as JSON: {e}"))),
    };
    match (&v).as_i64().map(|n| n as i32) {
        Some(x) => Ok(x),
        None => Err(crate::runtime::DispatchError::Transport("response body did not match the expected schema".to_string())),
    }
}

fn iface_carts_mine_order__quote_cart_management_v1_place_order_put__err(e: crate::runtime::DispatchError) -> iface_carts_mine_order::QuoteCartManagementV1PlaceOrderPutError {
    match e {
        crate::runtime::DispatchError::Http { status, body } => match status {
            400u16 => iface_carts_mine_order::QuoteCartManagementV1PlaceOrderPutError::BadRequest(body),
            401u16 => iface_carts_mine_order::QuoteCartManagementV1PlaceOrderPutError::Unauthorized(body),
            _ => iface_carts_mine_order::QuoteCartManagementV1PlaceOrderPutError::Other(body),
        },
        crate::runtime::DispatchError::Transport(m) => iface_carts_mine_order::QuoteCartManagementV1PlaceOrderPutError::Other(m),
    }
}

impl iface_carts_mine_order::Guest for crate::Component {
    fn quote_cart_management_v1_place_order_put(params: iface_carts_mine_order::QuoteCartManagementV1PlaceOrderPutParams) -> Result<i32, iface_carts_mine_order::QuoteCartManagementV1PlaceOrderPutError> {
        let json = iface_carts_mine_order__quote_cart_management_v1_place_order_put_params__to_json(&params);
        match dispatch(&OP_CARTS_MINE_ORDER_QUOTE_CART_MANAGEMENT_V1_PLACE_ORDER_PUT, json).and_then(iface_carts_mine_order__quote_cart_management_v1_place_order_put__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_carts_mine_order__quote_cart_management_v1_place_order_put__err(e)),
        }
    }
}
