// AUTOGENERATED by openapi-bindgen. Do not edit by hand.

use crate::runtime::{dispatch, AuthApply, AuthKind, FieldLocation, FieldSpec, OpSpec};
use crate::exports::autostamp::magento::products_attributes_attribute_code as iface_products_attributes_attribute_code;
use serde_json::{Map, Value};

const OP_PRODUCTS_ATTRIBUTES_ATTRIBUTE_CODE_CATALOG_PRODUCT_ATTRIBUTE_REPOSITORY_V1_GET_GET: OpSpec = OpSpec {
    method: "GET",
    path_template: "/V1/products/attributes/{attribute_code}",
    fields: &[
        FieldSpec { snake: "attribute_code", wire: "attributeCode", location: FieldLocation::Path },
    ],
    auth: &[
    ],
};

const OP_PRODUCTS_ATTRIBUTES_ATTRIBUTE_CODE_CATALOG_PRODUCT_ATTRIBUTE_REPOSITORY_V1_SAVE_PUT: OpSpec = OpSpec {
    method: "PUT",
    path_template: "/V1/products/attributes/{attribute_code}",
    fields: &[
        FieldSpec { snake: "attribute_code", wire: "attributeCode", location: FieldLocation::Path },
        FieldSpec { snake: "attribute", wire: "attribute", location: FieldLocation::Body },
    ],
    auth: &[
    ],
};

const OP_PRODUCTS_ATTRIBUTES_ATTRIBUTE_CODE_CATALOG_PRODUCT_ATTRIBUTE_REPOSITORY_V1_DELETE_BY_ID_DELETE: OpSpec = OpSpec {
    method: "DELETE",
    path_template: "/V1/products/attributes/{attribute_code}",
    fields: &[
        FieldSpec { snake: "attribute_code", wire: "attributeCode", location: FieldLocation::Path },
    ],
    auth: &[
    ],
};

fn iface_products_attributes_attribute_code__catalog_data_product_attribute_interface__to_json(p: &iface_products_attributes_attribute_code::CatalogDataProductAttributeInterface) -> Value {
    let mut m = Map::new();
    m.insert("apply_to".into(), match (&p.apply_to) { Some(v) => Value::Array((v).iter().map(|v| Value::String((v).clone())).collect()), None => Value::Null });
    m.insert("attribute_code".into(), Value::String((&p.attribute_code).clone()));
    m.insert("attribute_id".into(), match (&p.attribute_id) { Some(v) => Value::Number(serde_json::Number::from(*(v))), None => Value::Null });
    m.insert("backend_model".into(), match (&p.backend_model) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("backend_type".into(), match (&p.backend_type) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("custom_attributes".into(), match (&p.custom_attributes) { Some(v) => Value::Array((v).iter().map(|v| iface_products_attributes_attribute_code__framework_attribute_interface__to_json(v)).collect()), None => Value::Null });
    m.insert("default_frontend_label".into(), match (&p.default_frontend_label) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("default_value".into(), match (&p.default_value) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("entity_type_id".into(), Value::String((&p.entity_type_id).clone()));
    m.insert("extension_attributes".into(), match (&p.extension_attributes) { Some(v) => Value::Object((v).iter().map(|e| (e.key.clone(), Value::String((&e.value).clone()))).collect()), None => Value::Null });
    m.insert("frontend_class".into(), match (&p.frontend_class) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("frontend_input".into(), Value::String((&p.frontend_input).clone()));
    m.insert("frontend_labels".into(), Value::Array((&p.frontend_labels).iter().map(|v| iface_products_attributes_attribute_code__eav_data_attribute_frontend_label_interface__to_json(v)).collect()));
    m.insert("is_comparable".into(), match (&p.is_comparable) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("is_filterable".into(), match (&p.is_filterable) { Some(v) => Value::Bool(*(v)), None => Value::Null });
    m.insert("is_filterable_in_grid".into(), match (&p.is_filterable_in_grid) { Some(v) => Value::Bool(*(v)), None => Value::Null });
    m.insert("is_filterable_in_search".into(), match (&p.is_filterable_in_search) { Some(v) => Value::Bool(*(v)), None => Value::Null });
    m.insert("is_html_allowed_on_front".into(), match (&p.is_html_allowed_on_front) { Some(v) => Value::Bool(*(v)), None => Value::Null });
    m.insert("is_required".into(), Value::Bool(*(&p.is_required)));
    m.insert("is_searchable".into(), match (&p.is_searchable) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("is_unique".into(), match (&p.is_unique) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("is_used_for_promo_rules".into(), match (&p.is_used_for_promo_rules) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("is_used_in_grid".into(), match (&p.is_used_in_grid) { Some(v) => Value::Bool(*(v)), None => Value::Null });
    m.insert("is_user_defined".into(), match (&p.is_user_defined) { Some(v) => Value::Bool(*(v)), None => Value::Null });
    m.insert("is_visible".into(), match (&p.is_visible) { Some(v) => Value::Bool(*(v)), None => Value::Null });
    m.insert("is_visible_in_advanced_search".into(), match (&p.is_visible_in_advanced_search) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("is_visible_in_grid".into(), match (&p.is_visible_in_grid) { Some(v) => Value::Bool(*(v)), None => Value::Null });
    m.insert("is_visible_on_front".into(), match (&p.is_visible_on_front) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("is_wysiwyg_enabled".into(), match (&p.is_wysiwyg_enabled) { Some(v) => Value::Bool(*(v)), None => Value::Null });
    m.insert("note".into(), match (&p.note) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("options".into(), match (&p.options) { Some(v) => Value::Array((v).iter().map(|v| iface_products_attributes_attribute_code__eav_data_attribute_option_interface__to_json(v)).collect()), None => Value::Null });
    m.insert("position".into(), match (&p.position) { Some(v) => Value::Number(serde_json::Number::from(*(v))), None => Value::Null });
    m.insert("scope".into(), match (&p.scope) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("source_model".into(), match (&p.source_model) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("used_for_sort_by".into(), match (&p.used_for_sort_by) { Some(v) => Value::Bool(*(v)), None => Value::Null });
    m.insert("used_in_product_listing".into(), match (&p.used_in_product_listing) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("validation_rules".into(), match (&p.validation_rules) { Some(v) => Value::Array((v).iter().map(|v| iface_products_attributes_attribute_code__eav_data_attribute_validation_rule_interface__to_json(v)).collect()), None => Value::Null });
    Value::Object(m)
}

fn iface_products_attributes_attribute_code__framework_attribute_interface__to_json(p: &iface_products_attributes_attribute_code::FrameworkAttributeInterface) -> Value {
    let mut m = Map::new();
    m.insert("attribute_code".into(), Value::String((&p.attribute_code).clone()));
    m.insert("value".into(), Value::String((&p.value).clone()));
    Value::Object(m)
}

fn iface_products_attributes_attribute_code__catalog_data_eav_attribute_extension_interface_entry__to_json(p: &iface_products_attributes_attribute_code::CatalogDataEavAttributeExtensionInterfaceEntry) -> Value {
    let mut m = Map::new();
    m.insert("key".into(), Value::String((&p.key).clone()));
    m.insert("value".into(), Value::String((&p.value).clone()));
    Value::Object(m)
}

fn iface_products_attributes_attribute_code__eav_data_attribute_frontend_label_interface__to_json(p: &iface_products_attributes_attribute_code::EavDataAttributeFrontendLabelInterface) -> Value {
    let mut m = Map::new();
    m.insert("label".into(), match (&p.label) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("store_id".into(), match (&p.store_id) { Some(v) => Value::Number(serde_json::Number::from(*(v))), None => Value::Null });
    Value::Object(m)
}

fn iface_products_attributes_attribute_code__eav_data_attribute_option_interface__to_json(p: &iface_products_attributes_attribute_code::EavDataAttributeOptionInterface) -> Value {
    let mut m = Map::new();
    m.insert("is_default".into(), match (&p.is_default) { Some(v) => Value::Bool(*(v)), None => Value::Null });
    m.insert("label".into(), Value::String((&p.label).clone()));
    m.insert("sort_order".into(), match (&p.sort_order) { Some(v) => Value::Number(serde_json::Number::from(*(v))), None => Value::Null });
    m.insert("store_labels".into(), match (&p.store_labels) { Some(v) => Value::Array((v).iter().map(|v| iface_products_attributes_attribute_code__eav_data_attribute_option_label_interface__to_json(v)).collect()), None => Value::Null });
    m.insert("value".into(), Value::String((&p.value).clone()));
    Value::Object(m)
}

fn iface_products_attributes_attribute_code__eav_data_attribute_option_label_interface__to_json(p: &iface_products_attributes_attribute_code::EavDataAttributeOptionLabelInterface) -> Value {
    let mut m = Map::new();
    m.insert("label".into(), match (&p.label) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("store_id".into(), match (&p.store_id) { Some(v) => Value::Number(serde_json::Number::from(*(v))), None => Value::Null });
    Value::Object(m)
}

fn iface_products_attributes_attribute_code__eav_data_attribute_validation_rule_interface__to_json(p: &iface_products_attributes_attribute_code::EavDataAttributeValidationRuleInterface) -> Value {
    let mut m = Map::new();
    m.insert("key".into(), Value::String((&p.key).clone()));
    m.insert("value".into(), Value::String((&p.value).clone()));
    Value::Object(m)
}

fn iface_products_attributes_attribute_code__catalog_product_attribute_repository_v1_get_get_params__to_json(p: &iface_products_attributes_attribute_code::CatalogProductAttributeRepositoryV1GetGetParams) -> Value {
    let mut m = Map::new();
    m.insert("attribute_code".into(), Value::String((&p.attribute_code).clone()));
    Value::Object(m)
}

fn iface_products_attributes_attribute_code__catalog_product_attribute_repository_v1_save_put_params__to_json(p: &iface_products_attributes_attribute_code::CatalogProductAttributeRepositoryV1SavePutParams) -> Value {
    let mut m = Map::new();
    m.insert("attribute_code".into(), Value::String((&p.attribute_code).clone()));
    m.insert("attribute".into(), iface_products_attributes_attribute_code__catalog_data_product_attribute_interface__to_json(&p.attribute));
    Value::Object(m)
}

fn iface_products_attributes_attribute_code__catalog_product_attribute_repository_v1_delete_by_id_delete_params__to_json(p: &iface_products_attributes_attribute_code::CatalogProductAttributeRepositoryV1DeleteByIdDeleteParams) -> Value {
    let mut m = Map::new();
    m.insert("attribute_code".into(), Value::String((&p.attribute_code).clone()));
    Value::Object(m)
}

fn iface_products_attributes_attribute_code__catalog_data_product_attribute_interface__from_json(v: &Value) -> Option<iface_products_attributes_attribute_code::CatalogDataProductAttributeInterface> {
    let m = v.as_object()?;
    Some(iface_products_attributes_attribute_code::CatalogDataProductAttributeInterface {
        apply_to: m.get("apply_to").filter(|v| !v.is_null()).and_then(|v| (v).as_array().map(|a| a.iter().filter_map(|x| (x).as_str().map(|s| s.to_string())).collect())),
        attribute_code: m.get("attribute_code").and_then(|v| (v).as_str().map(|s| s.to_string())).unwrap_or_default(),
        attribute_id: m.get("attribute_id").filter(|v| !v.is_null()).and_then(|v| (v).as_i64().map(|n| n as i32)),
        backend_model: m.get("backend_model").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        backend_type: m.get("backend_type").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        custom_attributes: m.get("custom_attributes").filter(|v| !v.is_null()).and_then(|v| (v).as_array().map(|a| a.iter().filter_map(|x| iface_products_attributes_attribute_code__framework_attribute_interface__from_json(x)).collect())),
        default_frontend_label: m.get("default_frontend_label").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        default_value: m.get("default_value").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        entity_type_id: m.get("entity_type_id").and_then(|v| (v).as_str().map(|s| s.to_string())).unwrap_or_default(),
        extension_attributes: m.get("extension_attributes").filter(|v| !v.is_null()).and_then(|v| (v).as_object().map(|o| o.iter().filter_map(|(k, x)| ((x).as_str().map(|s| s.to_string())).map(|val| iface_products_attributes_attribute_code::CatalogDataEavAttributeExtensionInterfaceEntry { key: k.clone(), value: val })).collect())),
        frontend_class: m.get("frontend_class").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        frontend_input: m.get("frontend_input").and_then(|v| (v).as_str().map(|s| s.to_string())).unwrap_or_default(),
        frontend_labels: m.get("frontend_labels").and_then(|v| (v).as_array().map(|a| a.iter().filter_map(|x| iface_products_attributes_attribute_code__eav_data_attribute_frontend_label_interface__from_json(x)).collect())).unwrap_or_default(),
        is_comparable: m.get("is_comparable").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        is_filterable: m.get("is_filterable").filter(|v| !v.is_null()).and_then(|v| (v).as_bool()),
        is_filterable_in_grid: m.get("is_filterable_in_grid").filter(|v| !v.is_null()).and_then(|v| (v).as_bool()),
        is_filterable_in_search: m.get("is_filterable_in_search").filter(|v| !v.is_null()).and_then(|v| (v).as_bool()),
        is_html_allowed_on_front: m.get("is_html_allowed_on_front").filter(|v| !v.is_null()).and_then(|v| (v).as_bool()),
        is_required: m.get("is_required").and_then(|v| (v).as_bool()).unwrap_or_default(),
        is_searchable: m.get("is_searchable").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        is_unique: m.get("is_unique").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        is_used_for_promo_rules: m.get("is_used_for_promo_rules").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        is_used_in_grid: m.get("is_used_in_grid").filter(|v| !v.is_null()).and_then(|v| (v).as_bool()),
        is_user_defined: m.get("is_user_defined").filter(|v| !v.is_null()).and_then(|v| (v).as_bool()),
        is_visible: m.get("is_visible").filter(|v| !v.is_null()).and_then(|v| (v).as_bool()),
        is_visible_in_advanced_search: m.get("is_visible_in_advanced_search").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        is_visible_in_grid: m.get("is_visible_in_grid").filter(|v| !v.is_null()).and_then(|v| (v).as_bool()),
        is_visible_on_front: m.get("is_visible_on_front").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        is_wysiwyg_enabled: m.get("is_wysiwyg_enabled").filter(|v| !v.is_null()).and_then(|v| (v).as_bool()),
        note: m.get("note").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        options: m.get("options").filter(|v| !v.is_null()).and_then(|v| (v).as_array().map(|a| a.iter().filter_map(|x| iface_products_attributes_attribute_code__eav_data_attribute_option_interface__from_json(x)).collect())),
        position: m.get("position").filter(|v| !v.is_null()).and_then(|v| (v).as_i64().map(|n| n as i32)),
        scope: m.get("scope").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        source_model: m.get("source_model").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        used_for_sort_by: m.get("used_for_sort_by").filter(|v| !v.is_null()).and_then(|v| (v).as_bool()),
        used_in_product_listing: m.get("used_in_product_listing").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        validation_rules: m.get("validation_rules").filter(|v| !v.is_null()).and_then(|v| (v).as_array().map(|a| a.iter().filter_map(|x| iface_products_attributes_attribute_code__eav_data_attribute_validation_rule_interface__from_json(x)).collect())),
    })
}

fn iface_products_attributes_attribute_code__framework_attribute_interface__from_json(v: &Value) -> Option<iface_products_attributes_attribute_code::FrameworkAttributeInterface> {
    let m = v.as_object()?;
    Some(iface_products_attributes_attribute_code::FrameworkAttributeInterface {
        attribute_code: m.get("attribute_code").and_then(|v| (v).as_str().map(|s| s.to_string())).unwrap_or_default(),
        value: m.get("value").and_then(|v| (v).as_str().map(|s| s.to_string())).unwrap_or_default(),
    })
}

fn iface_products_attributes_attribute_code__catalog_data_eav_attribute_extension_interface_entry__from_json(v: &Value) -> Option<iface_products_attributes_attribute_code::CatalogDataEavAttributeExtensionInterfaceEntry> {
    let m = v.as_object()?;
    Some(iface_products_attributes_attribute_code::CatalogDataEavAttributeExtensionInterfaceEntry {
        key: m.get("key").and_then(|v| (v).as_str().map(|s| s.to_string())).unwrap_or_default(),
        value: m.get("value").and_then(|v| (v).as_str().map(|s| s.to_string())).unwrap_or_default(),
    })
}

fn iface_products_attributes_attribute_code__eav_data_attribute_frontend_label_interface__from_json(v: &Value) -> Option<iface_products_attributes_attribute_code::EavDataAttributeFrontendLabelInterface> {
    let m = v.as_object()?;
    Some(iface_products_attributes_attribute_code::EavDataAttributeFrontendLabelInterface {
        label: m.get("label").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        store_id: m.get("store_id").filter(|v| !v.is_null()).and_then(|v| (v).as_i64().map(|n| n as i32)),
    })
}

fn iface_products_attributes_attribute_code__eav_data_attribute_option_interface__from_json(v: &Value) -> Option<iface_products_attributes_attribute_code::EavDataAttributeOptionInterface> {
    let m = v.as_object()?;
    Some(iface_products_attributes_attribute_code::EavDataAttributeOptionInterface {
        is_default: m.get("is_default").filter(|v| !v.is_null()).and_then(|v| (v).as_bool()),
        label: m.get("label").and_then(|v| (v).as_str().map(|s| s.to_string())).unwrap_or_default(),
        sort_order: m.get("sort_order").filter(|v| !v.is_null()).and_then(|v| (v).as_i64().map(|n| n as i32)),
        store_labels: m.get("store_labels").filter(|v| !v.is_null()).and_then(|v| (v).as_array().map(|a| a.iter().filter_map(|x| iface_products_attributes_attribute_code__eav_data_attribute_option_label_interface__from_json(x)).collect())),
        value: m.get("value").and_then(|v| (v).as_str().map(|s| s.to_string())).unwrap_or_default(),
    })
}

fn iface_products_attributes_attribute_code__eav_data_attribute_option_label_interface__from_json(v: &Value) -> Option<iface_products_attributes_attribute_code::EavDataAttributeOptionLabelInterface> {
    let m = v.as_object()?;
    Some(iface_products_attributes_attribute_code::EavDataAttributeOptionLabelInterface {
        label: m.get("label").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        store_id: m.get("store_id").filter(|v| !v.is_null()).and_then(|v| (v).as_i64().map(|n| n as i32)),
    })
}

fn iface_products_attributes_attribute_code__eav_data_attribute_validation_rule_interface__from_json(v: &Value) -> Option<iface_products_attributes_attribute_code::EavDataAttributeValidationRuleInterface> {
    let m = v.as_object()?;
    Some(iface_products_attributes_attribute_code::EavDataAttributeValidationRuleInterface {
        key: m.get("key").and_then(|v| (v).as_str().map(|s| s.to_string())).unwrap_or_default(),
        value: m.get("value").and_then(|v| (v).as_str().map(|s| s.to_string())).unwrap_or_default(),
    })
}

fn iface_products_attributes_attribute_code__catalog_product_attribute_repository_v1_get_get__ok(body: String) -> Result<iface_products_attributes_attribute_code::CatalogDataProductAttributeInterface, crate::runtime::DispatchError> {
    let v: Value = match serde_json::from_str(&body) {
        Ok(v) => v,
        Err(e) => return Err(crate::runtime::DispatchError::Transport(format!("failed to decode response body as JSON: {e}"))),
    };
    match iface_products_attributes_attribute_code__catalog_data_product_attribute_interface__from_json(&v) {
        Some(x) => Ok(x),
        None => Err(crate::runtime::DispatchError::Transport("response body did not match the expected schema".to_string())),
    }
}

fn iface_products_attributes_attribute_code__catalog_product_attribute_repository_v1_get_get__err(e: crate::runtime::DispatchError) -> iface_products_attributes_attribute_code::CatalogProductAttributeRepositoryV1GetGetError {
    match e {
        crate::runtime::DispatchError::Http { status, body } => match status {
            400u16 => iface_products_attributes_attribute_code::CatalogProductAttributeRepositoryV1GetGetError::BadRequest(body),
            401u16 => iface_products_attributes_attribute_code::CatalogProductAttributeRepositoryV1GetGetError::Unauthorized(body),
            _ => iface_products_attributes_attribute_code::CatalogProductAttributeRepositoryV1GetGetError::Other(body),
        },
        crate::runtime::DispatchError::Transport(m) => iface_products_attributes_attribute_code::CatalogProductAttributeRepositoryV1GetGetError::Other(m),
    }
}

fn iface_products_attributes_attribute_code__catalog_product_attribute_repository_v1_save_put__ok(body: String) -> Result<iface_products_attributes_attribute_code::CatalogDataProductAttributeInterface, crate::runtime::DispatchError> {
    let v: Value = match serde_json::from_str(&body) {
        Ok(v) => v,
        Err(e) => return Err(crate::runtime::DispatchError::Transport(format!("failed to decode response body as JSON: {e}"))),
    };
    match iface_products_attributes_attribute_code__catalog_data_product_attribute_interface__from_json(&v) {
        Some(x) => Ok(x),
        None => Err(crate::runtime::DispatchError::Transport("response body did not match the expected schema".to_string())),
    }
}

fn iface_products_attributes_attribute_code__catalog_product_attribute_repository_v1_save_put__err(e: crate::runtime::DispatchError) -> iface_products_attributes_attribute_code::CatalogProductAttributeRepositoryV1SavePutError {
    match e {
        crate::runtime::DispatchError::Http { status, body } => match status {
            400u16 => iface_products_attributes_attribute_code::CatalogProductAttributeRepositoryV1SavePutError::BadRequest(body),
            401u16 => iface_products_attributes_attribute_code::CatalogProductAttributeRepositoryV1SavePutError::Unauthorized(body),
            _ => iface_products_attributes_attribute_code::CatalogProductAttributeRepositoryV1SavePutError::Other(body),
        },
        crate::runtime::DispatchError::Transport(m) => iface_products_attributes_attribute_code::CatalogProductAttributeRepositoryV1SavePutError::Other(m),
    }
}

fn iface_products_attributes_attribute_code__catalog_product_attribute_repository_v1_delete_by_id_delete__ok(body: String) -> Result<bool, crate::runtime::DispatchError> {
    let v: Value = match serde_json::from_str(&body) {
        Ok(v) => v,
        Err(e) => return Err(crate::runtime::DispatchError::Transport(format!("failed to decode response body as JSON: {e}"))),
    };
    match (&v).as_bool() {
        Some(x) => Ok(x),
        None => Err(crate::runtime::DispatchError::Transport("response body did not match the expected schema".to_string())),
    }
}

fn iface_products_attributes_attribute_code__catalog_product_attribute_repository_v1_delete_by_id_delete__err(e: crate::runtime::DispatchError) -> iface_products_attributes_attribute_code::CatalogProductAttributeRepositoryV1DeleteByIdDeleteError {
    match e {
        crate::runtime::DispatchError::Http { status, body } => match status {
            400u16 => iface_products_attributes_attribute_code::CatalogProductAttributeRepositoryV1DeleteByIdDeleteError::BadRequest(body),
            401u16 => iface_products_attributes_attribute_code::CatalogProductAttributeRepositoryV1DeleteByIdDeleteError::Unauthorized(body),
            _ => iface_products_attributes_attribute_code::CatalogProductAttributeRepositoryV1DeleteByIdDeleteError::Other(body),
        },
        crate::runtime::DispatchError::Transport(m) => iface_products_attributes_attribute_code::CatalogProductAttributeRepositoryV1DeleteByIdDeleteError::Other(m),
    }
}

impl iface_products_attributes_attribute_code::Guest for crate::Component {
    fn catalog_product_attribute_repository_v1_get_get(params: iface_products_attributes_attribute_code::CatalogProductAttributeRepositoryV1GetGetParams) -> Result<iface_products_attributes_attribute_code::CatalogDataProductAttributeInterface, iface_products_attributes_attribute_code::CatalogProductAttributeRepositoryV1GetGetError> {
        let json = iface_products_attributes_attribute_code__catalog_product_attribute_repository_v1_get_get_params__to_json(&params);
        match dispatch(&OP_PRODUCTS_ATTRIBUTES_ATTRIBUTE_CODE_CATALOG_PRODUCT_ATTRIBUTE_REPOSITORY_V1_GET_GET, json).and_then(iface_products_attributes_attribute_code__catalog_product_attribute_repository_v1_get_get__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_products_attributes_attribute_code__catalog_product_attribute_repository_v1_get_get__err(e)),
        }
    }
    fn catalog_product_attribute_repository_v1_save_put(params: iface_products_attributes_attribute_code::CatalogProductAttributeRepositoryV1SavePutParams) -> Result<iface_products_attributes_attribute_code::CatalogDataProductAttributeInterface, iface_products_attributes_attribute_code::CatalogProductAttributeRepositoryV1SavePutError> {
        let json = iface_products_attributes_attribute_code__catalog_product_attribute_repository_v1_save_put_params__to_json(&params);
        match dispatch(&OP_PRODUCTS_ATTRIBUTES_ATTRIBUTE_CODE_CATALOG_PRODUCT_ATTRIBUTE_REPOSITORY_V1_SAVE_PUT, json).and_then(iface_products_attributes_attribute_code__catalog_product_attribute_repository_v1_save_put__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_products_attributes_attribute_code__catalog_product_attribute_repository_v1_save_put__err(e)),
        }
    }
    fn catalog_product_attribute_repository_v1_delete_by_id_delete(params: iface_products_attributes_attribute_code::CatalogProductAttributeRepositoryV1DeleteByIdDeleteParams) -> Result<bool, iface_products_attributes_attribute_code::CatalogProductAttributeRepositoryV1DeleteByIdDeleteError> {
        let json = iface_products_attributes_attribute_code__catalog_product_attribute_repository_v1_delete_by_id_delete_params__to_json(&params);
        match dispatch(&OP_PRODUCTS_ATTRIBUTES_ATTRIBUTE_CODE_CATALOG_PRODUCT_ATTRIBUTE_REPOSITORY_V1_DELETE_BY_ID_DELETE, json).and_then(iface_products_attributes_attribute_code__catalog_product_attribute_repository_v1_delete_by_id_delete__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_products_attributes_attribute_code__catalog_product_attribute_repository_v1_delete_by_id_delete__err(e)),
        }
    }
}
