// AUTOGENERATED by openapi-bindgen. Do not edit by hand.

use crate::runtime::{dispatch, AuthApply, AuthKind, FieldLocation, FieldSpec, OpSpec};
use crate::exports::autostamp::magento::products_attribute_sets_groups_list as iface_products_attribute_sets_groups_list;
use serde_json::{Map, Value};

const OP_PRODUCTS_ATTRIBUTE_SETS_GROUPS_LIST_CATALOG_PRODUCT_ATTRIBUTE_GROUP_REPOSITORY_V1_GET_LIST_GET: OpSpec = OpSpec {
    method: "GET",
    path_template: "/V1/products/attribute-sets/groups/list",
    fields: &[
        FieldSpec { snake: "search_criteria_filter_groups_0_filters_0_field", wire: "searchCriteria[filterGroups][0][filters][0][field]", location: FieldLocation::Query },
        FieldSpec { snake: "search_criteria_filter_groups_0_filters_0_value", wire: "searchCriteria[filterGroups][0][filters][0][value]", location: FieldLocation::Query },
        FieldSpec { snake: "search_criteria_filter_groups_0_filters_0_condition_type", wire: "searchCriteria[filterGroups][0][filters][0][conditionType]", location: FieldLocation::Query },
        FieldSpec { snake: "search_criteria_sort_orders_0_field", wire: "searchCriteria[sortOrders][0][field]", location: FieldLocation::Query },
        FieldSpec { snake: "search_criteria_sort_orders_0_direction", wire: "searchCriteria[sortOrders][0][direction]", location: FieldLocation::Query },
        FieldSpec { snake: "search_criteria_page_size", wire: "searchCriteria[pageSize]", location: FieldLocation::Query },
        FieldSpec { snake: "search_criteria_current_page", wire: "searchCriteria[currentPage]", location: FieldLocation::Query },
    ],
    auth: &[
    ],
};

fn iface_products_attribute_sets_groups_list__eav_data_attribute_group_search_results_interface__to_json(p: &iface_products_attribute_sets_groups_list::EavDataAttributeGroupSearchResultsInterface) -> Value {
    let mut m = Map::new();
    m.insert("items".into(), Value::Array((&p.items).iter().map(|v| iface_products_attribute_sets_groups_list__eav_data_attribute_group_interface__to_json(v)).collect()));
    m.insert("search_criteria".into(), iface_products_attribute_sets_groups_list__framework_search_criteria_interface__to_json(&p.search_criteria));
    m.insert("total_count".into(), Value::Number(serde_json::Number::from(*(&p.total_count))));
    Value::Object(m)
}

fn iface_products_attribute_sets_groups_list__eav_data_attribute_group_interface__to_json(p: &iface_products_attribute_sets_groups_list::EavDataAttributeGroupInterface) -> Value {
    let mut m = Map::new();
    m.insert("attribute_group_id".into(), match (&p.attribute_group_id) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("attribute_group_name".into(), match (&p.attribute_group_name) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("attribute_set_id".into(), match (&p.attribute_set_id) { Some(v) => Value::Number(serde_json::Number::from(*(v))), None => Value::Null });
    m.insert("extension_attributes".into(), match (&p.extension_attributes) { Some(v) => iface_products_attribute_sets_groups_list__eav_data_attribute_group_extension_interface__to_json(v), None => Value::Null });
    Value::Object(m)
}

fn iface_products_attribute_sets_groups_list__eav_data_attribute_group_extension_interface__to_json(p: &iface_products_attribute_sets_groups_list::EavDataAttributeGroupExtensionInterface) -> Value {
    let mut m = Map::new();
    m.insert("attribute_group_code".into(), match (&p.attribute_group_code) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("sort_order".into(), match (&p.sort_order) { Some(v) => Value::String((v).clone()), None => Value::Null });
    Value::Object(m)
}

fn iface_products_attribute_sets_groups_list__framework_search_criteria_interface__to_json(p: &iface_products_attribute_sets_groups_list::FrameworkSearchCriteriaInterface) -> Value {
    let mut m = Map::new();
    m.insert("current_page".into(), match (&p.current_page) { Some(v) => Value::Number(serde_json::Number::from(*(v))), None => Value::Null });
    m.insert("filter_groups".into(), Value::Array((&p.filter_groups).iter().map(|v| iface_products_attribute_sets_groups_list__framework_search_filter_group__to_json(v)).collect()));
    m.insert("page_size".into(), match (&p.page_size) { Some(v) => Value::Number(serde_json::Number::from(*(v))), None => Value::Null });
    m.insert("sort_orders".into(), match (&p.sort_orders) { Some(v) => Value::Array((v).iter().map(|v| iface_products_attribute_sets_groups_list__framework_sort_order__to_json(v)).collect()), None => Value::Null });
    Value::Object(m)
}

fn iface_products_attribute_sets_groups_list__framework_search_filter_group__to_json(p: &iface_products_attribute_sets_groups_list::FrameworkSearchFilterGroup) -> Value {
    let mut m = Map::new();
    m.insert("filters".into(), match (&p.filters) { Some(v) => Value::Array((v).iter().map(|v| iface_products_attribute_sets_groups_list__framework_filter__to_json(v)).collect()), None => Value::Null });
    Value::Object(m)
}

fn iface_products_attribute_sets_groups_list__framework_filter__to_json(p: &iface_products_attribute_sets_groups_list::FrameworkFilter) -> Value {
    let mut m = Map::new();
    m.insert("condition_type".into(), match (&p.condition_type) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("field".into(), Value::String((&p.field).clone()));
    m.insert("value".into(), Value::String((&p.value).clone()));
    Value::Object(m)
}

fn iface_products_attribute_sets_groups_list__framework_sort_order__to_json(p: &iface_products_attribute_sets_groups_list::FrameworkSortOrder) -> Value {
    let mut m = Map::new();
    m.insert("direction".into(), Value::String((&p.direction).clone()));
    m.insert("field".into(), Value::String((&p.field).clone()));
    Value::Object(m)
}

fn iface_products_attribute_sets_groups_list__catalog_product_attribute_group_repository_v1_get_list_get_params__to_json(p: &iface_products_attribute_sets_groups_list::CatalogProductAttributeGroupRepositoryV1GetListGetParams) -> Value {
    let mut m = Map::new();
    m.insert("search_criteria_filter_groups_0_filters_0_field".into(), match (&p.search_criteria_filter_groups_v0_filters_v0_field) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("search_criteria_filter_groups_0_filters_0_value".into(), match (&p.search_criteria_filter_groups_v0_filters_v0_value) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("search_criteria_filter_groups_0_filters_0_condition_type".into(), match (&p.search_criteria_filter_groups_v0_filters_v0_condition_type) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("search_criteria_sort_orders_0_field".into(), match (&p.search_criteria_sort_orders_v0_field) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("search_criteria_sort_orders_0_direction".into(), match (&p.search_criteria_sort_orders_v0_direction) { Some(v) => Value::String((v).clone()), None => Value::Null });
    m.insert("search_criteria_page_size".into(), match (&p.search_criteria_page_size) { Some(v) => Value::Number(serde_json::Number::from(*(v))), None => Value::Null });
    m.insert("search_criteria_current_page".into(), match (&p.search_criteria_current_page) { Some(v) => Value::Number(serde_json::Number::from(*(v))), None => Value::Null });
    Value::Object(m)
}

fn iface_products_attribute_sets_groups_list__eav_data_attribute_group_search_results_interface__from_json(v: &Value) -> Option<iface_products_attribute_sets_groups_list::EavDataAttributeGroupSearchResultsInterface> {
    let m = v.as_object()?;
    Some(iface_products_attribute_sets_groups_list::EavDataAttributeGroupSearchResultsInterface {
        items: m.get("items").and_then(|v| (v).as_array().map(|a| a.iter().filter_map(|x| iface_products_attribute_sets_groups_list__eav_data_attribute_group_interface__from_json(x)).collect())).unwrap_or_default(),
        search_criteria: match m.get("search_criteria").and_then(|v| iface_products_attribute_sets_groups_list__framework_search_criteria_interface__from_json(v)) { Some(x) => x, None => return None },
        total_count: m.get("total_count").and_then(|v| (v).as_i64().map(|n| n as i32)).unwrap_or_default(),
    })
}

fn iface_products_attribute_sets_groups_list__eav_data_attribute_group_interface__from_json(v: &Value) -> Option<iface_products_attribute_sets_groups_list::EavDataAttributeGroupInterface> {
    let m = v.as_object()?;
    Some(iface_products_attribute_sets_groups_list::EavDataAttributeGroupInterface {
        attribute_group_id: m.get("attribute_group_id").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        attribute_group_name: m.get("attribute_group_name").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        attribute_set_id: m.get("attribute_set_id").filter(|v| !v.is_null()).and_then(|v| (v).as_i64().map(|n| n as i32)),
        extension_attributes: m.get("extension_attributes").filter(|v| !v.is_null()).and_then(|v| iface_products_attribute_sets_groups_list__eav_data_attribute_group_extension_interface__from_json(v)),
    })
}

fn iface_products_attribute_sets_groups_list__eav_data_attribute_group_extension_interface__from_json(v: &Value) -> Option<iface_products_attribute_sets_groups_list::EavDataAttributeGroupExtensionInterface> {
    let m = v.as_object()?;
    Some(iface_products_attribute_sets_groups_list::EavDataAttributeGroupExtensionInterface {
        attribute_group_code: m.get("attribute_group_code").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        sort_order: m.get("sort_order").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
    })
}

fn iface_products_attribute_sets_groups_list__framework_search_criteria_interface__from_json(v: &Value) -> Option<iface_products_attribute_sets_groups_list::FrameworkSearchCriteriaInterface> {
    let m = v.as_object()?;
    Some(iface_products_attribute_sets_groups_list::FrameworkSearchCriteriaInterface {
        current_page: m.get("current_page").filter(|v| !v.is_null()).and_then(|v| (v).as_i64().map(|n| n as i32)),
        filter_groups: m.get("filter_groups").and_then(|v| (v).as_array().map(|a| a.iter().filter_map(|x| iface_products_attribute_sets_groups_list__framework_search_filter_group__from_json(x)).collect())).unwrap_or_default(),
        page_size: m.get("page_size").filter(|v| !v.is_null()).and_then(|v| (v).as_i64().map(|n| n as i32)),
        sort_orders: m.get("sort_orders").filter(|v| !v.is_null()).and_then(|v| (v).as_array().map(|a| a.iter().filter_map(|x| iface_products_attribute_sets_groups_list__framework_sort_order__from_json(x)).collect())),
    })
}

fn iface_products_attribute_sets_groups_list__framework_search_filter_group__from_json(v: &Value) -> Option<iface_products_attribute_sets_groups_list::FrameworkSearchFilterGroup> {
    let m = v.as_object()?;
    Some(iface_products_attribute_sets_groups_list::FrameworkSearchFilterGroup {
        filters: m.get("filters").filter(|v| !v.is_null()).and_then(|v| (v).as_array().map(|a| a.iter().filter_map(|x| iface_products_attribute_sets_groups_list__framework_filter__from_json(x)).collect())),
    })
}

fn iface_products_attribute_sets_groups_list__framework_filter__from_json(v: &Value) -> Option<iface_products_attribute_sets_groups_list::FrameworkFilter> {
    let m = v.as_object()?;
    Some(iface_products_attribute_sets_groups_list::FrameworkFilter {
        condition_type: m.get("condition_type").filter(|v| !v.is_null()).and_then(|v| (v).as_str().map(|s| s.to_string())),
        field: m.get("field").and_then(|v| (v).as_str().map(|s| s.to_string())).unwrap_or_default(),
        value: m.get("value").and_then(|v| (v).as_str().map(|s| s.to_string())).unwrap_or_default(),
    })
}

fn iface_products_attribute_sets_groups_list__framework_sort_order__from_json(v: &Value) -> Option<iface_products_attribute_sets_groups_list::FrameworkSortOrder> {
    let m = v.as_object()?;
    Some(iface_products_attribute_sets_groups_list::FrameworkSortOrder {
        direction: m.get("direction").and_then(|v| (v).as_str().map(|s| s.to_string())).unwrap_or_default(),
        field: m.get("field").and_then(|v| (v).as_str().map(|s| s.to_string())).unwrap_or_default(),
    })
}

fn iface_products_attribute_sets_groups_list__catalog_product_attribute_group_repository_v1_get_list_get__ok(body: String) -> Result<iface_products_attribute_sets_groups_list::EavDataAttributeGroupSearchResultsInterface, crate::runtime::DispatchError> {
    let v: Value = match serde_json::from_str(&body) {
        Ok(v) => v,
        Err(e) => return Err(crate::runtime::DispatchError::Transport(format!("failed to decode response body as JSON: {e}"))),
    };
    match iface_products_attribute_sets_groups_list__eav_data_attribute_group_search_results_interface__from_json(&v) {
        Some(x) => Ok(x),
        None => Err(crate::runtime::DispatchError::Transport("response body did not match the expected schema".to_string())),
    }
}

fn iface_products_attribute_sets_groups_list__catalog_product_attribute_group_repository_v1_get_list_get__err(e: crate::runtime::DispatchError) -> iface_products_attribute_sets_groups_list::CatalogProductAttributeGroupRepositoryV1GetListGetError {
    match e {
        crate::runtime::DispatchError::Http { status, body } => match status {
            400u16 => iface_products_attribute_sets_groups_list::CatalogProductAttributeGroupRepositoryV1GetListGetError::BadRequest(body),
            401u16 => iface_products_attribute_sets_groups_list::CatalogProductAttributeGroupRepositoryV1GetListGetError::Unauthorized(body),
            _ => iface_products_attribute_sets_groups_list::CatalogProductAttributeGroupRepositoryV1GetListGetError::Other(body),
        },
        crate::runtime::DispatchError::Transport(m) => iface_products_attribute_sets_groups_list::CatalogProductAttributeGroupRepositoryV1GetListGetError::Other(m),
    }
}

impl iface_products_attribute_sets_groups_list::Guest for crate::Component {
    fn catalog_product_attribute_group_repository_v1_get_list_get(params: iface_products_attribute_sets_groups_list::CatalogProductAttributeGroupRepositoryV1GetListGetParams) -> Result<iface_products_attribute_sets_groups_list::EavDataAttributeGroupSearchResultsInterface, iface_products_attribute_sets_groups_list::CatalogProductAttributeGroupRepositoryV1GetListGetError> {
        let json = iface_products_attribute_sets_groups_list__catalog_product_attribute_group_repository_v1_get_list_get_params__to_json(&params);
        match dispatch(&OP_PRODUCTS_ATTRIBUTE_SETS_GROUPS_LIST_CATALOG_PRODUCT_ATTRIBUTE_GROUP_REPOSITORY_V1_GET_LIST_GET, json).and_then(iface_products_attribute_sets_groups_list__catalog_product_attribute_group_repository_v1_get_list_get__ok) {
            Ok(v) => Ok(v),
            Err(e) => Err(iface_products_attribute_sets_groups_list__catalog_product_attribute_group_repository_v1_get_list_get__err(e)),
        }
    }
}
