//! Render a `Cargo.toml` manifest for a generated component crate.

use crate::PackageName;

/// Render the `Cargo.toml` for the generated WebAssembly component crate.
///
/// The crate builds as a `cdylib` (the component shape) and depends on `wit-bindgen`
/// for the exported component bindings, `serde_json`, which the generated `*_to_json`
/// helpers use, and `wstd`, whose HTTP client the request runtime uses to perform calls.
/// The crate name and version are taken from `package`.
///
/// The emitted `[profile.release]` optimizes the component for size (`opt-level = "s"`)
/// and splits code generation into many small units (`codegen-units = 256`). Large APIs
/// produce very large crates (e.g. docusign is ~90k lines / ~400 operations); a high
/// codegen-unit count keeps each LLVM module small so the backend parallelizes and its
/// peak memory stays bounded, while `"s"` keeps the resulting `.wasm` compact. Very large
/// specs can still exceed the compiler's memory on a small machine — see the README.
pub(crate) fn render(package: &PackageName) -> String {
    let name = &package.name;
    let version = package.version.as_deref().unwrap_or("0.1.0");
    format!(
        r#"# AUTOGENERATED by openapi-bindgen. Do not edit by hand.
[package]
name = "{name}"
version = "{version}"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde_json = "1"
wit-bindgen = "0.41"
wstd = {{ version = "0.6", default-features = false }}

[profile.release]
opt-level = "s"
codegen-units = 256
"#
    )
}

/// Render the `wasm.toml` for a generated component: a `[package]` section with the publish
/// metadata `component publish` needs, plus the WIT interface dependencies the component
/// imports.
///
/// The `[package]` section targets the `<namespace>` org on GHCR
/// (`ghcr.io/<namespace>/<name>`) and points `file` at `build/<name>.wasm`, where the build
/// step deposits the compiled component. `version` is the full publish version, including any
/// provider/schema build metadata (e.g. `0.1.0+github-2022-11-28`).
///
/// The dependencies are written in the explicit table form (`registry`/`namespace`/`package`/
/// `version`) so `component install` resolves them straight from GHCR without a meta-registry.
/// `wasi:http` is imported transitively — the runtime performs requests with the `wstd` HTTP
/// client, whose bindings import it — while `wasmcloud:secrets` provides the credentials the
/// runtime fetches.
pub(crate) fn render_wasm_manifest(package: &PackageName, publish_version: &str) -> String {
    let namespace = &package.namespace;
    let name = &package.name;
    format!(
        r#"# AUTOGENERATED by openapi-bindgen. Do not edit by hand.
[package]
name = "{namespace}:{name}"
version = "{publish_version}"
registry = "ghcr.io/{namespace}/{name}"
kind = "component"
file = "build/{name}.wasm"
description = "WebAssembly component bindings for the {name} API, generated from an OpenAPI document."
license = "Apache-2.0 WITH LLVM-exception"
source = "https://github.com/yoshuawuyts/openapi-bindgen"

[dependencies.components]

[dependencies.interfaces]
"wasi:http" = {{ registry = "ghcr.io", namespace = "webassembly", package = "wasi/http", version = "0.2.3" }}
"wasmcloud:secrets" = {{ registry = "ghcr.io", namespace = "wasmcloud", package = "interfaces/wasmcloud/secrets", version = "1.0.0" }}
"#
    )
}

#[cfg(test)]
mod tests {
    use super::{render, render_wasm_manifest};
    use crate::PackageName;

    fn package() -> PackageName {
        PackageName::parse("autostamp:nasa@0.1.0").unwrap()
    }

    #[test]
    fn cargo_toml_uses_base_version() {
        let cargo = render(&package());
        assert!(cargo.contains("name = \"nasa\""));
        // Build metadata never leaks into Cargo.toml — it stays clean SemVer.
        assert!(cargo.contains("version = \"0.1.0\""));
        assert!(cargo.contains("crate-type = [\"cdylib\"]"));
    }

    #[test]
    fn cargo_toml_depends_on_wstd_for_the_http_runtime() {
        let cargo = render(&package());
        // The request runtime performs calls with the `wstd` HTTP client; its default `json`
        // feature is unused (bodies are assembled with serde_json), so it is disabled.
        assert!(cargo.contains("wstd = { version = \"0.6\", default-features = false }"));
    }

    #[test]
    fn cargo_toml_emits_size_and_memory_tuned_release_profile() {
        let cargo = render(&package());
        // Size-optimized components and a high codegen-unit count so large
        // crates keep the backend's peak memory bounded.
        assert!(cargo.contains("[profile.release]"));
        assert!(cargo.contains("opt-level = \"s\""));
        assert!(cargo.contains("codegen-units = 256"));
    }

    #[test]
    fn wasm_toml_has_package_section_targeting_the_namespace_org() {
        let wasm = render_wasm_manifest(&package(), "0.1.0+2022-11-28");
        assert!(wasm.contains("[package]"));
        assert!(wasm.contains("name = \"autostamp:nasa\""));
        assert!(wasm.contains("version = \"0.1.0+2022-11-28\""));
        assert!(wasm.contains("registry = \"ghcr.io/autostamp/nasa\""));
        assert!(wasm.contains("kind = \"component\""));
        assert!(wasm.contains("file = \"build/nasa.wasm\""));
        assert!(wasm.contains("license = \"Apache-2.0 WITH LLVM-exception\""));
    }

    #[test]
    fn wasm_toml_uses_explicit_interface_deps() {
        let wasm = render_wasm_manifest(&package(), "0.1.0");
        // Explicit table form resolves from GHCR without a meta-registry.
        assert!(wasm.contains(
            "\"wasi:http\" = { registry = \"ghcr.io\", namespace = \"webassembly\", package = \"wasi/http\", version = \"0.2.3\" }"
        ));
        assert!(wasm.contains(
            "\"wasmcloud:secrets\" = { registry = \"ghcr.io\", namespace = \"wasmcloud\", package = \"interfaces/wasmcloud/secrets\", version = \"1.0.0\" }"
        ));
    }
}
