package autostamp:azure@0.2.1;

interface operations {
  operations-list: func() -> result<string, string>;

}


interface addon-status {
  support-plan-types-list-info: func() -> result<string, string>;

}

interface addon-details {
  support-plan-types-get: func() -> result<string, string>;

  support-plan-types-create-or-update: func() -> result<string, string>;

}

interface subscriptions {
  support-plan-types-delete: func() -> result<string, string>;

}
/// The component world: imports the secrets host capability
/// the runtime uses and exports the generated interfaces. The HTTP host
/// capability is imported by the `wstd` crate's bindings at build time.
world client {
  import wasmcloud:secrets/store@1.0.0;
  import wasmcloud:secrets/reveal@1.0.0;
  export operations;
  export addon-status;
  export addon-details;
  export subscriptions;
}
